/// Phase 396 - the ONE reading of the repository's approval switches.
///
/// A committed artefact in this repository is a PROJECTION of something else (a public-surface
/// baseline, a wire baseline, a generated F# module, a README block, a ratchet file), and each
/// family that holds one is regenerated by setting an environment variable and re-running its
/// tests. There are eleven such switches (`CORE_APPROVE_API`, `_WIRE`, `_LADDER`, `_README`,
/// `_DOCS`, and `FUARAN_REGEN` at the generated-module sites); before this module each site read
/// its own variable with its own idea of "set" (`<> "" && <> "0"` at some, `= "1"` at others), and
/// none of them could be aimed at one file.
///
/// THE RULE (one truthiness, documented here and in CONTRIBUTING.md and STABILITY.md):
///
///   * absent, empty, `0` or `false` -> NOT requested;
///   * `1` or `true` (any case)      -> requested for EVERY file the switch governs;
///   * anything else                 -> requested for the named file(s) only: the value is a filter,
///                                      a comma-separated list of file stems (a package id for the
///                                      API and wire baselines, the file name without its
///                                      extension for a generated module).
///
/// A filter that names nothing the switch governs is RED BY NAME, never a silent no-op, and every
/// file a switch rewrites is printed, so the "stage by name" step reads the list.
module Fuaran.Core.Tests.Approval

open System
open System.IO
open Expecto

/// How a switch is set. `Everything` is the bare `1` / `true`; `Only` carries the filter's stems.
type Request =
    | NotRequested
    | Everything
    | Only of string list

/// The switches this repository reads. The sweep in ApprovalTests holds every site to this list.
[<Literal>]
let Api = "CORE_APPROVE_API"

[<Literal>]
let Wire = "CORE_APPROVE_WIRE"

[<Literal>]
let Ladder = "CORE_APPROVE_LADDER"

[<Literal>]
let Readme = "CORE_APPROVE_README"

[<Literal>]
let Docs = "CORE_APPROVE_DOCS"

[<Literal>]
let Regen = "FUARAN_REGEN"

/// Stems of the generated modules `FUARAN_REGEN` governs (the file name without its extension).
module Regenerated =
    [<Literal>]
    let Derive = "DeriveGenerated"

    [<Literal>]
    let DocAnnotated = "DocAnnotatedGenerated"

    [<Literal>]
    let SpecDecoders = "SpecDecodersGenerated"

    [<Literal>]
    let Mini = "MiniGenerated"

    [<Literal>]
    let Spike = "spike"

    [<Literal>]
    let Doc = "DocGenerated"

/// Stems of the two projections `CORE_APPROVE_LADDER` governs (both rewrite blocks of proofs/README.md).
module Ladders =
    [<Literal>]
    let Summary = "ladder"

    [<Literal>]
    let Operations = "operations"

/// Stems of the single files the remaining switches govern.
module Files =
    [<Literal>]
    let Readme = "README"

    [<Literal>]
    let DocCoverage = "doc-coverage"

/// The stems a switch governs when they are fixed in source. The API and wire switches are NOT
/// here: their stems are the packable roster, known only at run time, so their sites check the
/// filter with `requireMatched` against the roster they iterate.
let fixedStems (name: string) : string list option =
    match name with
    | Regen ->
        Some
            [ Regenerated.Derive
              Regenerated.DocAnnotated
              Regenerated.SpecDecoders
              Regenerated.Mini
              Regenerated.Spike
              Regenerated.Doc ]
    | Ladder -> Some [ Ladders.Summary; Ladders.Operations ]
    | Readme -> Some [ Files.Readme ]
    | Docs -> Some [ Files.DocCoverage ]
    | _ -> None

/// The pure reading of a switch's value; the one place the truthiness rule lives.
let parse (value: string) : Request =
    match value with
    | null -> NotRequested
    | v ->
        let t = v.Trim()

        if t = "" || t = "0" || t.Equals("false", StringComparison.OrdinalIgnoreCase) then
            NotRequested
        elif t = "1" || t.Equals("true", StringComparison.OrdinalIgnoreCase) then
            Everything
        else
            t.Split([| ',' |], StringSplitOptions.RemoveEmptyEntries ||| StringSplitOptions.TrimEntries)
            |> List.ofArray
            |> function
                | [] -> NotRequested
                | stems -> Only stems

let private read (name: string) : Request =
    parse (Environment.GetEnvironmentVariable name)

/// Is the switch set at all (for every file, or for a filter)?
let requested (name: string) : bool = read name <> NotRequested

/// The switch's filter, when its value is one: the stems as written, comma-joined; else `None`.
let scope (name: string) : string option =
    match read name with
    | Only stems -> Some(String.concat "," stems)
    | NotRequested
    | Everything -> None

let private same (a: string) (b: string) =
    String.Equals(a, b, StringComparison.OrdinalIgnoreCase)

// ---- the pure core: each decision takes the Request it is deciding about, so the tests
// ---- exercise it without ever setting a real switch in the shared process environment.

/// The filter's stems that match none of `stems` (always empty for a bare `1` or an unset switch).
let unmatchedFor (request: Request) (stems: string list) : string list =
    match request with
    | Only wanted -> wanted |> List.filter (fun w -> not (stems |> List.exists (same w)))
    | NotRequested
    | Everything -> []

/// Red, by name, when `request` carries a filter naming something outside `stems`.
let requireMatchedFor (request: Request) (name: string) (stems: string list) : unit =
    match unmatchedFor request stems with
    | [] -> ()
    | bad ->
        failtestf
            "%s=%s names nothing it governs: %s. It governs: %s. A filter that matches nothing is an error, never a no-op."
            name
            (match request with
             | Only s -> String.concat "," s
             | _ -> "")
            (String.concat ", " bad)
            (match stems with
             | [] -> "(no files)"
             | _ -> String.concat ", " stems)

/// May the site holding `stem` rewrite its file under `request`? For a switch whose stems are fixed
/// in source a filter naming no known stem is red here, so a mistyped filter cannot pass quietly.
let admitsFor (request: Request) (name: string) (stem: string) : bool =
    fixedStems name |> Option.iter (requireMatchedFor request name)

    match request with
    | NotRequested -> false
    | Everything -> true
    | Only wanted -> wanted |> List.exists (same stem)

/// Write `text` to `path` when `request` admits the site and the bytes differ, printing the file so
/// the "stage by name" step reads the list. Returns whether the file was rewritten.
let writeFor (request: Request) (name: string) (stem: string) (path: string) (text: string) : bool =
    if not (admitsFor request name stem) then
        false
    else
        let existing = if File.Exists path then File.ReadAllText path else null

        if existing = text then
            false
        else
            File.WriteAllText(path, text)
            printfn "%s: wrote %s" name path
            true

// ---- the environment-reading surface every site uses ---------------------------------------

/// The filter's stems that match none of `stems`, for the switch as the environment sets it.
let unmatched (name: string) (stems: string list) : string list = unmatchedFor (read name) stems

/// Red, by name, when the switch carries a filter naming something outside `stems`.
let requireMatched (name: string) (stems: string list) : unit =
    requireMatchedFor (read name) name stems

/// May the site holding `stem` rewrite its file now?
let admits (name: string) (stem: string) : bool = admitsFor (read name) name stem

/// Write `text` to `path` when the site is admitted and the bytes differ; see `writeFor`.
let write (name: string) (stem: string) (path: string) (text: string) : bool =
    writeFor (read name) name stem path text
