/// Phase 337 — the `conformance/decode/` vectors as an IDL vocabulary, so the interpreter and both
/// generated hosts can be held to the decode error contract those vectors pin.
///
/// The vectors are written over a SHAPE grammar (`string`, `list`, `object`, `tagged`, `ref`, …),
/// not over a vocabulary, and every generated host's one decode entry point is a NODE root. So each
/// vector whose shape the IDL can declare becomes one kind of this vocabulary, `V<NN>`, with a single
/// required member `v` of the translated type, and its input is decoded as that member of a flat node:
/// `{"id":"n","kind":"V<NN>","v":<input>}`. The vocabulary's discriminator is `kind` — the key every
/// `tagged` vector uses — and a refusal the vector places at `path` is expected at `["v", …path]`
/// (a parse refusal stays at the root).
///
/// A vector whose shape carries something the IDL does not declare is EXCLUDED, with its reason —
/// an item bound, an int range, an admit list, a closed object a refusal depends on, an unresolved
/// reference, a member name that is not an identifier. The exclusions are the IDL's own boundary,
/// not a gap in a host: no vocabulary can state them, so no generated host can be asked to.
///
/// `DecodeVectorsGenerated.fs` is this vocabulary's generated F# module, compiled into the suite and
/// regenerated by `--regen-snapshots`; a drift guard fails when the vectors move and it does not.
module Fuaran.Core.Tests.DecodeVectorsIdl

open System.IO
open System.Text.RegularExpressions
open Fuaran.Core
open Fuaran.Core.Idl

/// One vector of the family, as the file states it.
type DecodeVector =
    {
        Name: string
        Input: string
        /// The refusal the vector pins (its code's wire name and its path), or `None` for an
        /// accepted input.
        Refusal: (string * PathSegment list) option
        Shape: JVal
        Definitions: (string * JVal) list
    }

/// The vector file, relative to the repository root.
let vectorsFile = "conformance/decode/decode-rejects.json"

let private str (name: string) (o: JVal) : string option =
    match Decoder.tryMember name o with
    | Some(JStr s) -> Some s
    | _ -> None

let private flag (name: string) (o: JVal) : bool =
    match Decoder.tryMember name o with
    | Some(JBool b) -> b
    | _ -> false

let private items (name: string) (o: JVal) : JVal list =
    match Decoder.tryMember name o with
    | Some(JArr xs) -> xs
    | _ -> []

/// Every vector in the family file.
let load () : DecodeVector list =
    let text = File.ReadAllText(Snapshots.repoFile vectorsFile)

    let root =
        match Json.parse text with
        | Ok j -> j
        | Error e -> failwithf "%s does not parse: %s" vectorsFile e

    items "vectors" root
    |> List.map (fun v ->
        let refusal =
            match Decoder.tryMember "refusal" v with
            | Some r ->
                let path =
                    match Decoder.tryMember "path" r |> Option.bind DecodePath.ofJson with
                    | Some p -> p
                    | None -> failwithf "a vector's refusal path is not a path: %A" r

                Some(Option.defaultValue "" (str "code" r), path)
            | None -> None

        { Name = Option.defaultValue "" (str "name" v)
          Input = Option.defaultValue "" (str "input" v)
          Refusal = refusal
          Shape = Decoder.tryMember "shape" v |> Option.defaultValue (JObj [])
          Definitions =
            match Decoder.tryMember "definitions" v with
            | Some(JObj ds) -> ds
            | _ -> [] })

let private identifier = Regex "^[A-Za-z_][A-Za-z0-9_]*$"

/// Why the IDL cannot declare this vector's shape, or `None` when it can.
let exclusion (v: DecodeVector) : string option =
    let refusing = v.Refusal.IsSome

    let rec reason (shape: JVal) : string option =
        match str "$type" shape with
        | Some("string" | "int" | "float" | "bool" | "any") -> None
        | Some "list" ->
            if (Decoder.tryMember "maxItems" shape).IsSome then
                Some "an item bound (maxItems): the IDL declares none"
            else
                Decoder.tryMember "of" shape |> Option.bind reason
        | Some "object" ->
            let fields = items "fields" shape

            if refusing && flag "closed" shape then
                Some "a closed object the refusal depends on: an IDL decoder tolerates an undeclared member"
            else
                match
                    fields
                    |> List.tryPick (fun f ->
                        match str "name" f with
                        | Some n when not (identifier.IsMatch n) -> Some n
                        | _ -> None)
                with
                | Some n -> Some(sprintf "the member name %A: an IDL field name is an identifier" n)
                | None ->
                    fields
                    |> List.tryPick (fun f -> Decoder.tryMember "shape" f |> Option.bind reason)
        | Some "tagged" ->
            if (Decoder.tryMember "admit" shape).IsSome then
                Some "an admit list: the IDL declares no reader policy over a union's cases"
            elif str "key" shape <> Some "kind" then
                Some "a discriminator other than the vocabulary's"
            else
                items "cases" shape
                |> List.tryPick (fun c ->
                    match Decoder.tryMember "shape" c with
                    | Some s when str "$type" s = Some "object" -> reason s
                    | _ -> Some "a case that is not an object: an IDL union case is a set of members")
        | Some "intRange" -> Some "an int range: the IDL's int slot declares none"
        | Some "ref" ->
            match
                str "name" shape
                |> Option.bind (fun n -> v.Definitions |> List.tryFind (fun (k, _) -> k = n))
            with
            | None -> Some "an unresolved reference: a vocabulary cannot declare one (Declare.errors refuses it)"
            | Some(_, s) -> reason s
        | other -> Some(sprintf "the shape %A" other)

    reason v.Shape

/// The kind tag of the vector at `index` in the file.
let tagOf (index: int) = sprintf "V%02d" index

/// The translated vocabulary, with the vectors it covers (index in the file, vector) and the
/// excluded ones (vector, reason).
let build (vectors: DecodeVector list) : Idl * (int * DecodeVector) list * (DecodeVector * string) list =
    let records = ResizeArray<IdlRecord>()
    let unions = ResizeArray<IdlUnion>()

    let translate (index: int) (v: DecodeVector) : IdlType =
        let mutable n = 0

        let fresh (prefix: string) =
            n <- n + 1
            sprintf "%s%02d_%d" prefix index n

        let rec go (shape: JVal) : IdlType =
            match str "$type" shape with
            | Some "string" -> TStr
            | Some "int" -> TInt
            | Some "float" -> TFloat
            | Some "bool" -> TBool
            | Some "any" -> TJson
            | Some "list" -> TList(go (Decoder.tryMember "of" shape |> Option.defaultValue (JObj [])))
            | Some "object" ->
                let name = fresh "R"
                records.Add { Name = name; Fields = fields shape }
                TRecord name
            | Some "tagged" ->
                let name = fresh "U"

                let cases =
                    items "cases" shape
                    |> List.map (fun c ->
                        { Tag = Option.defaultValue "" (str "tag" c)
                          Fields = Decoder.tryMember "shape" c |> Option.map fields |> Option.defaultValue []
                          Annotations = Annotations.Empty })

                unions.Add
                    { Name = name
                      Params = []
                      Cases = cases }

                TUnion(name, [])
            | Some "ref" ->
                let target = str "name" shape |> Option.defaultValue ""
                go (v.Definitions |> List.find (fun (k, _) -> k = target) |> snd)
            | other -> failwithf "an excluded shape reached the translation: %A" other

        and fields (shape: JVal) : IdlField list =
            items "fields" shape
            |> List.map (fun f ->
                { Name = Option.defaultValue "" (str "name" f)
                  Type = go (Decoder.tryMember "shape" f |> Option.defaultValue (JObj []))
                  Opt = (if flag "optional" f then Optional else Required)
                  Annotations = Annotations.Empty })

        go v.Shape

    let indexed = List.indexed vectors

    let covered = indexed |> List.filter (fun (_, v) -> (exclusion v).IsNone)

    let excluded =
        indexed |> List.choose (fun (_, v) -> exclusion v |> Option.map (fun r -> v, r))

    let kinds =
        covered
        |> List.map (fun (i, v) ->
            { Tag = tagOf i
              Category = "decode"
              Annotations = Annotations.Empty
              Fields =
                [ { Name = "v"
                    Type = translate i v
                    Opt = Required
                    Annotations = Annotations.Empty } ] })

    let idl =
        { Kinds = kinds
          Unions = List.ofSeq unions
          Enums = []
          Records = List.ofSeq records
          Defaults = []
          NodeFields = []
          Ops = []
          Wire =
            { Discriminator = "kind"
              NodeEnvelope = NodeEnvelopeShape.FlatKind
              KeyOrder = KeyOrder.Sorted }
          Harden = HardenPolicy.Undeclared }

    idl, covered, excluded

/// The vocabulary over the vectors as the file stands.
let current () = build (load ())

/// The node document a covered vector's input is decoded as.
let document (index: int) (v: DecodeVector) : string =
    "{\"id\":\"n\",\"kind\":"
    + Canon.render (JStr(tagOf index))
    + ",\"v\":"
    + v.Input
    + "}"

/// Where the vector's refusal is expected in that document: a parse refusal at the root, every
/// other one under the member `v`.
let expectedRefusal (v: DecodeVector) : (string * PathSegment list) option =
    v.Refusal
    |> Option.map (fun (code, path) ->
        match code with
        | "InvalidJson"
        | "LimitExceeded" -> code, path
        | _ -> code, PathSegment.Key "v" :: path)

/// The generated module's name and file.
let moduleName = "Fuaran.Core.Tests.DecodeVectorsGenerated"
let generatedFile = "tests/Fuaran.Core.Tests/DecodeVectorsGenerated.fs"
