/// Phase 347 — the refusal corners as one vocabulary, so each is read by the interpreter, the compiled F#
/// host and the TypeScript host from one document.
///
/// One kind, `Corner`, holds a slot of every type a corner lives at: an int (`count`), a float
/// (`ratio`), a map of ints (`counts`), a list of ints (`items`), a verbatim JSON value (`meta`), and
/// the three sentinel slots — a required and an optional closure (`onClick`, `onHover`), a typed
/// handler (`onPick`) and an opaque value (`raw`). The node envelope is flat and the discriminator is
/// `kind`, as in the decode vectors' vocabulary.
///
/// `RefusalCornersGenerated.fs` is this vocabulary's generated F# module, compiled into the suite and
/// regenerated by `--regen-snapshots`; a drift guard fails when the generator moves and it does not.
module Fuaran.Core.Tests.RefusalCornersIdl

open Fuaran.Core.Idl

let private field (name: string) (t: IdlType) (opt: Optionality) : IdlField =
    { Name = name
      Type = t
      Opt = opt
      Annotations = Annotations.Empty }

/// The vocabulary.
let idl: Idl =
    { Kinds =
        [ { Tag = "Corner"
            Category = "corner"
            Annotations = Annotations.Empty
            Fields =
              [ field "count" TInt Required
                field "counts" (TMap TInt) Required
                field "items" (TList TInt) Required
                field "meta" TJson Required
                field "onClick" TClosure Required
                field "onHover" TClosure Optional
                field
                    "onPick"
                    (TFn
                        { FSharp = "int -> unit"
                          TypeScript = "(i: number) => void"
                          Placeholder = "ignore" })
                    Required
                field "ratio" TFloat Required
                field "raw" TOpaque Required ] } ]
      Unions = []
      Enums = []
      Records = []
      Defaults = []
      NodeFields = []
      Ops = []
      Wire =
        { Discriminator = "kind"
          NodeEnvelope = NodeEnvelopeShape.FlatKind
          KeyOrder = KeyOrder.Sorted }
      Harden = HardenPolicy.Undeclared }

/// A valid document, every member present: each corner is this document with one member rewritten.
let valid =
    """{"count":1,"counts":{"a":1},"id":"n","items":[1],"kind":"Corner","meta":{"x":1},"onClick":"<closure>","onHover":"<closure>","onPick":"<closure>","ratio":1.5,"raw":"<opaque>"}"""

/// The valid document with the member `name`'s value replaced by the raw JSON text `value`, or the
/// member removed when `value` is `None`.
let withMember (name: string) (value: string option) : string =
    let doc = Fuaran.Core.Json.parse valid |> Result.defaultWith failwith

    match doc with
    | Fuaran.Core.JObj fields ->
        let marker = "__corner_347__"

        let fields =
            fields
            |> List.choose (fun (k, v) ->
                if k <> name then
                    Some(k, v)
                else
                    value |> Option.map (fun _ -> k, Fuaran.Core.JStr marker))

        let text = Fuaran.Core.Canon.render (Fuaran.Core.JObj fields)

        match value with
        | Some raw -> text.Replace("\"" + marker + "\"", raw)
        | None -> text
    | _ -> failwith "the valid corner document is an object"

/// The generated module's name and file.
let moduleName = "Fuaran.Core.Tests.RefusalCornersGenerated"
let generatedFile = "tests/Fuaran.Core.Tests/RefusalCornersGenerated.fs"
