(*
   DocVocabularyProofs — GENERATED by Fuaran.Core.Idl.Codegen's F* target, from the same walk that
   emits `DocVocabulary.fst`, over
   the vendored SECOND-DOMAIN sample — `tests/Fuaran.Core.Tests/SecondDomainSpike.fs`,
   a document vocabulary with a corpus written outside this repository, on the
   declared non-default wire shape the reference vocabulary does not use
   (fuaran-core Phase 173, applying D14 to `proofs/`).
   DO NOT EDIT: `dotnet run --project tests/Fuaran.Core.Tests -- --emit-fstar` regenerates
   it, and the `Proofs.Vocabulary` family holds this file to a fresh generation from that
   source — a vocabulary that moves without a regeneration is VOCABULARY DRIFT, and
   `proofs/check.ps1` names it.

   WHAT IS PROVED, and why it is GENERATED rather than written.

   Phase 135 proved `decode (encode n) == Ok n` for a hand-written four-case REFERENCE
   vocabulary, and was explicit about the boundary: a theorem about a reference vocabulary
   is not a theorem about the one a host actually decodes. The real vocabulary has dozens
   of kinds — 11 of this one's 11 are modelled — and it grows. A HAND-WRITTEN proof over
   it would be a theorem about the vocabulary as it stood on the day it was written, which
   is the same defect one release later. So the proof script is emitted by the walk that
   emits the model: a kind added to the IDL re-proves itself at the next `check.ps1`, and a
   kind whose encoder and decoder disagree fails it.

     - `rt_node` and the family beside it — THE ROUND TRIP. For every value of every
       modelled type, decoding its encoding returns that value: `dec_node (enc_node x) ==
       Ok x`, at every depth, through every list, map, optional member and omit-default.
     - `dec_node_total` — TOTALITY, and the exclusivity of the outcome. That the decoders
       type-check at `Tot` is the termination proof; the lemma states that every input
       reaches exactly one of `Ok` / `Error` and never both.

   THE SHAPE — one lemma per constructor, and the presence split LINEAR in the conditional
   members (fuaran-core Phase 182, replacing Phase 168's per-pattern split).
   A constructor with k conditional members (optional, or omitted at its default) encodes
   to 2^k object shapes, and a lemma over the whole constructor puts all of them in ONE
   query. Measured at a twenty-kind vocabulary whose node envelope carried five optional
   members (Phase 150): the node lemma's 65-goal query failed a `--quake` seed at the leg's
   rlimit, the widest kind's arm failed outright, and raising the rlimit turned failing into
   grinding. `--split_queries` is not settable as a pragma on the pinned prover, so the
   isolation is in the emitted shape instead. `rt_<T>` is the round trip over a type — for a
   type with several constructors, a CASE SPLIT whose arms cite `rt_<T>__<Ctor>`, one
   constructor's arm alone under `C__<T>__<Ctor>? x`. A constructor with
   2 or more conditional members is proved from its members' LOOKUPS instead of in one
   query: `lk_<T>__<Ctor>__<member>` reads one key off the encoded object with every OTHER
   conditional member left free — one lemma for a member that is always emitted, two for a
   conditional one — and the constructor's lemma cites them a member at a time. That is
   2k + r' lemmas where Phase 168 emitted 2^k, and it is why a sixteen-conditional kind
   costs thirty-odd lemmas rather than 65,536 (`fuaran#1754` measured 71,722 of them in a
   114 MB script at the UI vocabulary). The family is still one mutual induction — a kind's
   children reach `rt_node` — on the lexicographic measure `%[x; tier]`; the lookups are
   NOT in it, since they recurse on nothing, which is what lets each carry the scoped
   `--fuel` its own walk needs. The rlimit precedent Phase 150 took (`--z3rlimit 200` in
   this file) stays retired: the leg's own rlimit is what these are checked under, and a
   query that wants more is a query the split has failed to isolate.

   WHAT IS NOT PROVED HERE, and why. The `wf` CHARACTERISATION — `Ok? (dec el) == wf el`,
   which Phase 135 carries for its hand-written reference vocabulary — is not restated over
   the generated vocabulary. The only predicate this emitter could generate from the same
   walk is the decoder's own accept set restated clause for clause, and `Ok? (dec el) ==
   (that predicate) el` is then a theorem about two renderings of one definition — true,
   and empty. A characterisation worth the name needs an INDEPENDENT statement of the
   accept set (a schema-shaped predicate), which is a model-sized artefact of its own;
   `proofs/README.md` (theorem 1) records the halt. The round trip covers one direction
   (everything the encoder can produce is read back exactly); the characterisation of what
   ELSE is accepted is not covered, and is named here rather than left to be assumed.

   ONE COST OPTION IS PART OF THE ARTEFACT: `--ext context_pruning` is set below for the
   reason the model module's header gives at greater length — a mutual induction over the
   whole family would otherwise carry the whole family in every query. If this module is
   ever slow enough to want investigating, check it is still in force first.

   Apache-2.0, like everything beside it.
*)
module DocVocabularyProofs

open WireDecode
open DocVocabulary

#set-options "--ext context_pruning"

(* ======================================================================================
   1. The closed string sets. Each is a finite match on distinct literals, so its round
      trip is definitional — stated anyway, because the family below calls it by name.
   ====================================================================================== *)

let rt_e_locale (#num #flt: eqtype) (x: e_locale) : Lemma (ensures dec_e_locale (enc_e_locale #num #flt x) == Ok x) = ()
let rt_e_numbering (#num #flt: eqtype) (x: e_numbering) : Lemma (ensures dec_e_numbering (enc_e_numbering #num #flt x) == Ok x) = ()
let rt_e_heading_depth (#num #flt: eqtype) (x: e_heading_depth) : Lemma (ensures dec_e_heading_depth (enc_e_heading_depth #num #flt x) == Ok x) = ()
let rt_e_list_style (#num #flt: eqtype) (x: e_list_style) : Lemma (ensures dec_e_list_style (enc_e_list_style #num #flt x) == Ok x) = ()

(* ======================================================================================
   2. THE PRESENCE LOOKUPS. One member's key read off the encoded object, with every
      conditional member other than that one left FREE — so a constructor with k of them
      costs 2k + r' lemmas rather than 2^k, and no query has to hold more than one key's
      walk. Each carries its own scoped fuel: `find_field` pushes through a key it is not
      looking for, and the default two unfoldings do not reach past the second. Emitted
      only for a constructor at or above the split threshold, and only from its first
      conditional member on — everything before that is reached without a branch.
   ====================================================================================== *)

(* ======================================================================================
   3. THE ROUND TRIP. One mutual induction over the whole family, recursing on the MODEL
      value — F*'s subterm order spans a mutual inductive family, so each case needs only
      the sub-lemmas of the members it carries. ONE LEMMA PER CONSTRUCTOR: a wide one is
      proved by citing section 2's lookups, a member at a time, rather than by carrying
      its object shapes into this query.
   ====================================================================================== *)

let rec rt_node (#num #flt: eqtype) (x: node num flt) : Lemma (ensures dec_node (enc_node #num #flt x) == Ok x) (decreases %[x; 2]) =
  match x with
  | C__node__Node i k -> rt_vkind #num #flt k

and rt_vkind (#num #flt: eqtype) (x: vkind num flt) : Lemma (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 2]) =
  match x with
  | C__vkind__Document _ _ _ _ -> rt_vkind__Document #num #flt x
  | C__vkind__Section _ _ _ -> rt_vkind__Section #num #flt x
  | C__vkind__Paragraph _ -> rt_vkind__Paragraph #num #flt x
  | C__vkind__ListBlock _ _ -> rt_vkind__ListBlock #num #flt x
  | C__vkind__ListItem _ -> rt_vkind__ListItem #num #flt x
  | C__vkind__Table _ _ -> rt_vkind__Table #num #flt x
  | C__vkind__Row _ _ -> rt_vkind__Row #num #flt x
  | C__vkind__Cell _ -> rt_vkind__Cell #num #flt x
  | C__vkind__Figure _ _ -> rt_vkind__Figure #num #flt x
  | C__vkind__Caption _ -> rt_vkind__Caption #num #flt x
  | C__vkind__Footnote _ -> rt_vkind__Footnote #num #flt x

and rt_vkind__Document (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__Document? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__Document f0 f1 f2 f3 -> rt_items_l_node #num #flt [] f0; rt_e_locale #num #flt f1; rt_e_numbering #num #flt f2

and rt_vkind__Section (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__Section? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__Section f0 f1 f2 -> rt_items_l_node #num #flt [] f0; rt_e_heading_depth #num #flt f1; rt_items_l_u_run #num #flt [] f2

and rt_vkind__Paragraph (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__Paragraph? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__Paragraph f0 -> rt_items_l_u_run #num #flt [] f0

and rt_vkind__ListBlock (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__ListBlock? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__ListBlock f0 f1 -> rt_items_l_node #num #flt [] f0; rt_e_list_style #num #flt f1

and rt_vkind__ListItem (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__ListItem? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__ListItem f0 -> rt_items_l_node #num #flt [] f0

and rt_vkind__Table (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__Table? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__Table f0 f1 -> (match f0 with | None -> () | Some w -> rt_items_l_u_run #num #flt [] w); rt_items_l_node #num #flt [] f1

and rt_vkind__Row (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__Row? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__Row f0 f1 -> rt_items_l_node #num #flt [] f0

and rt_vkind__Cell (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__Cell? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__Cell f0 -> rt_items_l_u_run #num #flt [] f0

and rt_vkind__Figure (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__Figure? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__Figure f0 f1 -> rt_items_l_node #num #flt [] f0

and rt_vkind__Caption (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__Caption? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__Caption f0 -> rt_items_l_u_run #num #flt [] f0

and rt_vkind__Footnote (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__Footnote? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__Footnote f0 -> rt_items_l_node #num #flt [] f0

and rt_u_run (#num #flt: eqtype) (x: u_run num flt) : Lemma (ensures dec_u_run (enc_u_run #num #flt x) == Ok x) (decreases %[x; 2]) =
  match x with
  | C__u_run__Text _ -> rt_u_run__Text #num #flt x
  | C__u_run__Emphasis _ -> rt_u_run__Emphasis #num #flt x
  | C__u_run__Strong _ -> rt_u_run__Strong #num #flt x
  | C__u_run__InlineRef _ -> rt_u_run__InlineRef #num #flt x
  | C__u_run__InlineVariable _ -> rt_u_run__InlineVariable #num #flt x
  | C__u_run__Link _ _ -> rt_u_run__Link #num #flt x
  | C__u_run__Code _ -> rt_u_run__Code #num #flt x

and rt_u_run__Text (#num #flt: eqtype) (x: u_run num flt) : Lemma (requires (C__u_run__Text? x)) (ensures dec_u_run (enc_u_run #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__u_run__Text f0 -> ()

and rt_u_run__Emphasis (#num #flt: eqtype) (x: u_run num flt) : Lemma (requires (C__u_run__Emphasis? x)) (ensures dec_u_run (enc_u_run #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__u_run__Emphasis f0 -> rt_items_l_u_run #num #flt [] f0

and rt_u_run__Strong (#num #flt: eqtype) (x: u_run num flt) : Lemma (requires (C__u_run__Strong? x)) (ensures dec_u_run (enc_u_run #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__u_run__Strong f0 -> rt_items_l_u_run #num #flt [] f0

and rt_u_run__InlineRef (#num #flt: eqtype) (x: u_run num flt) : Lemma (requires (C__u_run__InlineRef? x)) (ensures dec_u_run (enc_u_run #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__u_run__InlineRef f0 -> ()

and rt_u_run__InlineVariable (#num #flt: eqtype) (x: u_run num flt) : Lemma (requires (C__u_run__InlineVariable? x)) (ensures dec_u_run (enc_u_run #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__u_run__InlineVariable f0 -> ()

and rt_u_run__Link (#num #flt: eqtype) (x: u_run num flt) : Lemma (requires (C__u_run__Link? x)) (ensures dec_u_run (enc_u_run #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__u_run__Link f0 f1 -> ()

and rt_u_run__Code (#num #flt: eqtype) (x: u_run num flt) : Lemma (requires (C__u_run__Code? x)) (ensures dec_u_run (enc_u_run #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__u_run__Code f0 -> ()

and rt_items_l_node (#num #flt: eqtype) (acc: list (node num flt)) (xs: list (node num flt)) : Lemma (ensures dec_items_l_node acc (enc_items_l_node #num #flt xs) == Ok (rev_app acc xs)) (decreases %[xs; 2]) =
  match xs with
  | [] -> ()
  | y :: t -> rt_node #num #flt y; rt_items_l_node #num #flt (y :: acc) t

and rt_items_l_u_run (#num #flt: eqtype) (acc: list (u_run num flt)) (xs: list (u_run num flt)) : Lemma (ensures dec_items_l_u_run acc (enc_items_l_u_run #num #flt xs) == Ok (rev_app acc xs)) (decreases %[xs; 2]) =
  match xs with
  | [] -> ()
  | y :: t -> rt_u_run #num #flt y; rt_items_l_u_run #num #flt (y :: acc) t

(* ======================================================================================
   4. TOTALITY. That the decoders type-check at `Tot` is the termination proof; what the
      lemma adds is that the outcome is exactly one of the two, for EVERY input — the
      failure classification is exhaustive rather than merely non-empty.
   ====================================================================================== *)

let dec_node_total (#num #flt: eqtype) (el: jval num flt)
  : Lemma (ensures (Ok? (dec_node el) \/ Error? (dec_node el)) /\
                   ~(Ok? (dec_node el) /\ Error? (dec_node el)))
  = ()

