(*
   DocVocabulary — GENERATED by Fuaran.Core.Idl.Codegen's F* target from
   the vendored SECOND-DOMAIN sample — `tests/Fuaran.Core.Tests/SecondDomainSpike.fs`,
   a document vocabulary with a corpus written outside this repository, on the
   declared non-default wire shape the reference vocabulary does not use
   (fuaran-core Phase 173, applying D14 to `proofs/`).
   DO NOT EDIT: `dotnet run --project tests/Fuaran.Core.Tests -- --emit-fstar` regenerates
   it, and the `Proofs.Vocabulary` family holds this file to a fresh generation from that
   source — a vocabulary that moves without a regeneration is VOCABULARY DRIFT, and
   `proofs/check.ps1` names it.

   WHAT THIS IS. The vocabulary's types, its discriminated encoder and its tag-dispatch
   decoder, over Phase 135's `jval` value model and the `Decode` combinators modelled
   beside it (`WireDecode.fst`). The theorems over it are in `DocVocabularyProofs.fst`, which
   the same generator emits from the same walk — so a kind added to the IDL re-proves
   itself at the next `check.ps1` rather than waiting for a hand-written clause.

   WHAT THIS IS NOT. It is not any host's decoder and no host's build generates it. A
   host keeps its own hand-written, tuned decoder and is certified against its corpus;
   what is proved here is a property of the
   F* BACKEND (`Fuaran.Core.Idl.Codegen`'s `FStarTarget`) over the vocabulary the engine
   is certified on — the same set the F# and TypeScript backends are certified over — and
   not of any domain's vocabulary. A domain proves its own vocabulary in its own
   repository with the same generator; the UI vocabulary's model is `fuaran#1754`'s.

   THE MODEL'S BOUNDARY, stated rather than implied.

     - The numeric carriers are OPAQUE (`num` / `flt`), as they are in `WireDecode`: no
       definition here looks inside a number, it only moves one. A float member therefore
       decodes from `JFloat` alone — the widening `as_float` performs through a supplied
       `to_flt` has nothing to widen when the carriers are parameters, and the encoder
       never emits an integer at a float slot.
     - A HOST-ONLY member has no wire projection and is absent from the model. The model
       is of the wire; a member that is never on the wire is not part of it.
     - A `TMap` is an ASSOCIATION LIST in the authored order. A map has no declared key
       order, and an assoc list is what the wire object is before a renderer sorts it.
     - A `TJson` member, and a host-codec member whose wire is JSON, is carried VERBATIM
       as a `jval`. What such a member holds is the host codec's business, not the
       schema's, and inventing an F* counterpart for a host type would model a fiction.
     - Generic unions are MONOMORPHISED at the arguments this vocabulary reaches, which
       is what keeps every definition and every emitted lemma first-order.

   VOCABULARY. Discriminator "kind", flat-kind envelope, declaration key order.
   11 of 11 kinds are modelled; 2 declared types and 4 enums are reached.
   Every kind the vocabulary declares is modelled.

   THE COST OPTION IS PART OF THE ARTEFACT. `--ext context_pruning` is set below rather
   than passed by the leg: this module opens the whole decode model and declares dozens
   of types, so every query would otherwise carry the entire context. Measured on the
   pinned prover it is the difference between a module the leg can afford and one it
   cannot — the same finding `TreeOps`, `JsonParse`, `Preservation` and `TreeDiff` each
   record in `modules.json`. If this module's budget is ever bumped, check the option is
   still here before reading the growth as ordinary.

   Apache-2.0, like everything beside it.
*)
module DocVocabulary

open WireDecode

#set-options "--ext context_pruning"

(* ======================================================================================
   1. The closed string sets (`TEnum`) — a bare wire string, not an object.
   ====================================================================================== *)

type e_locale =
  | C__e_locale__EnGB
  | C__e_locale__EnUS

let enc_e_locale (#num #flt: eqtype) (x: e_locale) : Tot (jval num flt) =
  match x with
  | C__e_locale__EnGB -> JStr "EnGB"
  | C__e_locale__EnUS -> JStr "EnUS"

let dec_e_locale (#num #flt: eqtype) (el: jval num flt) : Tot (outcome e_locale) =
  match as_string el with
  | Error e -> Error e
  | Ok s ->
    if s = "EnGB" then Ok C__e_locale__EnGB else
    if s = "EnUS" then Ok C__e_locale__EnUS else
    Error ("unknown Locale: " ^ s)

type e_numbering =
  | C__e_numbering__NoNumbering
  | C__e_numbering__DecimalNumbering
  | C__e_numbering__LegalNumbering

let enc_e_numbering (#num #flt: eqtype) (x: e_numbering) : Tot (jval num flt) =
  match x with
  | C__e_numbering__NoNumbering -> JStr "NoNumbering"
  | C__e_numbering__DecimalNumbering -> JStr "DecimalNumbering"
  | C__e_numbering__LegalNumbering -> JStr "LegalNumbering"

let dec_e_numbering (#num #flt: eqtype) (el: jval num flt) : Tot (outcome e_numbering) =
  match as_string el with
  | Error e -> Error e
  | Ok s ->
    if s = "NoNumbering" then Ok C__e_numbering__NoNumbering else
    if s = "DecimalNumbering" then Ok C__e_numbering__DecimalNumbering else
    if s = "LegalNumbering" then Ok C__e_numbering__LegalNumbering else
    Error ("unknown Numbering: " ^ s)

type e_heading_depth =
  | C__e_heading_depth__H1
  | C__e_heading_depth__H2
  | C__e_heading_depth__H3
  | C__e_heading_depth__H4
  | C__e_heading_depth__H5
  | C__e_heading_depth__H6

let enc_e_heading_depth (#num #flt: eqtype) (x: e_heading_depth) : Tot (jval num flt) =
  match x with
  | C__e_heading_depth__H1 -> JStr "H1"
  | C__e_heading_depth__H2 -> JStr "H2"
  | C__e_heading_depth__H3 -> JStr "H3"
  | C__e_heading_depth__H4 -> JStr "H4"
  | C__e_heading_depth__H5 -> JStr "H5"
  | C__e_heading_depth__H6 -> JStr "H6"

let dec_e_heading_depth (#num #flt: eqtype) (el: jval num flt) : Tot (outcome e_heading_depth) =
  match as_string el with
  | Error e -> Error e
  | Ok s ->
    if s = "H1" then Ok C__e_heading_depth__H1 else
    if s = "H2" then Ok C__e_heading_depth__H2 else
    if s = "H3" then Ok C__e_heading_depth__H3 else
    if s = "H4" then Ok C__e_heading_depth__H4 else
    if s = "H5" then Ok C__e_heading_depth__H5 else
    if s = "H6" then Ok C__e_heading_depth__H6 else
    Error ("unknown HeadingDepth: " ^ s)

type e_list_style =
  | C__e_list_style__Bulleted
  | C__e_list_style__Numbered
  | C__e_list_style__Lettered
  | C__e_list_style__Roman

let enc_e_list_style (#num #flt: eqtype) (x: e_list_style) : Tot (jval num flt) =
  match x with
  | C__e_list_style__Bulleted -> JStr "Bulleted"
  | C__e_list_style__Numbered -> JStr "Numbered"
  | C__e_list_style__Lettered -> JStr "Lettered"
  | C__e_list_style__Roman -> JStr "Roman"

let dec_e_list_style (#num #flt: eqtype) (el: jval num flt) : Tot (outcome e_list_style) =
  match as_string el with
  | Error e -> Error e
  | Ok s ->
    if s = "Bulleted" then Ok C__e_list_style__Bulleted else
    if s = "Numbered" then Ok C__e_list_style__Numbered else
    if s = "Lettered" then Ok C__e_list_style__Lettered else
    if s = "Roman" then Ok C__e_list_style__Roman else
    Error ("unknown ListStyle: " ^ s)

(* ======================================================================================
   2. The vocabulary's types — one mutual group, because a record may hold a union, a
      union a node, and a node a list of nodes. Records are single-constructor types
      rather than F* records so that two objects declaring a `label` cannot collide.
   ====================================================================================== *)

type node (num flt: eqtype) =
  | C__node__Node : id:string -> k:(vkind num flt) -> node num flt

and vkind (num flt: eqtype) =
  | C__vkind__Document : children:(list (node num flt)) -> locale:(e_locale) -> numbering:(e_numbering) -> title:(option (string)) -> vkind num flt
  | C__vkind__Section : children:(list (node num flt)) -> depth:(e_heading_depth) -> heading:(list (u_run num flt)) -> vkind num flt
  | C__vkind__Paragraph : runs:(list (u_run num flt)) -> vkind num flt
  | C__vkind__ListBlock : children:(list (node num flt)) -> style:(e_list_style) -> vkind num flt
  | C__vkind__ListItem : children:(list (node num flt)) -> vkind num flt
  | C__vkind__Table : caption:(option (list (u_run num flt))) -> children:(list (node num flt)) -> vkind num flt
  | C__vkind__Row : children:(list (node num flt)) -> is_header:(bool) -> vkind num flt
  | C__vkind__Cell : runs:(list (u_run num flt)) -> vkind num flt
  | C__vkind__Figure : children:(list (node num flt)) -> source:(string) -> vkind num flt
  | C__vkind__Caption : runs:(list (u_run num flt)) -> vkind num flt
  | C__vkind__Footnote : children:(list (node num flt)) -> vkind num flt

and u_run (num flt: eqtype) =
  | C__u_run__Text : value:(string) -> u_run num flt
  | C__u_run__Emphasis : runs:(list (u_run num flt)) -> u_run num flt
  | C__u_run__Strong : runs:(list (u_run num flt)) -> u_run num flt
  | C__u_run__InlineRef : target:(string) -> u_run num flt
  | C__u_run__InlineVariable : field:(string) -> u_run num flt
  | C__u_run__Link : text:(string) -> url:(string) -> u_run num flt
  | C__u_run__Code : value:(string) -> u_run num flt

(* ======================================================================================
   3. The encoder — the discriminated envelope, keys in the vocabulary's canonical
      order. The model has no render step, so the object LITERAL is the canonical form.
      Recursion is on the MODEL value, where F*'s subterm order spans the whole family.
   ====================================================================================== *)

let rec enc_node (#num #flt: eqtype) (x: node num flt) : Tot (jval num flt) (decreases x) =
  match x with
  | C__node__Node i k  ->
    JObj (("id", JStr i) :: ("kind", enc_vkind k) :: [])

and enc_vkind (#num #flt: eqtype) (x: vkind num flt) : Tot (jval num flt) (decreases x) =
  match x with
  | C__vkind__Document f0 f1 f2 f3 ->
    JObj (("kind", JStr "Document") :: ("children", JArr (enc_items_l_node f0)) :: ("locale", enc_e_locale f1) :: ("numbering", enc_e_numbering f2) :: (match f3 with | None -> [] | Some w -> ("title", JStr w) :: []))
  | C__vkind__Section f0 f1 f2 ->
    JObj (("kind", JStr "Section") :: ("children", JArr (enc_items_l_node f0)) :: ("depth", enc_e_heading_depth f1) :: ("heading", JArr (enc_items_l_u_run f2)) :: [])
  | C__vkind__Paragraph f0 ->
    JObj (("kind", JStr "Paragraph") :: ("runs", JArr (enc_items_l_u_run f0)) :: [])
  | C__vkind__ListBlock f0 f1 ->
    JObj (("kind", JStr "ListBlock") :: ("children", JArr (enc_items_l_node f0)) :: ("style", enc_e_list_style f1) :: [])
  | C__vkind__ListItem f0 ->
    JObj (("kind", JStr "ListItem") :: ("children", JArr (enc_items_l_node f0)) :: [])
  | C__vkind__Table f0 f1 ->
    JObj (("kind", JStr "Table") :: (match f0 with | None -> ("children", JArr (enc_items_l_node f1)) :: [] | Some w -> ("caption", JArr (enc_items_l_u_run w)) :: ("children", JArr (enc_items_l_node f1)) :: []))
  | C__vkind__Row f0 f1 ->
    JObj (("kind", JStr "Row") :: ("children", JArr (enc_items_l_node f0)) :: ("isHeader", JBool f1) :: [])
  | C__vkind__Cell f0 ->
    JObj (("kind", JStr "Cell") :: ("runs", JArr (enc_items_l_u_run f0)) :: [])
  | C__vkind__Figure f0 f1 ->
    JObj (("kind", JStr "Figure") :: ("children", JArr (enc_items_l_node f0)) :: ("source", JStr f1) :: [])
  | C__vkind__Caption f0 ->
    JObj (("kind", JStr "Caption") :: ("runs", JArr (enc_items_l_u_run f0)) :: [])
  | C__vkind__Footnote f0 ->
    JObj (("kind", JStr "Footnote") :: ("children", JArr (enc_items_l_node f0)) :: [])

and enc_u_run (#num #flt: eqtype) (x: u_run num flt) : Tot (jval num flt) (decreases x) =
  match x with
  | C__u_run__Text f0 ->
    JObj (("kind", JStr "Text") :: ("value", JStr f0) :: [])
  | C__u_run__Emphasis f0 ->
    JObj (("kind", JStr "Emphasis") :: ("runs", JArr (enc_items_l_u_run f0)) :: [])
  | C__u_run__Strong f0 ->
    JObj (("kind", JStr "Strong") :: ("runs", JArr (enc_items_l_u_run f0)) :: [])
  | C__u_run__InlineRef f0 ->
    JObj (("kind", JStr "InlineRef") :: ("target", JStr f0) :: [])
  | C__u_run__InlineVariable f0 ->
    JObj (("kind", JStr "InlineVariable") :: ("field", JStr f0) :: [])
  | C__u_run__Link f0 f1 ->
    JObj (("kind", JStr "Link") :: ("text", JStr f0) :: ("url", JStr f1) :: [])
  | C__u_run__Code f0 ->
    JObj (("kind", JStr "Code") :: ("value", JStr f0) :: [])

and enc_items_l_node (#num #flt: eqtype) (xs: list (node num flt)) : Tot (list (jval num flt)) (decreases xs) =
  match xs with
  | [] -> []
  | y :: t -> enc_node y :: enc_items_l_node t

and enc_items_l_u_run (#num #flt: eqtype) (xs: list (u_run num flt)) : Tot (list (jval num flt)) (decreases xs) =
  match xs with
  | [] -> []
  | y :: t -> enc_u_run y :: enc_items_l_u_run t

(* ======================================================================================
   4. The tag-dispatch decoder. Every cross-type call goes through `get_prop`, whose
      RETURN-TYPE refinement (`jsize (Ok?.v r) < jsize el`) is the termination argument:
      a decoder that descends by NAME into a value it looked up has no syntactic one.
      Value decoders sit at tier 0 on `jsize`, walkers at tier 1 on `jsizes` / `fsize`.
   ====================================================================================== *)

let rec dec_node (#num #flt: eqtype) (el: jval num flt) : Tot (outcome (node num flt)) (decreases %[(jsize el <: nat); 0]) =
  let oid : outcome string = str_field "id" el in
  let ok : outcome (vkind num flt) = (match get_prop "kind" el with | Error e -> Error e | Ok v -> dec_vkind v) in
  (match oid with | Error e -> Error e | Ok i -> (match ok with | Error e -> Error e | Ok k -> Ok (C__node__Node i k )))

and dec_vkind (#num #flt: eqtype) (el: jval num flt) : Tot (outcome (vkind num flt)) (decreases %[(jsize el <: nat); 0]) =
  match str_field "kind" el with
  | Error e -> Error e
  | Ok tag ->
    if tag = "Document" then
      let o0 : outcome (list (node num flt)) = (match get_prop "children" el with | Error e -> Error e | Ok v -> (match v with | JArr ys -> (match dec_items_l_node [] ys with | Error e -> Error e | Ok w -> Ok w) | other -> Error ("expected array, got " ^ kind_name other))) in
      let o1 : outcome (e_locale) = (match get_prop "locale" el with | Error e -> Error e | Ok v -> (match dec_e_locale v with | Error e -> Error e | Ok w -> Ok w)) in
      let o2 : outcome (e_numbering) = (match get_prop "numbering" el with | Error e -> Error e | Ok v -> (match dec_e_numbering v with | Error e -> Error e | Ok w -> Ok w)) in
      let o3 : outcome (option (string)) = (match get_prop "title" el with | Error _ -> Ok None | Ok v -> (match as_string v with | Error e -> Error e | Ok w -> Ok (Some w))) in
      (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> (match o2 with | Error e -> Error e | Ok f2 -> (match o3 with | Error e -> Error e | Ok f3 -> Ok (C__vkind__Document f0 f1 f2 f3)))))
    else
    if tag = "Section" then
      let o0 : outcome (list (node num flt)) = (match get_prop "children" el with | Error e -> Error e | Ok v -> (match v with | JArr ys -> (match dec_items_l_node [] ys with | Error e -> Error e | Ok w -> Ok w) | other -> Error ("expected array, got " ^ kind_name other))) in
      let o1 : outcome (e_heading_depth) = (match get_prop "depth" el with | Error e -> Error e | Ok v -> (match dec_e_heading_depth v with | Error e -> Error e | Ok w -> Ok w)) in
      let o2 : outcome (list (u_run num flt)) = (match get_prop "heading" el with | Error e -> Error e | Ok v -> (match v with | JArr ys -> (match dec_items_l_u_run [] ys with | Error e -> Error e | Ok w -> Ok w) | other -> Error ("expected array, got " ^ kind_name other))) in
      (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> (match o2 with | Error e -> Error e | Ok f2 -> Ok (C__vkind__Section f0 f1 f2))))
    else
    if tag = "Paragraph" then
      let o0 : outcome (list (u_run num flt)) = (match get_prop "runs" el with | Error e -> Error e | Ok v -> (match v with | JArr ys -> (match dec_items_l_u_run [] ys with | Error e -> Error e | Ok w -> Ok w) | other -> Error ("expected array, got " ^ kind_name other))) in
      (match o0 with | Error e -> Error e | Ok f0 -> Ok (C__vkind__Paragraph f0))
    else
    if tag = "ListBlock" then
      let o0 : outcome (list (node num flt)) = (match get_prop "children" el with | Error e -> Error e | Ok v -> (match v with | JArr ys -> (match dec_items_l_node [] ys with | Error e -> Error e | Ok w -> Ok w) | other -> Error ("expected array, got " ^ kind_name other))) in
      let o1 : outcome (e_list_style) = (match get_prop "style" el with | Error e -> Error e | Ok v -> (match dec_e_list_style v with | Error e -> Error e | Ok w -> Ok w)) in
      (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> Ok (C__vkind__ListBlock f0 f1)))
    else
    if tag = "ListItem" then
      let o0 : outcome (list (node num flt)) = (match get_prop "children" el with | Error e -> Error e | Ok v -> (match v with | JArr ys -> (match dec_items_l_node [] ys with | Error e -> Error e | Ok w -> Ok w) | other -> Error ("expected array, got " ^ kind_name other))) in
      (match o0 with | Error e -> Error e | Ok f0 -> Ok (C__vkind__ListItem f0))
    else
    if tag = "Table" then
      let o0 : outcome (option (list (u_run num flt))) = (match get_prop "caption" el with | Error _ -> Ok None | Ok v -> (match v with | JArr ys -> (match dec_items_l_u_run [] ys with | Error e -> Error e | Ok w -> Ok (Some w)) | other -> Error ("expected array, got " ^ kind_name other))) in
      let o1 : outcome (list (node num flt)) = (match get_prop "children" el with | Error e -> Error e | Ok v -> (match v with | JArr ys -> (match dec_items_l_node [] ys with | Error e -> Error e | Ok w -> Ok w) | other -> Error ("expected array, got " ^ kind_name other))) in
      (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> Ok (C__vkind__Table f0 f1)))
    else
    if tag = "Row" then
      let o0 : outcome (list (node num flt)) = (match get_prop "children" el with | Error e -> Error e | Ok v -> (match v with | JArr ys -> (match dec_items_l_node [] ys with | Error e -> Error e | Ok w -> Ok w) | other -> Error ("expected array, got " ^ kind_name other))) in
      let o1 : outcome (bool) = (match get_prop "isHeader" el with | Error e -> Error e | Ok v -> (match as_bool v with | Error e -> Error e | Ok w -> Ok w)) in
      (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> Ok (C__vkind__Row f0 f1)))
    else
    if tag = "Cell" then
      let o0 : outcome (list (u_run num flt)) = (match get_prop "runs" el with | Error e -> Error e | Ok v -> (match v with | JArr ys -> (match dec_items_l_u_run [] ys with | Error e -> Error e | Ok w -> Ok w) | other -> Error ("expected array, got " ^ kind_name other))) in
      (match o0 with | Error e -> Error e | Ok f0 -> Ok (C__vkind__Cell f0))
    else
    if tag = "Figure" then
      let o0 : outcome (list (node num flt)) = (match get_prop "children" el with | Error e -> Error e | Ok v -> (match v with | JArr ys -> (match dec_items_l_node [] ys with | Error e -> Error e | Ok w -> Ok w) | other -> Error ("expected array, got " ^ kind_name other))) in
      let o1 : outcome (string) = (match get_prop "source" el with | Error e -> Error e | Ok v -> (match as_string v with | Error e -> Error e | Ok w -> Ok w)) in
      (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> Ok (C__vkind__Figure f0 f1)))
    else
    if tag = "Caption" then
      let o0 : outcome (list (u_run num flt)) = (match get_prop "runs" el with | Error e -> Error e | Ok v -> (match v with | JArr ys -> (match dec_items_l_u_run [] ys with | Error e -> Error e | Ok w -> Ok w) | other -> Error ("expected array, got " ^ kind_name other))) in
      (match o0 with | Error e -> Error e | Ok f0 -> Ok (C__vkind__Caption f0))
    else
    if tag = "Footnote" then
      let o0 : outcome (list (node num flt)) = (match get_prop "children" el with | Error e -> Error e | Ok v -> (match v with | JArr ys -> (match dec_items_l_node [] ys with | Error e -> Error e | Ok w -> Ok w) | other -> Error ("expected array, got " ^ kind_name other))) in
      (match o0 with | Error e -> Error e | Ok f0 -> Ok (C__vkind__Footnote f0))
    else
    Error ("unknown kind: " ^ tag)

and dec_u_run (#num #flt: eqtype) (el: jval num flt) : Tot (outcome (u_run num flt)) (decreases %[(jsize el <: nat); 0]) =
  match str_field "kind" el with
  | Error e -> Error e
  | Ok tag ->
    if tag = "Text" then
      let o0 : outcome (string) = (match get_prop "value" el with | Error e -> Error e | Ok v -> (match as_string v with | Error e -> Error e | Ok w -> Ok w)) in
      (match o0 with | Error e -> Error e | Ok f0 -> Ok (C__u_run__Text f0))
    else
    if tag = "Emphasis" then
      let o0 : outcome (list (u_run num flt)) = (match get_prop "runs" el with | Error e -> Error e | Ok v -> (match v with | JArr ys -> (match dec_items_l_u_run [] ys with | Error e -> Error e | Ok w -> Ok w) | other -> Error ("expected array, got " ^ kind_name other))) in
      (match o0 with | Error e -> Error e | Ok f0 -> Ok (C__u_run__Emphasis f0))
    else
    if tag = "Strong" then
      let o0 : outcome (list (u_run num flt)) = (match get_prop "runs" el with | Error e -> Error e | Ok v -> (match v with | JArr ys -> (match dec_items_l_u_run [] ys with | Error e -> Error e | Ok w -> Ok w) | other -> Error ("expected array, got " ^ kind_name other))) in
      (match o0 with | Error e -> Error e | Ok f0 -> Ok (C__u_run__Strong f0))
    else
    if tag = "InlineRef" then
      let o0 : outcome (string) = (match get_prop "target" el with | Error e -> Error e | Ok v -> (match as_string v with | Error e -> Error e | Ok w -> Ok w)) in
      (match o0 with | Error e -> Error e | Ok f0 -> Ok (C__u_run__InlineRef f0))
    else
    if tag = "InlineVariable" then
      let o0 : outcome (string) = (match get_prop "field" el with | Error e -> Error e | Ok v -> (match as_string v with | Error e -> Error e | Ok w -> Ok w)) in
      (match o0 with | Error e -> Error e | Ok f0 -> Ok (C__u_run__InlineVariable f0))
    else
    if tag = "Link" then
      let o0 : outcome (string) = (match get_prop "text" el with | Error e -> Error e | Ok v -> (match as_string v with | Error e -> Error e | Ok w -> Ok w)) in
      let o1 : outcome (string) = (match get_prop "url" el with | Error e -> Error e | Ok v -> (match as_string v with | Error e -> Error e | Ok w -> Ok w)) in
      (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> Ok (C__u_run__Link f0 f1)))
    else
    if tag = "Code" then
      let o0 : outcome (string) = (match get_prop "value" el with | Error e -> Error e | Ok v -> (match as_string v with | Error e -> Error e | Ok w -> Ok w)) in
      (match o0 with | Error e -> Error e | Ok f0 -> Ok (C__u_run__Code f0))
    else
    Error ("unknown u_run case: " ^ tag)

and dec_items_l_node (#num #flt: eqtype) (acc: list (node num flt)) (ys: list (jval num flt)) : Tot (outcome (list (node num flt))) (decreases %[(jsizes ys <: nat); 1]) =
  match ys with
  | [] -> Ok (rev acc)
  | y :: rest ->
    (match dec_node y with
     | Ok w -> dec_items_l_node (w :: acc) rest
     | Error e -> Error e)

and dec_items_l_u_run (#num #flt: eqtype) (acc: list (u_run num flt)) (ys: list (jval num flt)) : Tot (outcome (list (u_run num flt))) (decreases %[(jsizes ys <: nat); 1]) =
  match ys with
  | [] -> Ok (rev acc)
  | y :: rest ->
    (match dec_u_run y with
     | Ok w -> dec_items_l_u_run (w :: acc) rest
     | Error e -> Error e)

