(*
   ScoreVocabularyProofs — GENERATED by Fuaran.Core.Idl.Codegen's F* target, from the same walk that
   emits `ScoreVocabulary.fst`, over
   the vendored THIRD-DOMAIN sample — `tests/Fuaran.Core.Tests/ScoreDomainSpike.fs`,
   a notation vocabulary with a corpus written outside this repository: records and
   omit-at-default at scale, on the same declared non-default wire shape
   (fuaran-core Phase 173, applying D14 to `proofs/`).
   DO NOT EDIT: `dotnet run --project tests/Fuaran.Core.Tests -- --emit-fstar` regenerates
   it, and the `Proofs.Vocabulary` family holds this file to a fresh generation from that
   source — a vocabulary that moves without a regeneration is VOCABULARY DRIFT, and
   `proofs/check.ps1` names it.

   WHAT IS PROVED, and why it is GENERATED rather than written.

   Phase 135 proved `decode (encode n) == Ok n` for a hand-written four-case REFERENCE
   vocabulary, and was explicit about the boundary: a theorem about a reference vocabulary
   is not a theorem about the one a host actually decodes. The real vocabulary has dozens
   of kinds — 19 of this one's 21 are modelled — and it grows. A HAND-WRITTEN proof over
   it would be a theorem about the vocabulary as it stood on the day it was written, which
   is the same defect one release later. So the proof script is emitted by the walk that
   emits the model: a kind added to the IDL re-proves itself at the next `check.ps1`, and a
   kind whose encoder and decoder disagree fails it.

     - `rt_node` and the family beside it — THE ROUND TRIP. For every value of every
       modelled type, decoding its encoding returns that value: `dec_node (enc_node x) ==
       Ok x`, at every depth, through every list, map, optional member and omit-default.
     - `dec_node_total` — TOTALITY, and the exclusivity of the outcome. That the decoders
       type-check at `Tot` is the termination proof; the lemma states that every input
       reaches exactly one of `Ok` / `Error` and never both.

   THE SHAPE — one lemma per constructor, and the presence split LINEAR in the conditional
   members (fuaran-core Phase 182, replacing Phase 168's per-pattern split).
   A constructor with k conditional members (optional, or omitted at its default) encodes
   to 2^k object shapes, and a lemma over the whole constructor puts all of them in ONE
   query. Measured at a twenty-kind vocabulary whose node envelope carried five optional
   members (Phase 150): the node lemma's 65-goal query failed a `--quake` seed at the leg's
   rlimit, the widest kind's arm failed outright, and raising the rlimit turned failing into
   grinding. `--split_queries` is not settable as a pragma on the pinned prover, so the
   isolation is in the emitted shape instead. `rt_<T>` is the round trip over a type — for a
   type with several constructors, a CASE SPLIT whose arms cite `rt_<T>__<Ctor>`, one
   constructor's arm alone under `C__<T>__<Ctor>? x`. A constructor with
   2 or more conditional members is proved from its members' LOOKUPS instead of in one
   query: `lk_<T>__<Ctor>__<member>` reads one key off the encoded object with every OTHER
   conditional member left free — one lemma for a member that is always emitted, two for a
   conditional one — and the constructor's lemma cites them a member at a time. That is
   2k + r' lemmas where Phase 168 emitted 2^k, and it is why a sixteen-conditional kind
   costs thirty-odd lemmas rather than 65,536 (`fuaran#1754` measured 71,722 of them in a
   114 MB script at the UI vocabulary). The family is still one mutual induction — a kind's
   children reach `rt_node` — on the lexicographic measure `%[x; tier]`; the lookups are
   NOT in it, since they recurse on nothing, which is what lets each carry the scoped
   `--fuel` its own walk needs. The rlimit precedent Phase 150 took (`--z3rlimit 200` in
   this file) stays retired: the leg's own rlimit is what these are checked under, and a
   query that wants more is a query the split has failed to isolate.

   WHAT IS NOT PROVED HERE, and why. The `wf` CHARACTERISATION — `Ok? (dec el) == wf el`,
   which Phase 135 carries for its hand-written reference vocabulary — is not restated over
   the generated vocabulary. The only predicate this emitter could generate from the same
   walk is the decoder's own accept set restated clause for clause, and `Ok? (dec el) ==
   (that predicate) el` is then a theorem about two renderings of one definition — true,
   and empty. A characterisation worth the name needs an INDEPENDENT statement of the
   accept set (a schema-shaped predicate), which is a model-sized artefact of its own;
   `proofs/README.md` (theorem 1) records the halt. The round trip covers one direction
   (everything the encoder can produce is read back exactly); the characterisation of what
   ELSE is accepted is not covered, and is named here rather than left to be assumed.

   ONE COST OPTION IS PART OF THE ARTEFACT: `--ext context_pruning` is set below for the
   reason the model module's header gives at greater length — a mutual induction over the
   whole family would otherwise carry the whole family in every query. If this module is
   ever slow enough to want investigating, check it is still in force first.

   Apache-2.0, like everything beside it.
*)
module ScoreVocabularyProofs

open WireDecode
open ScoreVocabulary

#set-options "--ext context_pruning"

(* ======================================================================================
   1. The closed string sets. Each is a finite match on distinct literals, so its round
      trip is definitional — stated anyway, because the family below calls it by name.
   ====================================================================================== *)

let rt_e_clef_kind (#num #flt: eqtype) (x: e_clef_kind) : Lemma (ensures dec_e_clef_kind (enc_e_clef_kind #num #flt x) == Ok x) = ()
let rt_e_note_letter (#num #flt: eqtype) (x: e_note_letter) : Lemma (ensures dec_e_note_letter (enc_e_note_letter #num #flt x) == Ok x) = ()
let rt_e_accidental (#num #flt: eqtype) (x: e_accidental) : Lemma (ensures dec_e_accidental (enc_e_accidental #num #flt x) == Ok x) = ()
let rt_e_mode (#num #flt: eqtype) (x: e_mode) : Lemma (ensures dec_e_mode (enc_e_mode #num #flt x) == Ok x) = ()
let rt_e_bracket_kind (#num #flt: eqtype) (x: e_bracket_kind) : Lemma (ensures dec_e_bracket_kind (enc_e_bracket_kind #num #flt x) == Ok x) = ()
let rt_e_grace_kind (#num #flt: eqtype) (x: e_grace_kind) : Lemma (ensures dec_e_grace_kind (enc_e_grace_kind #num #flt x) == Ok x) = ()
let rt_e_dynamic_level (#num #flt: eqtype) (x: e_dynamic_level) : Lemma (ensures dec_e_dynamic_level (enc_e_dynamic_level #num #flt x) == Ok x) = ()
let rt_e_hairpin_kind (#num #flt: eqtype) (x: e_hairpin_kind) : Lemma (ensures dec_e_hairpin_kind (enc_e_hairpin_kind #num #flt x) == Ok x) = ()
let rt_e_octave_shift_kind (#num #flt: eqtype) (x: e_octave_shift_kind) : Lemma (ensures dec_e_octave_shift_kind (enc_e_octave_shift_kind #num #flt x) == Ok x) = ()
let rt_e_ornament_name (#num #flt: eqtype) (x: e_ornament_name) : Lemma (ensures dec_e_ornament_name (enc_e_ornament_name #num #flt x) == Ok x) = ()
let rt_e_navigation_kind (#num #flt: eqtype) (x: e_navigation_kind) : Lemma (ensures dec_e_navigation_kind (enc_e_navigation_kind #num #flt x) == Ok x) = ()

(* ======================================================================================
   2. THE PRESENCE LOOKUPS. One member's key read off the encoded object, with every
      conditional member other than that one left FREE — so a constructor with k of them
      costs 2k + r' lemmas rather than 2^k, and no query has to hold more than one key's
      walk. Each carries its own scoped fuel: `find_field` pushes through a key it is not
      looking for, and the default two unfoldings do not reach past the second. Emitted
      only for a constructor at or above the split threshold, and only from its first
      conditional member on — everything before that is reached without a branch.
   ====================================================================================== *)

(* The suffixes of C__vkind__Score — each revealed once, here, and cited by name below. *)
let sk_vkind__Score__composer__skip (#num #flt: eqtype) (n: string) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Lemma (requires (n <> "composer")) (ensures (find_field n (sfx_vkind__Score__composer e rest) == find_field n rest))
  = reveal_opaque (`%sfx_vkind__Score__composer) (sfx_vkind__Score__composer #num #flt e rest)
let sk_vkind__Score__composer__hit (#num #flt: eqtype) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Lemma (requires (Some? e)) (ensures (find_field "composer" (sfx_vkind__Score__composer e rest) == Ok (Some?.v e)))
  = reveal_opaque (`%sfx_vkind__Score__composer) (sfx_vkind__Score__composer #num #flt e rest)
let sk_vkind__Score__composer__none (#num #flt: eqtype) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Lemma (requires (None? e)) (ensures (sfx_vkind__Score__composer e rest == rest))
  = reveal_opaque (`%sfx_vkind__Score__composer) (sfx_vkind__Score__composer #num #flt e rest)
let sk_vkind__Score__title__skip (#num #flt: eqtype) (n: string) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Lemma (requires (n <> "title")) (ensures (find_field n (sfx_vkind__Score__title e rest) == find_field n rest))
  = reveal_opaque (`%sfx_vkind__Score__title) (sfx_vkind__Score__title #num #flt e rest)
let sk_vkind__Score__title__hit (#num #flt: eqtype) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Lemma (requires (Some? e)) (ensures (find_field "title" (sfx_vkind__Score__title e rest) == Ok (Some?.v e)))
  = reveal_opaque (`%sfx_vkind__Score__title) (sfx_vkind__Score__title #num #flt e rest)
let sk_vkind__Score__title__none (#num #flt: eqtype) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Lemma (requires (None? e)) (ensures (sfx_vkind__Score__title e rest == rest))
  = reveal_opaque (`%sfx_vkind__Score__title) (sfx_vkind__Score__title #num #flt e rest)

(* lk_vkind__Score__composer__present — composer present *)
#push-options "--fuel 8 --ifuel 4"
let lk_vkind__Score__composer__present (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (match x with | C__vkind__Score f0 f1 f2 -> Some? f1 | _ -> false)) (ensures (match x with | C__vkind__Score f0 f1 f2 -> get_prop "composer" (enc_vkind #num #flt x) == Ok (JStr (Some?.v f1)) | _ -> True)) =
  match x with
  | C__vkind__Score f0 f1 f2 ->
    let s1 = sfx_vkind__Score__title #num #flt (enc_opt_str #num #flt f2) ([]) in
    let s0 = sfx_vkind__Score__composer #num #flt (enc_opt_str #num #flt f1) (s1) in
    sk_vkind__Score__composer__hit #num #flt (enc_opt_str #num #flt f1) (s1)
  | _ -> ()
#pop-options

(* lk_vkind__Score__composer__absent — composer absent *)
#push-options "--fuel 8 --ifuel 4"
let lk_vkind__Score__composer__absent (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (match x with | C__vkind__Score f0 f1 f2 -> None? f1 | _ -> false)) (ensures (Error? (get_prop "composer" (enc_vkind #num #flt x)))) =
  match x with
  | C__vkind__Score f0 f1 f2 ->
    let s1 = sfx_vkind__Score__title #num #flt (enc_opt_str #num #flt f2) ([]) in
    let s0 = sfx_vkind__Score__composer #num #flt (enc_opt_str #num #flt f1) (s1) in
    sk_vkind__Score__composer__none #num #flt (enc_opt_str #num #flt f1) (s1);
    sk_vkind__Score__title__skip #num #flt "composer" (enc_opt_str #num #flt f2) ([])
  | _ -> ()
#pop-options

(* lk_vkind__Score__title__present — title present *)
#push-options "--fuel 8 --ifuel 4"
let lk_vkind__Score__title__present (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (match x with | C__vkind__Score f0 f1 f2 -> Some? f2 | _ -> false)) (ensures (match x with | C__vkind__Score f0 f1 f2 -> get_prop "title" (enc_vkind #num #flt x) == Ok (JStr (Some?.v f2)) | _ -> True)) =
  match x with
  | C__vkind__Score f0 f1 f2 ->
    let s1 = sfx_vkind__Score__title #num #flt (enc_opt_str #num #flt f2) ([]) in
    let s0 = sfx_vkind__Score__composer #num #flt (enc_opt_str #num #flt f1) (s1) in
    sk_vkind__Score__composer__skip #num #flt "title" (enc_opt_str #num #flt f1) (s1);
    sk_vkind__Score__title__hit #num #flt (enc_opt_str #num #flt f2) ([])
  | _ -> ()
#pop-options

(* lk_vkind__Score__title__absent — title absent *)
#push-options "--fuel 8 --ifuel 4"
let lk_vkind__Score__title__absent (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (match x with | C__vkind__Score f0 f1 f2 -> None? f2 | _ -> false)) (ensures (Error? (get_prop "title" (enc_vkind #num #flt x)))) =
  match x with
  | C__vkind__Score f0 f1 f2 ->
    let s1 = sfx_vkind__Score__title #num #flt (enc_opt_str #num #flt f2) ([]) in
    let s0 = sfx_vkind__Score__composer #num #flt (enc_opt_str #num #flt f1) (s1) in
    sk_vkind__Score__composer__skip #num #flt "title" (enc_opt_str #num #flt f1) (s1);
    sk_vkind__Score__title__none #num #flt (enc_opt_str #num #flt f2) ([])
  | _ -> ()
#pop-options

(* The suffixes of C__vkind__Measure — each revealed once, here, and cited by name below. *)
let sk_vkind__Measure__is_anacrusis__skip (#num #flt: eqtype) (n: string) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Lemma (requires (n <> "isAnacrusis")) (ensures (find_field n (sfx_vkind__Measure__is_anacrusis e rest) == find_field n rest))
  = reveal_opaque (`%sfx_vkind__Measure__is_anacrusis) (sfx_vkind__Measure__is_anacrusis #num #flt e rest)
let sk_vkind__Measure__is_anacrusis__hit (#num #flt: eqtype) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Lemma (requires (Some? e)) (ensures (find_field "isAnacrusis" (sfx_vkind__Measure__is_anacrusis e rest) == Ok (Some?.v e)))
  = reveal_opaque (`%sfx_vkind__Measure__is_anacrusis) (sfx_vkind__Measure__is_anacrusis #num #flt e rest)
let sk_vkind__Measure__is_anacrusis__none (#num #flt: eqtype) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Lemma (requires (None? e)) (ensures (sfx_vkind__Measure__is_anacrusis e rest == rest))
  = reveal_opaque (`%sfx_vkind__Measure__is_anacrusis) (sfx_vkind__Measure__is_anacrusis #num #flt e rest)
let sk_vkind__Measure__repeat_end__skip (#num #flt: eqtype) (n: string) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Lemma (requires (n <> "repeatEnd")) (ensures (find_field n (sfx_vkind__Measure__repeat_end e rest) == find_field n rest))
  = reveal_opaque (`%sfx_vkind__Measure__repeat_end) (sfx_vkind__Measure__repeat_end #num #flt e rest)
let sk_vkind__Measure__repeat_end__hit (#num #flt: eqtype) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Lemma (requires (Some? e)) (ensures (find_field "repeatEnd" (sfx_vkind__Measure__repeat_end e rest) == Ok (Some?.v e)))
  = reveal_opaque (`%sfx_vkind__Measure__repeat_end) (sfx_vkind__Measure__repeat_end #num #flt e rest)
let sk_vkind__Measure__repeat_end__none (#num #flt: eqtype) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Lemma (requires (None? e)) (ensures (sfx_vkind__Measure__repeat_end e rest == rest))
  = reveal_opaque (`%sfx_vkind__Measure__repeat_end) (sfx_vkind__Measure__repeat_end #num #flt e rest)
let sk_vkind__Measure__repeat_start__skip (#num #flt: eqtype) (n: string) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Lemma (requires (n <> "repeatStart")) (ensures (find_field n (sfx_vkind__Measure__repeat_start e rest) == find_field n rest))
  = reveal_opaque (`%sfx_vkind__Measure__repeat_start) (sfx_vkind__Measure__repeat_start #num #flt e rest)
let sk_vkind__Measure__repeat_start__hit (#num #flt: eqtype) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Lemma (requires (Some? e)) (ensures (find_field "repeatStart" (sfx_vkind__Measure__repeat_start e rest) == Ok (Some?.v e)))
  = reveal_opaque (`%sfx_vkind__Measure__repeat_start) (sfx_vkind__Measure__repeat_start #num #flt e rest)
let sk_vkind__Measure__repeat_start__none (#num #flt: eqtype) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Lemma (requires (None? e)) (ensures (sfx_vkind__Measure__repeat_start e rest == rest))
  = reveal_opaque (`%sfx_vkind__Measure__repeat_start) (sfx_vkind__Measure__repeat_start #num #flt e rest)
let sk_vkind__Measure__volta__skip (#num #flt: eqtype) (n: string) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Lemma (requires (n <> "volta")) (ensures (find_field n (sfx_vkind__Measure__volta e rest) == find_field n rest))
  = reveal_opaque (`%sfx_vkind__Measure__volta) (sfx_vkind__Measure__volta #num #flt e rest)
let sk_vkind__Measure__volta__hit (#num #flt: eqtype) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Lemma (requires (Some? e)) (ensures (find_field "volta" (sfx_vkind__Measure__volta e rest) == Ok (Some?.v e)))
  = reveal_opaque (`%sfx_vkind__Measure__volta) (sfx_vkind__Measure__volta #num #flt e rest)
let sk_vkind__Measure__volta__none (#num #flt: eqtype) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Lemma (requires (None? e)) (ensures (sfx_vkind__Measure__volta e rest == rest))
  = reveal_opaque (`%sfx_vkind__Measure__volta) (sfx_vkind__Measure__volta #num #flt e rest)

(* lk_vkind__Measure__is_anacrusis__present — isAnacrusis not at its default *)
#push-options "--fuel 8 --ifuel 4"
let lk_vkind__Measure__is_anacrusis__present (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (match x with | C__vkind__Measure f0 f1 f2 f3 f4 f5 -> not (f1 = false) | _ -> false)) (ensures (match x with | C__vkind__Measure f0 f1 f2 f3 f4 f5 -> get_prop "isAnacrusis" (enc_vkind #num #flt x) == Ok (JBool f1) | _ -> True)) =
  match x with
  | C__vkind__Measure f0 f1 f2 f3 f4 f5 ->
    let s3 = sfx_vkind__Measure__volta #num #flt (enc_opt_l_int #num #flt f5) ([]) in
    let s2 = sfx_vkind__Measure__repeat_start #num #flt (enc_dflt_bool #num #flt (false) f4) (s3) in
    let s1 = sfx_vkind__Measure__repeat_end #num #flt (enc_dflt_bool #num #flt (false) f3) (s2) in
    let s0 = sfx_vkind__Measure__is_anacrusis #num #flt (enc_dflt_bool #num #flt (false) f1) (("number", JInt f2) :: s1) in
    sk_vkind__Measure__is_anacrusis__hit #num #flt (enc_dflt_bool #num #flt (false) f1) (("number", JInt f2) :: s1)
  | _ -> ()
#pop-options

(* lk_vkind__Measure__is_anacrusis__absent — isAnacrusis at its default *)
#push-options "--fuel 8 --ifuel 4"
let lk_vkind__Measure__is_anacrusis__absent (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (match x with | C__vkind__Measure f0 f1 f2 f3 f4 f5 -> f1 = false | _ -> false)) (ensures (Error? (get_prop "isAnacrusis" (enc_vkind #num #flt x)))) =
  match x with
  | C__vkind__Measure f0 f1 f2 f3 f4 f5 ->
    let s3 = sfx_vkind__Measure__volta #num #flt (enc_opt_l_int #num #flt f5) ([]) in
    let s2 = sfx_vkind__Measure__repeat_start #num #flt (enc_dflt_bool #num #flt (false) f4) (s3) in
    let s1 = sfx_vkind__Measure__repeat_end #num #flt (enc_dflt_bool #num #flt (false) f3) (s2) in
    let s0 = sfx_vkind__Measure__is_anacrusis #num #flt (enc_dflt_bool #num #flt (false) f1) (("number", JInt f2) :: s1) in
    sk_vkind__Measure__is_anacrusis__none #num #flt (enc_dflt_bool #num #flt (false) f1) (("number", JInt f2) :: s1);
    sk_vkind__Measure__repeat_end__skip #num #flt "isAnacrusis" (enc_dflt_bool #num #flt (false) f3) (s2);
    sk_vkind__Measure__repeat_start__skip #num #flt "isAnacrusis" (enc_dflt_bool #num #flt (false) f4) (s3);
    sk_vkind__Measure__volta__skip #num #flt "isAnacrusis" (enc_opt_l_int #num #flt f5) ([])
  | _ -> ()
#pop-options

(* lk_vkind__Measure__number — number — always emitted, at a position the conditionals before it move *)
#push-options "--fuel 8 --ifuel 4"
let lk_vkind__Measure__number (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__Measure? x)) (ensures (match x with | C__vkind__Measure f0 f1 f2 f3 f4 f5 -> get_prop "number" (enc_vkind #num #flt x) == Ok (JInt f2) | _ -> True)) =
  match x with
  | C__vkind__Measure f0 f1 f2 f3 f4 f5 ->
    let s3 = sfx_vkind__Measure__volta #num #flt (enc_opt_l_int #num #flt f5) ([]) in
    let s2 = sfx_vkind__Measure__repeat_start #num #flt (enc_dflt_bool #num #flt (false) f4) (s3) in
    let s1 = sfx_vkind__Measure__repeat_end #num #flt (enc_dflt_bool #num #flt (false) f3) (s2) in
    let s0 = sfx_vkind__Measure__is_anacrusis #num #flt (enc_dflt_bool #num #flt (false) f1) (("number", JInt f2) :: s1) in
    sk_vkind__Measure__is_anacrusis__skip #num #flt "number" (enc_dflt_bool #num #flt (false) f1) (("number", JInt f2) :: s1)
  | _ -> ()
#pop-options

(* lk_vkind__Measure__repeat_end__present — repeatEnd not at its default *)
#push-options "--fuel 8 --ifuel 4"
let lk_vkind__Measure__repeat_end__present (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (match x with | C__vkind__Measure f0 f1 f2 f3 f4 f5 -> not (f3 = false) | _ -> false)) (ensures (match x with | C__vkind__Measure f0 f1 f2 f3 f4 f5 -> get_prop "repeatEnd" (enc_vkind #num #flt x) == Ok (JBool f3) | _ -> True)) =
  match x with
  | C__vkind__Measure f0 f1 f2 f3 f4 f5 ->
    let s3 = sfx_vkind__Measure__volta #num #flt (enc_opt_l_int #num #flt f5) ([]) in
    let s2 = sfx_vkind__Measure__repeat_start #num #flt (enc_dflt_bool #num #flt (false) f4) (s3) in
    let s1 = sfx_vkind__Measure__repeat_end #num #flt (enc_dflt_bool #num #flt (false) f3) (s2) in
    let s0 = sfx_vkind__Measure__is_anacrusis #num #flt (enc_dflt_bool #num #flt (false) f1) (("number", JInt f2) :: s1) in
    sk_vkind__Measure__is_anacrusis__skip #num #flt "repeatEnd" (enc_dflt_bool #num #flt (false) f1) (("number", JInt f2) :: s1);
    sk_vkind__Measure__repeat_end__hit #num #flt (enc_dflt_bool #num #flt (false) f3) (s2)
  | _ -> ()
#pop-options

(* lk_vkind__Measure__repeat_end__absent — repeatEnd at its default *)
#push-options "--fuel 8 --ifuel 4"
let lk_vkind__Measure__repeat_end__absent (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (match x with | C__vkind__Measure f0 f1 f2 f3 f4 f5 -> f3 = false | _ -> false)) (ensures (Error? (get_prop "repeatEnd" (enc_vkind #num #flt x)))) =
  match x with
  | C__vkind__Measure f0 f1 f2 f3 f4 f5 ->
    let s3 = sfx_vkind__Measure__volta #num #flt (enc_opt_l_int #num #flt f5) ([]) in
    let s2 = sfx_vkind__Measure__repeat_start #num #flt (enc_dflt_bool #num #flt (false) f4) (s3) in
    let s1 = sfx_vkind__Measure__repeat_end #num #flt (enc_dflt_bool #num #flt (false) f3) (s2) in
    let s0 = sfx_vkind__Measure__is_anacrusis #num #flt (enc_dflt_bool #num #flt (false) f1) (("number", JInt f2) :: s1) in
    sk_vkind__Measure__is_anacrusis__skip #num #flt "repeatEnd" (enc_dflt_bool #num #flt (false) f1) (("number", JInt f2) :: s1);
    sk_vkind__Measure__repeat_end__none #num #flt (enc_dflt_bool #num #flt (false) f3) (s2);
    sk_vkind__Measure__repeat_start__skip #num #flt "repeatEnd" (enc_dflt_bool #num #flt (false) f4) (s3);
    sk_vkind__Measure__volta__skip #num #flt "repeatEnd" (enc_opt_l_int #num #flt f5) ([])
  | _ -> ()
#pop-options

(* lk_vkind__Measure__repeat_start__present — repeatStart not at its default *)
#push-options "--fuel 8 --ifuel 4"
let lk_vkind__Measure__repeat_start__present (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (match x with | C__vkind__Measure f0 f1 f2 f3 f4 f5 -> not (f4 = false) | _ -> false)) (ensures (match x with | C__vkind__Measure f0 f1 f2 f3 f4 f5 -> get_prop "repeatStart" (enc_vkind #num #flt x) == Ok (JBool f4) | _ -> True)) =
  match x with
  | C__vkind__Measure f0 f1 f2 f3 f4 f5 ->
    let s3 = sfx_vkind__Measure__volta #num #flt (enc_opt_l_int #num #flt f5) ([]) in
    let s2 = sfx_vkind__Measure__repeat_start #num #flt (enc_dflt_bool #num #flt (false) f4) (s3) in
    let s1 = sfx_vkind__Measure__repeat_end #num #flt (enc_dflt_bool #num #flt (false) f3) (s2) in
    let s0 = sfx_vkind__Measure__is_anacrusis #num #flt (enc_dflt_bool #num #flt (false) f1) (("number", JInt f2) :: s1) in
    sk_vkind__Measure__is_anacrusis__skip #num #flt "repeatStart" (enc_dflt_bool #num #flt (false) f1) (("number", JInt f2) :: s1);
    sk_vkind__Measure__repeat_end__skip #num #flt "repeatStart" (enc_dflt_bool #num #flt (false) f3) (s2);
    sk_vkind__Measure__repeat_start__hit #num #flt (enc_dflt_bool #num #flt (false) f4) (s3)
  | _ -> ()
#pop-options

(* lk_vkind__Measure__repeat_start__absent — repeatStart at its default *)
#push-options "--fuel 8 --ifuel 4"
let lk_vkind__Measure__repeat_start__absent (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (match x with | C__vkind__Measure f0 f1 f2 f3 f4 f5 -> f4 = false | _ -> false)) (ensures (Error? (get_prop "repeatStart" (enc_vkind #num #flt x)))) =
  match x with
  | C__vkind__Measure f0 f1 f2 f3 f4 f5 ->
    let s3 = sfx_vkind__Measure__volta #num #flt (enc_opt_l_int #num #flt f5) ([]) in
    let s2 = sfx_vkind__Measure__repeat_start #num #flt (enc_dflt_bool #num #flt (false) f4) (s3) in
    let s1 = sfx_vkind__Measure__repeat_end #num #flt (enc_dflt_bool #num #flt (false) f3) (s2) in
    let s0 = sfx_vkind__Measure__is_anacrusis #num #flt (enc_dflt_bool #num #flt (false) f1) (("number", JInt f2) :: s1) in
    sk_vkind__Measure__is_anacrusis__skip #num #flt "repeatStart" (enc_dflt_bool #num #flt (false) f1) (("number", JInt f2) :: s1);
    sk_vkind__Measure__repeat_end__skip #num #flt "repeatStart" (enc_dflt_bool #num #flt (false) f3) (s2);
    sk_vkind__Measure__repeat_start__none #num #flt (enc_dflt_bool #num #flt (false) f4) (s3);
    sk_vkind__Measure__volta__skip #num #flt "repeatStart" (enc_opt_l_int #num #flt f5) ([])
  | _ -> ()
#pop-options

(* lk_vkind__Measure__volta__present — volta present *)
#push-options "--fuel 8 --ifuel 4"
let lk_vkind__Measure__volta__present (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (match x with | C__vkind__Measure f0 f1 f2 f3 f4 f5 -> Some? f5 | _ -> false)) (ensures (match x with | C__vkind__Measure f0 f1 f2 f3 f4 f5 -> get_prop "volta" (enc_vkind #num #flt x) == Ok (JArr (enc_items_l_int (Some?.v f5))) | _ -> True)) =
  match x with
  | C__vkind__Measure f0 f1 f2 f3 f4 f5 ->
    let s3 = sfx_vkind__Measure__volta #num #flt (enc_opt_l_int #num #flt f5) ([]) in
    let s2 = sfx_vkind__Measure__repeat_start #num #flt (enc_dflt_bool #num #flt (false) f4) (s3) in
    let s1 = sfx_vkind__Measure__repeat_end #num #flt (enc_dflt_bool #num #flt (false) f3) (s2) in
    let s0 = sfx_vkind__Measure__is_anacrusis #num #flt (enc_dflt_bool #num #flt (false) f1) (("number", JInt f2) :: s1) in
    sk_vkind__Measure__is_anacrusis__skip #num #flt "volta" (enc_dflt_bool #num #flt (false) f1) (("number", JInt f2) :: s1);
    sk_vkind__Measure__repeat_end__skip #num #flt "volta" (enc_dflt_bool #num #flt (false) f3) (s2);
    sk_vkind__Measure__repeat_start__skip #num #flt "volta" (enc_dflt_bool #num #flt (false) f4) (s3);
    sk_vkind__Measure__volta__hit #num #flt (enc_opt_l_int #num #flt f5) ([])
  | _ -> ()
#pop-options

(* lk_vkind__Measure__volta__absent — volta absent *)
#push-options "--fuel 8 --ifuel 4"
let lk_vkind__Measure__volta__absent (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (match x with | C__vkind__Measure f0 f1 f2 f3 f4 f5 -> None? f5 | _ -> false)) (ensures (Error? (get_prop "volta" (enc_vkind #num #flt x)))) =
  match x with
  | C__vkind__Measure f0 f1 f2 f3 f4 f5 ->
    let s3 = sfx_vkind__Measure__volta #num #flt (enc_opt_l_int #num #flt f5) ([]) in
    let s2 = sfx_vkind__Measure__repeat_start #num #flt (enc_dflt_bool #num #flt (false) f4) (s3) in
    let s1 = sfx_vkind__Measure__repeat_end #num #flt (enc_dflt_bool #num #flt (false) f3) (s2) in
    let s0 = sfx_vkind__Measure__is_anacrusis #num #flt (enc_dflt_bool #num #flt (false) f1) (("number", JInt f2) :: s1) in
    sk_vkind__Measure__is_anacrusis__skip #num #flt "volta" (enc_dflt_bool #num #flt (false) f1) (("number", JInt f2) :: s1);
    sk_vkind__Measure__repeat_end__skip #num #flt "volta" (enc_dflt_bool #num #flt (false) f3) (s2);
    sk_vkind__Measure__repeat_start__skip #num #flt "volta" (enc_dflt_bool #num #flt (false) f4) (s3);
    sk_vkind__Measure__volta__none #num #flt (enc_opt_l_int #num #flt f5) ([])
  | _ -> ()
#pop-options

(* ======================================================================================
   3. THE ROUND TRIP. One mutual induction over the whole family, recursing on the MODEL
      value — F*'s subterm order spans a mutual inductive family, so each case needs only
      the sub-lemmas of the members it carries. ONE LEMMA PER CONSTRUCTOR: a wide one is
      proved by citing section 2's lookups, a member at a time, rather than by carrying
      its object shapes into this query.
   ====================================================================================== *)

let rec rt_node (#num #flt: eqtype) (x: node num flt) : Lemma (ensures dec_node (enc_node #num #flt x) == Ok x) (decreases %[x; 2]) =
  match x with
  | C__node__Node i k -> rt_vkind #num #flt k

and rt_vkind (#num #flt: eqtype) (x: vkind num flt) : Lemma (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 2]) =
  match x with
  | C__vkind__Score _ _ _ -> rt_vkind__Score #num #flt x
  | C__vkind__Part _ _ _ -> rt_vkind__Part #num #flt x
  | C__vkind__PartGroup _ _ _ -> rt_vkind__PartGroup #num #flt x
  | C__vkind__Measure _ _ _ _ _ _ -> rt_vkind__Measure #num #flt x
  | C__vkind__Staff _ _ -> rt_vkind__Staff #num #flt x
  | C__vkind__GraceNote _ _ -> rt_vkind__GraceNote #num #flt x
  | C__vkind__Dynamic _ -> rt_vkind__Dynamic #num #flt x
  | C__vkind__Fermata -> rt_vkind__Fermata #num #flt x
  | C__vkind__HairpinStart _ -> rt_vkind__HairpinStart #num #flt x
  | C__vkind__HairpinEnd -> rt_vkind__HairpinEnd #num #flt x
  | C__vkind__SlurStart -> rt_vkind__SlurStart #num #flt x
  | C__vkind__SlurEnd -> rt_vkind__SlurEnd #num #flt x
  | C__vkind__OctaveShiftStart _ -> rt_vkind__OctaveShiftStart #num #flt x
  | C__vkind__OctaveShiftEnd -> rt_vkind__OctaveShiftEnd #num #flt x
  | C__vkind__MultiRest _ -> rt_vkind__MultiRest #num #flt x
  | C__vkind__Ornament _ _ -> rt_vkind__Ornament #num #flt x
  | C__vkind__RehearsalMark _ -> rt_vkind__RehearsalMark #num #flt x
  | C__vkind__NavigationMark _ -> rt_vkind__NavigationMark #num #flt x
  | C__vkind__Form _ _ _ -> rt_vkind__Form #num #flt x

and rt_vkind__Score (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__Score? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__Score f0 f1 f2 ->
    (match f1 with | None -> lk_vkind__Score__composer__absent #num #flt x | Some _ -> lk_vkind__Score__composer__present #num #flt x);
    (match f2 with | None -> lk_vkind__Score__title__absent #num #flt x | Some _ -> lk_vkind__Score__title__present #num #flt x);
    rt_items_l_node #num #flt [] f0

and rt_vkind__Part (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__Part? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__Part f0 f1 f2 -> rt_items_l_node #num #flt [] f0; rt_items_l_r_staff_definition #num #flt [] f2

and rt_vkind__PartGroup (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__PartGroup? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__PartGroup f0 f1 f2 -> rt_e_bracket_kind #num #flt f0; rt_items_l_node #num #flt [] f1

and rt_vkind__Measure (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__Measure? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__Measure f0 f1 f2 f3 f4 f5 ->
    (if f1 = false then lk_vkind__Measure__is_anacrusis__absent #num #flt x else lk_vkind__Measure__is_anacrusis__present #num #flt x);
    lk_vkind__Measure__number #num #flt x;
    (if f3 = false then lk_vkind__Measure__repeat_end__absent #num #flt x else lk_vkind__Measure__repeat_end__present #num #flt x);
    (if f4 = false then lk_vkind__Measure__repeat_start__absent #num #flt x else lk_vkind__Measure__repeat_start__present #num #flt x);
    (match f5 with | None -> lk_vkind__Measure__volta__absent #num #flt x | Some _ -> lk_vkind__Measure__volta__present #num #flt x);
    rt_items_l_node #num #flt [] f0; (match f5 with | None -> () | Some w -> rt_items_l_int #num #flt [] w)

and rt_vkind__Staff (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__Staff? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__Staff f0 f1 -> rt_items_l_node #num #flt [] f0

and rt_vkind__GraceNote (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__GraceNote? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__GraceNote f0 f1 -> rt_e_grace_kind #num #flt f0; rt_r_pitch #num #flt f1

and rt_vkind__Dynamic (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__Dynamic? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__Dynamic f0 -> rt_e_dynamic_level #num #flt f0

and rt_vkind__Fermata (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__Fermata? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__Fermata -> ()

and rt_vkind__HairpinStart (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__HairpinStart? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__HairpinStart f0 -> rt_e_hairpin_kind #num #flt f0

and rt_vkind__HairpinEnd (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__HairpinEnd? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__HairpinEnd -> ()

and rt_vkind__SlurStart (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__SlurStart? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__SlurStart -> ()

and rt_vkind__SlurEnd (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__SlurEnd? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__SlurEnd -> ()

and rt_vkind__OctaveShiftStart (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__OctaveShiftStart? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__OctaveShiftStart f0 -> rt_e_octave_shift_kind #num #flt f0

and rt_vkind__OctaveShiftEnd (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__OctaveShiftEnd? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__OctaveShiftEnd -> ()

and rt_vkind__MultiRest (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__MultiRest? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__MultiRest f0 -> ()

and rt_vkind__Ornament (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__Ornament? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__Ornament f0 f1 -> rt_e_ornament_name #num #flt f0

and rt_vkind__RehearsalMark (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__RehearsalMark? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__RehearsalMark f0 -> ()

and rt_vkind__NavigationMark (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__NavigationMark? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__NavigationMark f0 -> rt_e_navigation_kind #num #flt f0

and rt_vkind__Form (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__Form? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__Form f0 f1 f2 -> rt_items_l_str #num #flt [] f0; rt_items_l_r_form_section #num #flt [] f2

and rt_r_staff_definition (#num #flt: eqtype) (x: r_staff_definition num flt) : Lemma (ensures dec_r_staff_definition (enc_r_staff_definition #num #flt x) == Ok x) (decreases %[x; 2]) =
  match x with
  | C__r_staff_definition__Mk f0 f1 f2 f3 -> rt_e_clef_kind #num #flt f0; rt_r_key_signature #num #flt f1; rt_r_time_signature #num #flt f2

and rt_r_key_signature (#num #flt: eqtype) (x: r_key_signature num flt) : Lemma (ensures dec_r_key_signature (enc_r_key_signature #num #flt x) == Ok x) (decreases %[x; 2]) =
  match x with
  | C__r_key_signature__Mk f0 f1 f2 -> rt_e_mode #num #flt f0; rt_e_note_letter #num #flt f1; rt_e_accidental #num #flt f2

and rt_r_time_signature (#num #flt: eqtype) (x: r_time_signature num flt) : Lemma (ensures dec_r_time_signature (enc_r_time_signature #num #flt x) == Ok x) (decreases %[x; 2]) =
  match x with
  | C__r_time_signature__Mk f0 f1 -> ()

and rt_r_pitch (#num #flt: eqtype) (x: r_pitch num flt) : Lemma (ensures dec_r_pitch (enc_r_pitch #num #flt x) == Ok x) (decreases %[x; 2]) =
  match x with
  | C__r_pitch__Mk f0 f1 f2 f3 -> rt_e_accidental #num #flt f0; rt_e_note_letter #num #flt f1

and rt_r_form_section (#num #flt: eqtype) (x: r_form_section num flt) : Lemma (ensures dec_r_form_section (enc_r_form_section #num #flt x) == Ok x) (decreases %[x; 2]) =
  match x with
  | C__r_form_section__Mk f0 f1 -> rt_items_l_node #num #flt [] f0

and rt_items_l_node (#num #flt: eqtype) (acc: list (node num flt)) (xs: list (node num flt)) : Lemma (ensures dec_items_l_node acc (enc_items_l_node #num #flt xs) == Ok (rev_app acc xs)) (decreases %[xs; 2]) =
  match xs with
  | [] -> ()
  | y :: t -> rt_node #num #flt y; rt_items_l_node #num #flt (y :: acc) t

and rt_items_l_r_staff_definition (#num #flt: eqtype) (acc: list (r_staff_definition num flt)) (xs: list (r_staff_definition num flt)) : Lemma (ensures dec_items_l_r_staff_definition acc (enc_items_l_r_staff_definition #num #flt xs) == Ok (rev_app acc xs)) (decreases %[xs; 2]) =
  match xs with
  | [] -> ()
  | y :: t -> rt_r_staff_definition #num #flt y; rt_items_l_r_staff_definition #num #flt (y :: acc) t

and rt_items_l_int (#num #flt: eqtype) (acc: list (num)) (xs: list (num)) : Lemma (ensures dec_items_l_int acc (enc_items_l_int #num #flt xs) == Ok (rev_app acc xs)) (decreases %[xs; 2]) =
  match xs with
  | [] -> ()
  | y :: t -> rt_items_l_int #num #flt (y :: acc) t

and rt_items_l_r_form_section (#num #flt: eqtype) (acc: list (r_form_section num flt)) (xs: list (r_form_section num flt)) : Lemma (ensures dec_items_l_r_form_section acc (enc_items_l_r_form_section #num #flt xs) == Ok (rev_app acc xs)) (decreases %[xs; 2]) =
  match xs with
  | [] -> ()
  | y :: t -> rt_r_form_section #num #flt y; rt_items_l_r_form_section #num #flt (y :: acc) t

and rt_items_l_str (#num #flt: eqtype) (acc: list (string)) (xs: list (string)) : Lemma (ensures dec_items_l_str acc (enc_items_l_str #num #flt xs) == Ok (rev_app acc xs)) (decreases %[xs; 2]) =
  match xs with
  | [] -> ()
  | y :: t -> rt_items_l_str #num #flt (y :: acc) t

(* ======================================================================================
   4. TOTALITY. That the decoders type-check at `Tot` is the termination proof; what the
      lemma adds is that the outcome is exactly one of the two, for EVERY input — the
      failure classification is exhaustive rather than merely non-empty.
   ====================================================================================== *)

let dec_node_total (#num #flt: eqtype) (el: jval num flt)
  : Lemma (ensures (Ok? (dec_node el) \/ Error? (dec_node el)) /\
                   ~(Ok? (dec_node el) /\ Error? (dec_node el)))
  = ()

