(*
   ScoreVocabularyProofs — GENERATED by Fuaran.Core.Idl.Codegen's F* target, from the same walk that
   emits `ScoreVocabulary.fst`, over
   the vendored THIRD-DOMAIN sample — `tests/Fuaran.Core.Tests/ScoreDomainSpike.fs`,
   a notation vocabulary with a corpus written outside this repository: records and
   omit-at-default at scale, on the same declared non-default wire shape
   (fuaran-core Phase 173, applying D14 to `proofs/`).
   DO NOT EDIT: `dotnet run --project tests/Fuaran.Core.Tests -- --emit-fstar` regenerates
   it, and the `Proofs.Vocabulary` family holds this file to a fresh generation from that
   source — a vocabulary that moves without a regeneration is VOCABULARY DRIFT, and
   `proofs/check.ps1` names it.

   WHAT IS PROVED, and why it is GENERATED rather than written.

   Phase 135 proved `decode (encode n) == Ok n` for a hand-written four-case REFERENCE
   vocabulary, and was explicit about the boundary: a theorem about a reference vocabulary
   is not a theorem about the one a host actually decodes. The real vocabulary has dozens
   of kinds — 19 of this one's 21 are modelled — and it grows. A HAND-WRITTEN proof over
   it would be a theorem about the vocabulary as it stood on the day it was written, which
   is the same defect one release later. So the proof script is emitted by the walk that
   emits the model: a kind added to the IDL re-proves itself at the next `check.ps1`, and a
   kind whose encoder and decoder disagree fails it.

     - `rt_node` and the family beside it — THE ROUND TRIP. For every value of every
       modelled type, decoding its encoding returns that value: `dec_node (enc_node x) ==
       Ok x`, at every depth, through every list, map, optional member and omit-default.
     - `dec_node_total` — TOTALITY, and the exclusivity of the outcome. That the decoders
       type-check at `Tot` is the termination proof; the lemma states that every input
       reaches exactly one of `Ok` / `Error` and never both.

   WHAT IS NOT PROVED HERE. The `wf` CHARACTERISATION — `Ok? (dec el) == wf el`, which
   Phase 135 carries for the reference vocabulary — is not restated over the generated
   vocabulary: it needs a second generated predicate mirroring the decoder's accept set,
   which is a model-sized artefact of its own. The round trip covers one direction
   (everything the encoder can produce is read back exactly); the characterisation of what
   ELSE is accepted is not covered, and is named here rather than left to be assumed.

   TWO COST OPTIONS ARE PART OF THE ARTEFACT, and the second was MEASURED rather than
   guessed. `--ext context_pruning` is set below for the reason the model module's header
   gives at greater length: a mutual induction over the whole family would otherwise carry
   the whole family in every query.

   The other is a MEASURED finding rather than a default anybody chose, and it was measured
   at the scale this emitter was first run at — a twenty-kind vocabulary whose node envelope
   carries five OPTIONAL members (fuaran-core Phase 150). Under the leg's own `--quake 3`
   that node lemma proved 64 of 65 goals in a single query and FAILED the third seed at the
   leg's default rlimit of 40 — green standalone and red under `check.ps1`, exactly the
   shape `Preservation`'s `invert_applicable` records in `modules.json`, and exactly the
   failure an unquaked run hides. `--z3rlimit 200` is the same remedy that precedent took.
   It is a blunt one: the hard goal is hard because k conditional envelope members put 2^k
   object shapes in one query, and isolating that goal would be the sharper fix —
   `--split_queries` is not settable as a pragma on the pinned prover, so it would mean
   emitting the node's proof as several smaller lemmas, which is a successor's work rather
   than a flag. A vocabulary with a small envelope never meets the goal and pays nothing for
   the option. If this module is ever slow enough to want investigating, check both options
   are still in force first: losing the rlimit does not read as slowness, it reads as a flake.

   Apache-2.0, like everything beside it.
*)
module ScoreVocabularyProofs

open WireDecode
open ScoreVocabulary

#set-options "--z3rlimit 200 --ext context_pruning"

(* ======================================================================================
   1. The closed string sets. Each is a finite match on distinct literals, so its round
      trip is definitional — stated anyway, because the family below calls it by name.
   ====================================================================================== *)

let rt_e_clef_kind (#num #flt: eqtype) (x: e_clef_kind) : Lemma (ensures dec_e_clef_kind (enc_e_clef_kind #num #flt x) == Ok x) = ()
let rt_e_note_letter (#num #flt: eqtype) (x: e_note_letter) : Lemma (ensures dec_e_note_letter (enc_e_note_letter #num #flt x) == Ok x) = ()
let rt_e_accidental (#num #flt: eqtype) (x: e_accidental) : Lemma (ensures dec_e_accidental (enc_e_accidental #num #flt x) == Ok x) = ()
let rt_e_mode (#num #flt: eqtype) (x: e_mode) : Lemma (ensures dec_e_mode (enc_e_mode #num #flt x) == Ok x) = ()
let rt_e_bracket_kind (#num #flt: eqtype) (x: e_bracket_kind) : Lemma (ensures dec_e_bracket_kind (enc_e_bracket_kind #num #flt x) == Ok x) = ()
let rt_e_grace_kind (#num #flt: eqtype) (x: e_grace_kind) : Lemma (ensures dec_e_grace_kind (enc_e_grace_kind #num #flt x) == Ok x) = ()
let rt_e_dynamic_level (#num #flt: eqtype) (x: e_dynamic_level) : Lemma (ensures dec_e_dynamic_level (enc_e_dynamic_level #num #flt x) == Ok x) = ()
let rt_e_hairpin_kind (#num #flt: eqtype) (x: e_hairpin_kind) : Lemma (ensures dec_e_hairpin_kind (enc_e_hairpin_kind #num #flt x) == Ok x) = ()
let rt_e_octave_shift_kind (#num #flt: eqtype) (x: e_octave_shift_kind) : Lemma (ensures dec_e_octave_shift_kind (enc_e_octave_shift_kind #num #flt x) == Ok x) = ()
let rt_e_ornament_name (#num #flt: eqtype) (x: e_ornament_name) : Lemma (ensures dec_e_ornament_name (enc_e_ornament_name #num #flt x) == Ok x) = ()
let rt_e_navigation_kind (#num #flt: eqtype) (x: e_navigation_kind) : Lemma (ensures dec_e_navigation_kind (enc_e_navigation_kind #num #flt x) == Ok x) = ()

(* ======================================================================================
   2. THE ROUND TRIP. One mutual induction over the whole family, recursing on the MODEL
      value — F*'s subterm order spans a mutual inductive family, so each case needs only
      the sub-lemmas of the members it carries.
   ====================================================================================== *)

let rec rt_node (#num #flt: eqtype) (x: node num flt) : Lemma (ensures dec_node (enc_node #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__node__Node i k  ->
    rt_vkind #num #flt k

and rt_vkind (#num #flt: eqtype) (x: vkind num flt) : Lemma (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__vkind__Score f0 f1 f2 -> rt_items_l_node #num #flt [] f0
  | C__vkind__Part f0 f1 f2 -> rt_items_l_node #num #flt [] f0; rt_items_l_r_staff_definition #num #flt [] f2
  | C__vkind__PartGroup f0 f1 f2 -> rt_e_bracket_kind #num #flt f0; rt_items_l_node #num #flt [] f1
  | C__vkind__Measure f0 f1 f2 f3 f4 f5 -> rt_items_l_node #num #flt [] f0; (match f5 with | None -> () | Some w -> rt_items_l_int #num #flt [] w)
  | C__vkind__Staff f0 f1 -> rt_items_l_node #num #flt [] f0
  | C__vkind__GraceNote f0 f1 -> rt_e_grace_kind #num #flt f0; rt_r_pitch #num #flt f1
  | C__vkind__Dynamic f0 -> rt_e_dynamic_level #num #flt f0
  | C__vkind__Fermata  -> ()
  | C__vkind__HairpinStart f0 -> rt_e_hairpin_kind #num #flt f0
  | C__vkind__HairpinEnd  -> ()
  | C__vkind__SlurStart  -> ()
  | C__vkind__SlurEnd  -> ()
  | C__vkind__OctaveShiftStart f0 -> rt_e_octave_shift_kind #num #flt f0
  | C__vkind__OctaveShiftEnd  -> ()
  | C__vkind__MultiRest f0 -> ()
  | C__vkind__Ornament f0 f1 -> rt_e_ornament_name #num #flt f0
  | C__vkind__RehearsalMark f0 -> ()
  | C__vkind__NavigationMark f0 -> rt_e_navigation_kind #num #flt f0
  | C__vkind__Form f0 f1 f2 -> rt_items_l_str #num #flt [] f0; rt_items_l_r_form_section #num #flt [] f2

and rt_r_staff_definition (#num #flt: eqtype) (x: r_staff_definition num flt) : Lemma (ensures dec_r_staff_definition (enc_r_staff_definition #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__r_staff_definition__Mk f0 f1 f2 f3 -> rt_e_clef_kind #num #flt f0; rt_r_key_signature #num #flt f1; rt_r_time_signature #num #flt f2

and rt_r_key_signature (#num #flt: eqtype) (x: r_key_signature num flt) : Lemma (ensures dec_r_key_signature (enc_r_key_signature #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__r_key_signature__Mk f0 f1 f2 -> rt_e_mode #num #flt f0; rt_e_note_letter #num #flt f1; rt_e_accidental #num #flt f2

and rt_r_time_signature (#num #flt: eqtype) (x: r_time_signature num flt) : Lemma (ensures dec_r_time_signature (enc_r_time_signature #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__r_time_signature__Mk f0 f1 -> ()

and rt_r_pitch (#num #flt: eqtype) (x: r_pitch num flt) : Lemma (ensures dec_r_pitch (enc_r_pitch #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__r_pitch__Mk f0 f1 f2 f3 -> rt_e_accidental #num #flt f0; rt_e_note_letter #num #flt f1

and rt_r_form_section (#num #flt: eqtype) (x: r_form_section num flt) : Lemma (ensures dec_r_form_section (enc_r_form_section #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__r_form_section__Mk f0 f1 -> rt_items_l_node #num #flt [] f0

and rt_items_l_node (#num #flt: eqtype) (acc: list (node num flt)) (xs: list (node num flt)) : Lemma (ensures dec_items_l_node acc (enc_items_l_node #num #flt xs) == Ok (rev_app acc xs)) (decreases xs) =
  match xs with
  | [] -> ()
  | y :: t -> rt_node #num #flt y; rt_items_l_node #num #flt (y :: acc) t

and rt_items_l_r_staff_definition (#num #flt: eqtype) (acc: list (r_staff_definition num flt)) (xs: list (r_staff_definition num flt)) : Lemma (ensures dec_items_l_r_staff_definition acc (enc_items_l_r_staff_definition #num #flt xs) == Ok (rev_app acc xs)) (decreases xs) =
  match xs with
  | [] -> ()
  | y :: t -> rt_r_staff_definition #num #flt y; rt_items_l_r_staff_definition #num #flt (y :: acc) t

and rt_items_l_int (#num #flt: eqtype) (acc: list (num)) (xs: list (num)) : Lemma (ensures dec_items_l_int acc (enc_items_l_int #num #flt xs) == Ok (rev_app acc xs)) (decreases xs) =
  match xs with
  | [] -> ()
  | y :: t -> rt_items_l_int #num #flt (y :: acc) t

and rt_items_l_r_form_section (#num #flt: eqtype) (acc: list (r_form_section num flt)) (xs: list (r_form_section num flt)) : Lemma (ensures dec_items_l_r_form_section acc (enc_items_l_r_form_section #num #flt xs) == Ok (rev_app acc xs)) (decreases xs) =
  match xs with
  | [] -> ()
  | y :: t -> rt_r_form_section #num #flt y; rt_items_l_r_form_section #num #flt (y :: acc) t

and rt_items_l_str (#num #flt: eqtype) (acc: list (string)) (xs: list (string)) : Lemma (ensures dec_items_l_str acc (enc_items_l_str #num #flt xs) == Ok (rev_app acc xs)) (decreases xs) =
  match xs with
  | [] -> ()
  | y :: t -> rt_items_l_str #num #flt (y :: acc) t

(* ======================================================================================
   3. TOTALITY. That the decoders type-check at `Tot` is the termination proof; what the
      lemma adds is that the outcome is exactly one of the two, for EVERY input — the
      failure classification is exhaustive rather than merely non-empty.
   ====================================================================================== *)

let dec_node_total (#num #flt: eqtype) (el: jval num flt)
  : Lemma (ensures (Ok? (dec_node el) \/ Error? (dec_node el)) /\
                   ~(Ok? (dec_node el) /\ Error? (dec_node el)))
  = ()

