(*
   ScoreVocabulary — GENERATED by Fuaran.Core.Idl.Codegen's F* target from
   the vendored THIRD-DOMAIN sample — `tests/Fuaran.Core.Tests/ScoreDomainSpike.fs`,
   a notation vocabulary with a corpus written outside this repository: records and
   omit-at-default at scale, on the same declared non-default wire shape
   (fuaran-core Phase 173, applying D14 to `proofs/`).
   DO NOT EDIT: `dotnet run --project tests/Fuaran.Core.Tests -- --emit-fstar` regenerates
   it, and the `Proofs.Vocabulary` family holds this file to a fresh generation from that
   source — a vocabulary that moves without a regeneration is VOCABULARY DRIFT, and
   `proofs/check.ps1` names it.

   WHAT THIS IS. The vocabulary's types, its discriminated encoder and its tag-dispatch
   decoder, over Phase 135's `jval` value model and the `Decode` combinators modelled
   beside it (`WireDecode.fst`). The theorems over it are in `ScoreVocabularyProofs.fst`, which
   the same generator emits from the same walk — so a kind added to the IDL re-proves
   itself at the next `check.ps1` rather than waiting for a hand-written clause.

   WHAT THIS IS NOT. It is not any host's decoder and no host's build generates it. A
   host keeps its own hand-written, tuned decoder and is certified against its corpus;
   what is proved here is a property of the
   F* BACKEND (`Fuaran.Core.Idl.Codegen`'s `FStarTarget`) over the vocabulary the engine
   is certified on — the same set the F# and TypeScript backends are certified over — and
   not of any domain's vocabulary. A domain proves its own vocabulary in its own
   repository with the same generator; the UI vocabulary's model is `fuaran#1754`'s.

   THE MODEL'S BOUNDARY, stated rather than implied.

     - The numeric carriers are OPAQUE (`num` / `flt`), as they are in `WireDecode`: no
       definition here looks inside a number, it only moves one. A float member therefore
       decodes from `JFloat` alone — the widening `as_float` performs through a supplied
       `to_flt` has nothing to widen when the carriers are parameters, and the encoder
       never emits an integer at a float slot.
     - A HOST-ONLY member has no wire projection and is absent from the model. The model
       is of the wire; a member that is never on the wire is not part of it.
     - A `TMap` is an ASSOCIATION LIST in the authored order. A map has no declared key
       order, and an assoc list is what the wire object is before a renderer sorts it.
     - A `TJson` member, and a host-codec member whose wire is JSON, is carried VERBATIM
       as a `jval`. What such a member holds is the host codec's business, not the
       schema's, and inventing an F* counterpart for a host type would model a fiction.
     - Generic unions are MONOMORPHISED at the arguments this vocabulary reaches, which
       is what keeps every definition and every emitted lemma first-order.

   VOCABULARY. Discriminator "kind", flat-kind envelope, declaration key order.
   19 of 21 kinds are modelled; 6 declared types and 11 enums are reached.
   The kinds NOT modelled — named here rather than silently missing, because a reader
   of the theorem needs to know what it does not cover. Two different reasons, and
   they are worth telling apart: a construct with no wire-level meaning in the model
   is a BOUNDARY, while a kind held out of the proof vocabulary is a COST CONTROL
   that a measurement could lift:

     - Note: the F* proof model cannot express a declared default the opaque numeric model cannot spell: VInt 1 (at kind Note.voice)
     - Chord: the F* proof model cannot express a declared default the opaque numeric model cannot spell: VInt 1 (at kind Chord.voice)

   THE COST OPTION IS PART OF THE ARTEFACT. `--ext context_pruning` is set below rather
   than passed by the leg: this module opens the whole decode model and declares dozens
   of types, so every query would otherwise carry the entire context. Measured on the
   pinned prover it is the difference between a module the leg can afford and one it
   cannot — the same finding `TreeOps`, `JsonParse`, `Preservation` and `TreeDiff` each
   record in `modules.json`. If this module's budget is ever bumped, check the option is
   still here before reading the growth as ordinary.

   Apache-2.0, like everything beside it.
*)
module ScoreVocabulary

open WireDecode

#set-options "--ext context_pruning"

(* ======================================================================================
   1. The closed string sets (`TEnum`) — a bare wire string, not an object.
   ====================================================================================== *)

type e_clef_kind =
  | C__e_clef_kind__Treble
  | C__e_clef_kind__Bass
  | C__e_clef_kind__Alto
  | C__e_clef_kind__Tenor
  | C__e_clef_kind__Percussion

let enc_e_clef_kind (#num #flt: eqtype) (x: e_clef_kind) : Tot (jval num flt) =
  match x with
  | C__e_clef_kind__Treble -> JStr "Treble"
  | C__e_clef_kind__Bass -> JStr "Bass"
  | C__e_clef_kind__Alto -> JStr "Alto"
  | C__e_clef_kind__Tenor -> JStr "Tenor"
  | C__e_clef_kind__Percussion -> JStr "Percussion"

let dec_e_clef_kind (#num #flt: eqtype) (el: jval num flt) : Tot (outcome e_clef_kind) =
  match as_string el with
  | Error e -> Error e
  | Ok s ->
    if s = "Treble" then Ok C__e_clef_kind__Treble else
    if s = "Bass" then Ok C__e_clef_kind__Bass else
    if s = "Alto" then Ok C__e_clef_kind__Alto else
    if s = "Tenor" then Ok C__e_clef_kind__Tenor else
    if s = "Percussion" then Ok C__e_clef_kind__Percussion else
    Error ("unknown ClefKind: " ^ s)

type e_note_letter =
  | C__e_note_letter__C
  | C__e_note_letter__D
  | C__e_note_letter__E
  | C__e_note_letter__F
  | C__e_note_letter__G
  | C__e_note_letter__A
  | C__e_note_letter__B

let enc_e_note_letter (#num #flt: eqtype) (x: e_note_letter) : Tot (jval num flt) =
  match x with
  | C__e_note_letter__C -> JStr "C"
  | C__e_note_letter__D -> JStr "D"
  | C__e_note_letter__E -> JStr "E"
  | C__e_note_letter__F -> JStr "F"
  | C__e_note_letter__G -> JStr "G"
  | C__e_note_letter__A -> JStr "A"
  | C__e_note_letter__B -> JStr "B"

let dec_e_note_letter (#num #flt: eqtype) (el: jval num flt) : Tot (outcome e_note_letter) =
  match as_string el with
  | Error e -> Error e
  | Ok s ->
    if s = "C" then Ok C__e_note_letter__C else
    if s = "D" then Ok C__e_note_letter__D else
    if s = "E" then Ok C__e_note_letter__E else
    if s = "F" then Ok C__e_note_letter__F else
    if s = "G" then Ok C__e_note_letter__G else
    if s = "A" then Ok C__e_note_letter__A else
    if s = "B" then Ok C__e_note_letter__B else
    Error ("unknown NoteLetter: " ^ s)

type e_accidental =
  | C__e_accidental__DoubleFlat
  | C__e_accidental__Flat
  | C__e_accidental__Natural
  | C__e_accidental__Sharp
  | C__e_accidental__DoubleSharp

let enc_e_accidental (#num #flt: eqtype) (x: e_accidental) : Tot (jval num flt) =
  match x with
  | C__e_accidental__DoubleFlat -> JStr "DoubleFlat"
  | C__e_accidental__Flat -> JStr "Flat"
  | C__e_accidental__Natural -> JStr "Natural"
  | C__e_accidental__Sharp -> JStr "Sharp"
  | C__e_accidental__DoubleSharp -> JStr "DoubleSharp"

let dec_e_accidental (#num #flt: eqtype) (el: jval num flt) : Tot (outcome e_accidental) =
  match as_string el with
  | Error e -> Error e
  | Ok s ->
    if s = "DoubleFlat" then Ok C__e_accidental__DoubleFlat else
    if s = "Flat" then Ok C__e_accidental__Flat else
    if s = "Natural" then Ok C__e_accidental__Natural else
    if s = "Sharp" then Ok C__e_accidental__Sharp else
    if s = "DoubleSharp" then Ok C__e_accidental__DoubleSharp else
    Error ("unknown Accidental: " ^ s)

type e_mode =
  | C__e_mode__Ionian
  | C__e_mode__Dorian
  | C__e_mode__Phrygian
  | C__e_mode__Lydian
  | C__e_mode__Mixolydian
  | C__e_mode__Aeolian
  | C__e_mode__Locrian
  | C__e_mode__MelodicMinor
  | C__e_mode__Dorianb2
  | C__e_mode__LydianAugmented
  | C__e_mode__LydianDominant
  | C__e_mode__Mixolydianb6
  | C__e_mode__LocrianNatural2
  | C__e_mode__SuperLocrian
  | C__e_mode__HarmonicMinor
  | C__e_mode__LocrianNatural6
  | C__e_mode__IonianAugmented
  | C__e_mode__DorianSharp4
  | C__e_mode__PhrygianDominant
  | C__e_mode__LydianSharp2
  | C__e_mode__UltraLocrian

let enc_e_mode (#num #flt: eqtype) (x: e_mode) : Tot (jval num flt) =
  match x with
  | C__e_mode__Ionian -> JStr "Ionian"
  | C__e_mode__Dorian -> JStr "Dorian"
  | C__e_mode__Phrygian -> JStr "Phrygian"
  | C__e_mode__Lydian -> JStr "Lydian"
  | C__e_mode__Mixolydian -> JStr "Mixolydian"
  | C__e_mode__Aeolian -> JStr "Aeolian"
  | C__e_mode__Locrian -> JStr "Locrian"
  | C__e_mode__MelodicMinor -> JStr "MelodicMinor"
  | C__e_mode__Dorianb2 -> JStr "Dorianb2"
  | C__e_mode__LydianAugmented -> JStr "LydianAugmented"
  | C__e_mode__LydianDominant -> JStr "LydianDominant"
  | C__e_mode__Mixolydianb6 -> JStr "Mixolydianb6"
  | C__e_mode__LocrianNatural2 -> JStr "LocrianNatural2"
  | C__e_mode__SuperLocrian -> JStr "SuperLocrian"
  | C__e_mode__HarmonicMinor -> JStr "HarmonicMinor"
  | C__e_mode__LocrianNatural6 -> JStr "LocrianNatural6"
  | C__e_mode__IonianAugmented -> JStr "IonianAugmented"
  | C__e_mode__DorianSharp4 -> JStr "DorianSharp4"
  | C__e_mode__PhrygianDominant -> JStr "PhrygianDominant"
  | C__e_mode__LydianSharp2 -> JStr "LydianSharp2"
  | C__e_mode__UltraLocrian -> JStr "UltraLocrian"

let dec_e_mode (#num #flt: eqtype) (el: jval num flt) : Tot (outcome e_mode) =
  match as_string el with
  | Error e -> Error e
  | Ok s ->
    if s = "Ionian" then Ok C__e_mode__Ionian else
    if s = "Dorian" then Ok C__e_mode__Dorian else
    if s = "Phrygian" then Ok C__e_mode__Phrygian else
    if s = "Lydian" then Ok C__e_mode__Lydian else
    if s = "Mixolydian" then Ok C__e_mode__Mixolydian else
    if s = "Aeolian" then Ok C__e_mode__Aeolian else
    if s = "Locrian" then Ok C__e_mode__Locrian else
    if s = "MelodicMinor" then Ok C__e_mode__MelodicMinor else
    if s = "Dorianb2" then Ok C__e_mode__Dorianb2 else
    if s = "LydianAugmented" then Ok C__e_mode__LydianAugmented else
    if s = "LydianDominant" then Ok C__e_mode__LydianDominant else
    if s = "Mixolydianb6" then Ok C__e_mode__Mixolydianb6 else
    if s = "LocrianNatural2" then Ok C__e_mode__LocrianNatural2 else
    if s = "SuperLocrian" then Ok C__e_mode__SuperLocrian else
    if s = "HarmonicMinor" then Ok C__e_mode__HarmonicMinor else
    if s = "LocrianNatural6" then Ok C__e_mode__LocrianNatural6 else
    if s = "IonianAugmented" then Ok C__e_mode__IonianAugmented else
    if s = "DorianSharp4" then Ok C__e_mode__DorianSharp4 else
    if s = "PhrygianDominant" then Ok C__e_mode__PhrygianDominant else
    if s = "LydianSharp2" then Ok C__e_mode__LydianSharp2 else
    if s = "UltraLocrian" then Ok C__e_mode__UltraLocrian else
    Error ("unknown Mode: " ^ s)

type e_bracket_kind =
  | C__e_bracket_kind__Brace
  | C__e_bracket_kind__Square
  | C__e_bracket_kind__Line
  | C__e_bracket_kind__None

let enc_e_bracket_kind (#num #flt: eqtype) (x: e_bracket_kind) : Tot (jval num flt) =
  match x with
  | C__e_bracket_kind__Brace -> JStr "Brace"
  | C__e_bracket_kind__Square -> JStr "Square"
  | C__e_bracket_kind__Line -> JStr "Line"
  | C__e_bracket_kind__None -> JStr "None"

let dec_e_bracket_kind (#num #flt: eqtype) (el: jval num flt) : Tot (outcome e_bracket_kind) =
  match as_string el with
  | Error e -> Error e
  | Ok s ->
    if s = "Brace" then Ok C__e_bracket_kind__Brace else
    if s = "Square" then Ok C__e_bracket_kind__Square else
    if s = "Line" then Ok C__e_bracket_kind__Line else
    if s = "None" then Ok C__e_bracket_kind__None else
    Error ("unknown BracketKind: " ^ s)

type e_grace_kind =
  | C__e_grace_kind__Acciaccatura
  | C__e_grace_kind__Appoggiatura

let enc_e_grace_kind (#num #flt: eqtype) (x: e_grace_kind) : Tot (jval num flt) =
  match x with
  | C__e_grace_kind__Acciaccatura -> JStr "Acciaccatura"
  | C__e_grace_kind__Appoggiatura -> JStr "Appoggiatura"

let dec_e_grace_kind (#num #flt: eqtype) (el: jval num flt) : Tot (outcome e_grace_kind) =
  match as_string el with
  | Error e -> Error e
  | Ok s ->
    if s = "Acciaccatura" then Ok C__e_grace_kind__Acciaccatura else
    if s = "Appoggiatura" then Ok C__e_grace_kind__Appoggiatura else
    Error ("unknown GraceKind: " ^ s)

type e_dynamic_level =
  | C__e_dynamic_level__Pianississimo
  | C__e_dynamic_level__Pianissimo
  | C__e_dynamic_level__Piano
  | C__e_dynamic_level__MezzoPiano
  | C__e_dynamic_level__MezzoForte
  | C__e_dynamic_level__Forte
  | C__e_dynamic_level__Fortissimo
  | C__e_dynamic_level__Fortississimo
  | C__e_dynamic_level__Sforzando
  | C__e_dynamic_level__Forzato
  | C__e_dynamic_level__Rinforzando
  | C__e_dynamic_level__FortePiano
  | C__e_dynamic_level__SforzandoPiano

let enc_e_dynamic_level (#num #flt: eqtype) (x: e_dynamic_level) : Tot (jval num flt) =
  match x with
  | C__e_dynamic_level__Pianississimo -> JStr "Pianississimo"
  | C__e_dynamic_level__Pianissimo -> JStr "Pianissimo"
  | C__e_dynamic_level__Piano -> JStr "Piano"
  | C__e_dynamic_level__MezzoPiano -> JStr "MezzoPiano"
  | C__e_dynamic_level__MezzoForte -> JStr "MezzoForte"
  | C__e_dynamic_level__Forte -> JStr "Forte"
  | C__e_dynamic_level__Fortissimo -> JStr "Fortissimo"
  | C__e_dynamic_level__Fortississimo -> JStr "Fortississimo"
  | C__e_dynamic_level__Sforzando -> JStr "Sforzando"
  | C__e_dynamic_level__Forzato -> JStr "Forzato"
  | C__e_dynamic_level__Rinforzando -> JStr "Rinforzando"
  | C__e_dynamic_level__FortePiano -> JStr "FortePiano"
  | C__e_dynamic_level__SforzandoPiano -> JStr "SforzandoPiano"

let dec_e_dynamic_level (#num #flt: eqtype) (el: jval num flt) : Tot (outcome e_dynamic_level) =
  match as_string el with
  | Error e -> Error e
  | Ok s ->
    if s = "Pianississimo" then Ok C__e_dynamic_level__Pianississimo else
    if s = "Pianissimo" then Ok C__e_dynamic_level__Pianissimo else
    if s = "Piano" then Ok C__e_dynamic_level__Piano else
    if s = "MezzoPiano" then Ok C__e_dynamic_level__MezzoPiano else
    if s = "MezzoForte" then Ok C__e_dynamic_level__MezzoForte else
    if s = "Forte" then Ok C__e_dynamic_level__Forte else
    if s = "Fortissimo" then Ok C__e_dynamic_level__Fortissimo else
    if s = "Fortississimo" then Ok C__e_dynamic_level__Fortississimo else
    if s = "Sforzando" then Ok C__e_dynamic_level__Sforzando else
    if s = "Forzato" then Ok C__e_dynamic_level__Forzato else
    if s = "Rinforzando" then Ok C__e_dynamic_level__Rinforzando else
    if s = "FortePiano" then Ok C__e_dynamic_level__FortePiano else
    if s = "SforzandoPiano" then Ok C__e_dynamic_level__SforzandoPiano else
    Error ("unknown DynamicLevel: " ^ s)

type e_hairpin_kind =
  | C__e_hairpin_kind__Crescendo
  | C__e_hairpin_kind__Decrescendo

let enc_e_hairpin_kind (#num #flt: eqtype) (x: e_hairpin_kind) : Tot (jval num flt) =
  match x with
  | C__e_hairpin_kind__Crescendo -> JStr "Crescendo"
  | C__e_hairpin_kind__Decrescendo -> JStr "Decrescendo"

let dec_e_hairpin_kind (#num #flt: eqtype) (el: jval num flt) : Tot (outcome e_hairpin_kind) =
  match as_string el with
  | Error e -> Error e
  | Ok s ->
    if s = "Crescendo" then Ok C__e_hairpin_kind__Crescendo else
    if s = "Decrescendo" then Ok C__e_hairpin_kind__Decrescendo else
    Error ("unknown HairpinKind: " ^ s)

type e_octave_shift_kind =
  | C__e_octave_shift_kind__Ottava
  | C__e_octave_shift_kind__OttavaBassa
  | C__e_octave_shift_kind__Quindicesima
  | C__e_octave_shift_kind__QuindicesimaBassa

let enc_e_octave_shift_kind (#num #flt: eqtype) (x: e_octave_shift_kind) : Tot (jval num flt) =
  match x with
  | C__e_octave_shift_kind__Ottava -> JStr "Ottava"
  | C__e_octave_shift_kind__OttavaBassa -> JStr "OttavaBassa"
  | C__e_octave_shift_kind__Quindicesima -> JStr "Quindicesima"
  | C__e_octave_shift_kind__QuindicesimaBassa -> JStr "QuindicesimaBassa"

let dec_e_octave_shift_kind (#num #flt: eqtype) (el: jval num flt) : Tot (outcome e_octave_shift_kind) =
  match as_string el with
  | Error e -> Error e
  | Ok s ->
    if s = "Ottava" then Ok C__e_octave_shift_kind__Ottava else
    if s = "OttavaBassa" then Ok C__e_octave_shift_kind__OttavaBassa else
    if s = "Quindicesima" then Ok C__e_octave_shift_kind__Quindicesima else
    if s = "QuindicesimaBassa" then Ok C__e_octave_shift_kind__QuindicesimaBassa else
    Error ("unknown OctaveShiftKind: " ^ s)

type e_ornament_name =
  | C__e_ornament_name__Trill
  | C__e_ornament_name__Turn
  | C__e_ornament_name__InvertedTurn
  | C__e_ornament_name__Mordent
  | C__e_ornament_name__InvertedMordent
  | C__e_ornament_name__Tremolo

let enc_e_ornament_name (#num #flt: eqtype) (x: e_ornament_name) : Tot (jval num flt) =
  match x with
  | C__e_ornament_name__Trill -> JStr "Trill"
  | C__e_ornament_name__Turn -> JStr "Turn"
  | C__e_ornament_name__InvertedTurn -> JStr "InvertedTurn"
  | C__e_ornament_name__Mordent -> JStr "Mordent"
  | C__e_ornament_name__InvertedMordent -> JStr "InvertedMordent"
  | C__e_ornament_name__Tremolo -> JStr "Tremolo"

let dec_e_ornament_name (#num #flt: eqtype) (el: jval num flt) : Tot (outcome e_ornament_name) =
  match as_string el with
  | Error e -> Error e
  | Ok s ->
    if s = "Trill" then Ok C__e_ornament_name__Trill else
    if s = "Turn" then Ok C__e_ornament_name__Turn else
    if s = "InvertedTurn" then Ok C__e_ornament_name__InvertedTurn else
    if s = "Mordent" then Ok C__e_ornament_name__Mordent else
    if s = "InvertedMordent" then Ok C__e_ornament_name__InvertedMordent else
    if s = "Tremolo" then Ok C__e_ornament_name__Tremolo else
    Error ("unknown OrnamentName: " ^ s)

type e_navigation_kind =
  | C__e_navigation_kind__Segno
  | C__e_navigation_kind__Coda
  | C__e_navigation_kind__DaCapo
  | C__e_navigation_kind__DaCapoAlFine
  | C__e_navigation_kind__DaCapoAlCoda
  | C__e_navigation_kind__DalSegno
  | C__e_navigation_kind__DalSegnoAlFine
  | C__e_navigation_kind__DalSegnoAlCoda
  | C__e_navigation_kind__Fine
  | C__e_navigation_kind__ToCoda

let enc_e_navigation_kind (#num #flt: eqtype) (x: e_navigation_kind) : Tot (jval num flt) =
  match x with
  | C__e_navigation_kind__Segno -> JStr "Segno"
  | C__e_navigation_kind__Coda -> JStr "Coda"
  | C__e_navigation_kind__DaCapo -> JStr "DaCapo"
  | C__e_navigation_kind__DaCapoAlFine -> JStr "DaCapoAlFine"
  | C__e_navigation_kind__DaCapoAlCoda -> JStr "DaCapoAlCoda"
  | C__e_navigation_kind__DalSegno -> JStr "DalSegno"
  | C__e_navigation_kind__DalSegnoAlFine -> JStr "DalSegnoAlFine"
  | C__e_navigation_kind__DalSegnoAlCoda -> JStr "DalSegnoAlCoda"
  | C__e_navigation_kind__Fine -> JStr "Fine"
  | C__e_navigation_kind__ToCoda -> JStr "ToCoda"

let dec_e_navigation_kind (#num #flt: eqtype) (el: jval num flt) : Tot (outcome e_navigation_kind) =
  match as_string el with
  | Error e -> Error e
  | Ok s ->
    if s = "Segno" then Ok C__e_navigation_kind__Segno else
    if s = "Coda" then Ok C__e_navigation_kind__Coda else
    if s = "DaCapo" then Ok C__e_navigation_kind__DaCapo else
    if s = "DaCapoAlFine" then Ok C__e_navigation_kind__DaCapoAlFine else
    if s = "DaCapoAlCoda" then Ok C__e_navigation_kind__DaCapoAlCoda else
    if s = "DalSegno" then Ok C__e_navigation_kind__DalSegno else
    if s = "DalSegnoAlFine" then Ok C__e_navigation_kind__DalSegnoAlFine else
    if s = "DalSegnoAlCoda" then Ok C__e_navigation_kind__DalSegnoAlCoda else
    if s = "Fine" then Ok C__e_navigation_kind__Fine else
    if s = "ToCoda" then Ok C__e_navigation_kind__ToCoda else
    Error ("unknown NavigationKind: " ^ s)

(* ======================================================================================
   2. The vocabulary's types — one mutual group, because a record may hold a union, a
      union a node, and a node a list of nodes. Records are single-constructor types
      rather than F* records so that two objects declaring a `label` cannot collide.
   ====================================================================================== *)

type node (num flt: eqtype) =
  | C__node__Node : id:string -> k:(vkind num flt) -> node num flt

and vkind (num flt: eqtype) =
  | C__vkind__Score : children:(list (node num flt)) -> composer:(option (string)) -> title:(option (string)) -> vkind num flt
  | C__vkind__Part : children:(list (node num flt)) -> name:(string) -> staves:(list (r_staff_definition num flt)) -> vkind num flt
  | C__vkind__PartGroup : bracket:(e_bracket_kind) -> children:(list (node num flt)) -> name:(option (string)) -> vkind num flt
  | C__vkind__Measure : children:(list (node num flt)) -> is_anacrusis:(bool) -> number:(num) -> repeat_end:(bool) -> repeat_start:(bool) -> volta:(option (list (num))) -> vkind num flt
  | C__vkind__Staff : children:(list (node num flt)) -> staff_number:(num) -> vkind num flt
  | C__vkind__GraceNote : grace:(e_grace_kind) -> pitch:(r_pitch num flt) -> vkind num flt
  | C__vkind__Dynamic : level:(e_dynamic_level) -> vkind num flt
  | C__vkind__Fermata : vkind num flt
  | C__vkind__HairpinStart : hairpin:(e_hairpin_kind) -> vkind num flt
  | C__vkind__HairpinEnd : vkind num flt
  | C__vkind__SlurStart : vkind num flt
  | C__vkind__SlurEnd : vkind num flt
  | C__vkind__OctaveShiftStart : octave_shift:(e_octave_shift_kind) -> vkind num flt
  | C__vkind__OctaveShiftEnd : vkind num flt
  | C__vkind__MultiRest : measure_count:(num) -> vkind num flt
  | C__vkind__Ornament : ornament:(e_ornament_name) -> slash_count:(option (num)) -> vkind num flt
  | C__vkind__RehearsalMark : label:(string) -> vkind num flt
  | C__vkind__NavigationMark : navigation:(e_navigation_kind) -> vkind num flt
  | C__vkind__Form : arrangement:(list (string)) -> name:(option (string)) -> sections:(list (r_form_section num flt)) -> vkind num flt

and r_staff_definition (num flt: eqtype) =
  | C__r_staff_definition__Mk : clef:(e_clef_kind) -> initial_key:(r_key_signature num flt) -> initial_time:(r_time_signature num flt) -> number:(num) -> r_staff_definition num flt

and r_key_signature (num flt: eqtype) =
  | C__r_key_signature__Mk : mode:(e_mode) -> tonic:(e_note_letter) -> tonic_accidental:(e_accidental) -> r_key_signature num flt

and r_time_signature (num flt: eqtype) =
  | C__r_time_signature__Mk : denominator:(num) -> numerator:(num) -> r_time_signature num flt

and r_pitch (num flt: eqtype) =
  | C__r_pitch__Mk : accidental:(e_accidental) -> letter:(e_note_letter) -> midi:(num) -> octave:(num) -> r_pitch num flt

and r_form_section (num flt: eqtype) =
  | C__r_form_section__Mk : children:(list (node num flt)) -> label:(string) -> r_form_section num flt

(* ======================================================================================
   3. The encoder — the discriminated envelope, keys in the vocabulary's canonical
      order. The model has no render step, so the object LITERAL is the canonical form.
      Recursion is on the MODEL value, where F*'s subterm order spans the whole family.
   ====================================================================================== *)

(* The member-list SUFFIXES — one per conditional member of a constructor carrying two or
   more, bound once by the encoder below rather than written into both arms of a test.
   Opaque to the solver: only the per-suffix lemmas of the proof script look inside. *)

[@@"opaque_to_smt"]
let sfx_vkind__Score__composer (#num #flt: eqtype) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Tot (list (string & jval num flt)) =
  match e with | None -> rest | Some v -> ("composer", v) :: rest

[@@"opaque_to_smt"]
let sfx_vkind__Score__title (#num #flt: eqtype) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Tot (list (string & jval num flt)) =
  match e with | None -> rest | Some v -> ("title", v) :: rest

[@@"opaque_to_smt"]
let sfx_vkind__Measure__is_anacrusis (#num #flt: eqtype) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Tot (list (string & jval num flt)) =
  match e with | None -> rest | Some v -> ("isAnacrusis", v) :: rest

[@@"opaque_to_smt"]
let sfx_vkind__Measure__repeat_end (#num #flt: eqtype) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Tot (list (string & jval num flt)) =
  match e with | None -> rest | Some v -> ("repeatEnd", v) :: rest

[@@"opaque_to_smt"]
let sfx_vkind__Measure__repeat_start (#num #flt: eqtype) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Tot (list (string & jval num flt)) =
  match e with | None -> rest | Some v -> ("repeatStart", v) :: rest

[@@"opaque_to_smt"]
let sfx_vkind__Measure__volta (#num #flt: eqtype) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Tot (list (string & jval num flt)) =
  match e with | None -> rest | Some v -> ("volta", v) :: rest

(* The member READERS — one per conditional member of a suffixed constructor whose read calls
   nothing in the decoder family, applied by the decoder below rather than inlined into it.
   Opaque to the solver: only the per-reader value lemmas of the proof script look inside. *)

[@@"opaque_to_smt"]
let rd_vkind__Score__composer (#num #flt: eqtype) (el: jval num flt) : Tot (outcome (option (string))) =
  (match get_prop "composer" el with | Error _ -> Ok None | Ok v -> (match as_string v with | Error e -> Error e | Ok w -> Ok (Some w)))

[@@"opaque_to_smt"]
let rd_vkind__Score__title (#num #flt: eqtype) (el: jval num flt) : Tot (outcome (option (string))) =
  (match get_prop "title" el with | Error _ -> Ok None | Ok v -> (match as_string v with | Error e -> Error e | Ok w -> Ok (Some w)))

[@@"opaque_to_smt"]
let rd_vkind__Measure__is_anacrusis (#num #flt: eqtype) (el: jval num flt) : Tot (outcome (bool)) =
  (match get_prop "isAnacrusis" el with | Error _ -> Ok false | Ok v -> (match as_bool v with | Error e -> Error e | Ok w -> Ok w))

[@@"opaque_to_smt"]
let rd_vkind__Measure__repeat_end (#num #flt: eqtype) (el: jval num flt) : Tot (outcome (bool)) =
  (match get_prop "repeatEnd" el with | Error _ -> Ok false | Ok v -> (match as_bool v with | Error e -> Error e | Ok w -> Ok w))

[@@"opaque_to_smt"]
let rd_vkind__Measure__repeat_start (#num #flt: eqtype) (el: jval num flt) : Tot (outcome (bool)) =
  (match get_prop "repeatStart" el with | Error _ -> Ok false | Ok v -> (match as_bool v with | Error e -> Error e | Ok w -> Ok w))

let rec enc_node (#num #flt: eqtype) (x: node num flt) : Tot (jval num flt) (decreases x) =
  match x with
  | C__node__Node i k  ->
    JObj (("id", JStr i) :: ("kind", enc_vkind k) :: [])

and enc_vkind (#num #flt: eqtype) (x: vkind num flt) : Tot (jval num flt) (decreases x) =
  match x with
  | C__vkind__Score f0 f1 f2 ->
    JObj (("kind", JStr "Score") :: (let s1 = sfx_vkind__Score__title #num #flt (enc_opt_str #num #flt f2) ([]) in let s0 = sfx_vkind__Score__composer #num #flt (enc_opt_str #num #flt f1) (s1) in ("children", JArr (enc_items_l_node f0)) :: s0))
  | C__vkind__Part f0 f1 f2 ->
    JObj (("kind", JStr "Part") :: ("children", JArr (enc_items_l_node f0)) :: ("name", JStr f1) :: ("staves", JArr (enc_items_l_r_staff_definition f2)) :: [])
  | C__vkind__PartGroup f0 f1 f2 ->
    JObj (("kind", JStr "PartGroup") :: ("bracket", enc_e_bracket_kind f0) :: ("children", JArr (enc_items_l_node f1)) :: (match f2 with | None -> [] | Some w -> ("name", JStr w) :: []))
  | C__vkind__Measure f0 f1 f2 f3 f4 f5 ->
    JObj (("kind", JStr "Measure") :: (let s3 = sfx_vkind__Measure__volta #num #flt (enc_opt_l_int #num #flt f5) ([]) in let s2 = sfx_vkind__Measure__repeat_start #num #flt (enc_dflt_bool #num #flt (false) f4) (s3) in let s1 = sfx_vkind__Measure__repeat_end #num #flt (enc_dflt_bool #num #flt (false) f3) (s2) in let s0 = sfx_vkind__Measure__is_anacrusis #num #flt (enc_dflt_bool #num #flt (false) f1) (("number", JInt f2) :: s1) in ("children", JArr (enc_items_l_node f0)) :: s0))
  | C__vkind__Staff f0 f1 ->
    JObj (("kind", JStr "Staff") :: ("children", JArr (enc_items_l_node f0)) :: ("staffNumber", JInt f1) :: [])
  | C__vkind__GraceNote f0 f1 ->
    JObj (("kind", JStr "GraceNote") :: ("grace", enc_e_grace_kind f0) :: ("pitch", enc_r_pitch f1) :: [])
  | C__vkind__Dynamic f0 ->
    JObj (("kind", JStr "Dynamic") :: ("level", enc_e_dynamic_level f0) :: [])
  | C__vkind__Fermata  ->
    JObj (("kind", JStr "Fermata") :: [])
  | C__vkind__HairpinStart f0 ->
    JObj (("kind", JStr "HairpinStart") :: ("hairpin", enc_e_hairpin_kind f0) :: [])
  | C__vkind__HairpinEnd  ->
    JObj (("kind", JStr "HairpinEnd") :: [])
  | C__vkind__SlurStart  ->
    JObj (("kind", JStr "SlurStart") :: [])
  | C__vkind__SlurEnd  ->
    JObj (("kind", JStr "SlurEnd") :: [])
  | C__vkind__OctaveShiftStart f0 ->
    JObj (("kind", JStr "OctaveShiftStart") :: ("octaveShift", enc_e_octave_shift_kind f0) :: [])
  | C__vkind__OctaveShiftEnd  ->
    JObj (("kind", JStr "OctaveShiftEnd") :: [])
  | C__vkind__MultiRest f0 ->
    JObj (("kind", JStr "MultiRest") :: ("measureCount", JInt f0) :: [])
  | C__vkind__Ornament f0 f1 ->
    JObj (("kind", JStr "Ornament") :: ("ornament", enc_e_ornament_name f0) :: (match f1 with | None -> [] | Some w -> ("slashCount", JInt w) :: []))
  | C__vkind__RehearsalMark f0 ->
    JObj (("kind", JStr "RehearsalMark") :: ("label", JStr f0) :: [])
  | C__vkind__NavigationMark f0 ->
    JObj (("kind", JStr "NavigationMark") :: ("navigation", enc_e_navigation_kind f0) :: [])
  | C__vkind__Form f0 f1 f2 ->
    JObj (("kind", JStr "Form") :: ("arrangement", JArr (enc_items_l_str f0)) :: (match f1 with | None -> ("sections", JArr (enc_items_l_r_form_section f2)) :: [] | Some w -> ("name", JStr w) :: ("sections", JArr (enc_items_l_r_form_section f2)) :: []))

and enc_r_staff_definition (#num #flt: eqtype) (x: r_staff_definition num flt) : Tot (jval num flt) (decreases x) =
  match x with
  | C__r_staff_definition__Mk f0 f1 f2 f3 -> JObj (("clef", enc_e_clef_kind f0) :: ("initialKey", enc_r_key_signature f1) :: ("initialTime", enc_r_time_signature f2) :: ("number", JInt f3) :: [])

and enc_r_key_signature (#num #flt: eqtype) (x: r_key_signature num flt) : Tot (jval num flt) (decreases x) =
  match x with
  | C__r_key_signature__Mk f0 f1 f2 -> JObj (("mode", enc_e_mode f0) :: ("tonic", enc_e_note_letter f1) :: ("tonicAccidental", enc_e_accidental f2) :: [])

and enc_r_time_signature (#num #flt: eqtype) (x: r_time_signature num flt) : Tot (jval num flt) (decreases x) =
  match x with
  | C__r_time_signature__Mk f0 f1 -> JObj (("denominator", JInt f0) :: ("numerator", JInt f1) :: [])

and enc_r_pitch (#num #flt: eqtype) (x: r_pitch num flt) : Tot (jval num flt) (decreases x) =
  match x with
  | C__r_pitch__Mk f0 f1 f2 f3 -> JObj (("accidental", enc_e_accidental f0) :: ("letter", enc_e_note_letter f1) :: ("midi", JInt f2) :: ("octave", JInt f3) :: [])

and enc_r_form_section (#num #flt: eqtype) (x: r_form_section num flt) : Tot (jval num flt) (decreases x) =
  match x with
  | C__r_form_section__Mk f0 f1 -> JObj (("children", JArr (enc_items_l_node f0)) :: ("label", JStr f1) :: [])

and enc_items_l_node (#num #flt: eqtype) (xs: list (node num flt)) : Tot (list (jval num flt)) (decreases xs) =
  match xs with
  | [] -> []
  | y :: t -> enc_node y :: enc_items_l_node t

and enc_items_l_r_staff_definition (#num #flt: eqtype) (xs: list (r_staff_definition num flt)) : Tot (list (jval num flt)) (decreases xs) =
  match xs with
  | [] -> []
  | y :: t -> enc_r_staff_definition y :: enc_items_l_r_staff_definition t

and enc_items_l_int (#num #flt: eqtype) (xs: list (num)) : Tot (list (jval num flt)) (decreases xs) =
  match xs with
  | [] -> []
  | y :: t -> JInt y :: enc_items_l_int t

and enc_items_l_r_form_section (#num #flt: eqtype) (xs: list (r_form_section num flt)) : Tot (list (jval num flt)) (decreases xs) =
  match xs with
  | [] -> []
  | y :: t -> enc_r_form_section y :: enc_items_l_r_form_section t

and enc_items_l_str (#num #flt: eqtype) (xs: list (string)) : Tot (list (jval num flt)) (decreases xs) =
  match xs with
  | [] -> []
  | y :: t -> JStr y :: enc_items_l_str t

and enc_opt_str (#num #flt: eqtype) (o: option (string)) : Tot (option (jval num flt)) (decreases o) =
  match o with | None -> None | Some w -> Some (JStr w)

and enc_dflt_bool (#num #flt: eqtype) (d: bool) (v: bool) : Tot (option (jval num flt)) (decreases v) =
  if v = d then None else Some (JBool v)

and enc_opt_l_int (#num #flt: eqtype) (o: option (list (num))) : Tot (option (jval num flt)) (decreases o) =
  match o with | None -> None | Some w -> Some (JArr (enc_items_l_int w))

(* ======================================================================================
   4. The tag-dispatch decoder. Every cross-type call goes through `get_prop`, whose
      RETURN-TYPE refinement (`jsize (Ok?.v r) < jsize el`) is the termination argument:
      a decoder that descends by NAME into a value it looked up has no syntactic one.
      Value decoders sit at tier 0 on `jsize`, walkers at tier 1 on `jsizes` / `fsize`.
   ====================================================================================== *)

let rec dec_node (#num #flt: eqtype) (el: jval num flt) : Tot (outcome (node num flt)) (decreases %[(jsize el <: nat); 0]) =
  let oid : outcome string = str_field "id" el in
  let ok : outcome (vkind num flt) = (match get_prop "kind" el with | Error e -> Error e | Ok v -> dec_vkind v) in
  (match oid with | Error e -> Error e | Ok i -> (match ok with | Error e -> Error e | Ok k -> Ok (C__node__Node i k )))

and dec_vkind (#num #flt: eqtype) (el: jval num flt) : Tot (outcome (vkind num flt)) (decreases %[(jsize el <: nat); 0]) =
  match str_field "kind" el with
  | Error e -> Error e
  | Ok tag ->
    if tag = "Score" then
      let o0 : outcome (list (node num flt)) = (match get_prop "children" el with | Error e -> Error e | Ok v -> (match v with | JArr ys -> (match dec_items_l_node [] ys with | Error e -> Error e | Ok w -> Ok w) | other -> Error ("expected array, got " ^ kind_name other))) in
      let o1 : outcome (option (string)) = rd_vkind__Score__composer #num #flt el in
      let o2 : outcome (option (string)) = rd_vkind__Score__title #num #flt el in
      (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> (match o2 with | Error e -> Error e | Ok f2 -> Ok (C__vkind__Score f0 f1 f2))))
    else
    if tag = "Part" then
      let o0 : outcome (list (node num flt)) = (match get_prop "children" el with | Error e -> Error e | Ok v -> (match v with | JArr ys -> (match dec_items_l_node [] ys with | Error e -> Error e | Ok w -> Ok w) | other -> Error ("expected array, got " ^ kind_name other))) in
      let o1 : outcome (string) = (match get_prop "name" el with | Error e -> Error e | Ok v -> (match as_string v with | Error e -> Error e | Ok w -> Ok w)) in
      let o2 : outcome (list (r_staff_definition num flt)) = (match get_prop "staves" el with | Error e -> Error e | Ok v -> (match v with | JArr ys -> (match dec_items_l_r_staff_definition [] ys with | Error e -> Error e | Ok w -> Ok w) | other -> Error ("expected array, got " ^ kind_name other))) in
      (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> (match o2 with | Error e -> Error e | Ok f2 -> Ok (C__vkind__Part f0 f1 f2))))
    else
    if tag = "PartGroup" then
      let o0 : outcome (e_bracket_kind) = (match get_prop "bracket" el with | Error e -> Error e | Ok v -> (match dec_e_bracket_kind v with | Error e -> Error e | Ok w -> Ok w)) in
      let o1 : outcome (list (node num flt)) = (match get_prop "children" el with | Error e -> Error e | Ok v -> (match v with | JArr ys -> (match dec_items_l_node [] ys with | Error e -> Error e | Ok w -> Ok w) | other -> Error ("expected array, got " ^ kind_name other))) in
      let o2 : outcome (option (string)) = (match get_prop "name" el with | Error _ -> Ok None | Ok v -> (match as_string v with | Error e -> Error e | Ok w -> Ok (Some w))) in
      (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> (match o2 with | Error e -> Error e | Ok f2 -> Ok (C__vkind__PartGroup f0 f1 f2))))
    else
    if tag = "Measure" then
      let o0 : outcome (list (node num flt)) = (match get_prop "children" el with | Error e -> Error e | Ok v -> (match v with | JArr ys -> (match dec_items_l_node [] ys with | Error e -> Error e | Ok w -> Ok w) | other -> Error ("expected array, got " ^ kind_name other))) in
      let o1 : outcome (bool) = rd_vkind__Measure__is_anacrusis #num #flt el in
      let o2 : outcome (num) = (match get_prop "number" el with | Error e -> Error e | Ok v -> (match as_int v with | Error e -> Error e | Ok w -> Ok w)) in
      let o3 : outcome (bool) = rd_vkind__Measure__repeat_end #num #flt el in
      let o4 : outcome (bool) = rd_vkind__Measure__repeat_start #num #flt el in
      let o5 : outcome (option (list (num))) = (match get_prop "volta" el with | Error _ -> Ok None | Ok v -> (match v with | JArr ys -> (match dec_items_l_int [] ys with | Error e -> Error e | Ok w -> Ok (Some w)) | other -> Error ("expected array, got " ^ kind_name other))) in
      (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> (match o2 with | Error e -> Error e | Ok f2 -> (match o3 with | Error e -> Error e | Ok f3 -> (match o4 with | Error e -> Error e | Ok f4 -> (match o5 with | Error e -> Error e | Ok f5 -> Ok (C__vkind__Measure f0 f1 f2 f3 f4 f5)))))))
    else
    if tag = "Staff" then
      let o0 : outcome (list (node num flt)) = (match get_prop "children" el with | Error e -> Error e | Ok v -> (match v with | JArr ys -> (match dec_items_l_node [] ys with | Error e -> Error e | Ok w -> Ok w) | other -> Error ("expected array, got " ^ kind_name other))) in
      let o1 : outcome (num) = (match get_prop "staffNumber" el with | Error e -> Error e | Ok v -> (match as_int v with | Error e -> Error e | Ok w -> Ok w)) in
      (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> Ok (C__vkind__Staff f0 f1)))
    else
    if tag = "GraceNote" then
      let o0 : outcome (e_grace_kind) = (match get_prop "grace" el with | Error e -> Error e | Ok v -> (match dec_e_grace_kind v with | Error e -> Error e | Ok w -> Ok w)) in
      let o1 : outcome (r_pitch num flt) = (match get_prop "pitch" el with | Error e -> Error e | Ok v -> (match dec_r_pitch v with | Error e -> Error e | Ok w -> Ok w)) in
      (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> Ok (C__vkind__GraceNote f0 f1)))
    else
    if tag = "Dynamic" then
      let o0 : outcome (e_dynamic_level) = (match get_prop "level" el with | Error e -> Error e | Ok v -> (match dec_e_dynamic_level v with | Error e -> Error e | Ok w -> Ok w)) in
      (match o0 with | Error e -> Error e | Ok f0 -> Ok (C__vkind__Dynamic f0))
    else
    if tag = "Fermata" then
      Ok C__vkind__Fermata
    else
    if tag = "HairpinStart" then
      let o0 : outcome (e_hairpin_kind) = (match get_prop "hairpin" el with | Error e -> Error e | Ok v -> (match dec_e_hairpin_kind v with | Error e -> Error e | Ok w -> Ok w)) in
      (match o0 with | Error e -> Error e | Ok f0 -> Ok (C__vkind__HairpinStart f0))
    else
    if tag = "HairpinEnd" then
      Ok C__vkind__HairpinEnd
    else
    if tag = "SlurStart" then
      Ok C__vkind__SlurStart
    else
    if tag = "SlurEnd" then
      Ok C__vkind__SlurEnd
    else
    if tag = "OctaveShiftStart" then
      let o0 : outcome (e_octave_shift_kind) = (match get_prop "octaveShift" el with | Error e -> Error e | Ok v -> (match dec_e_octave_shift_kind v with | Error e -> Error e | Ok w -> Ok w)) in
      (match o0 with | Error e -> Error e | Ok f0 -> Ok (C__vkind__OctaveShiftStart f0))
    else
    if tag = "OctaveShiftEnd" then
      Ok C__vkind__OctaveShiftEnd
    else
    if tag = "MultiRest" then
      let o0 : outcome (num) = (match get_prop "measureCount" el with | Error e -> Error e | Ok v -> (match as_int v with | Error e -> Error e | Ok w -> Ok w)) in
      (match o0 with | Error e -> Error e | Ok f0 -> Ok (C__vkind__MultiRest f0))
    else
    if tag = "Ornament" then
      let o0 : outcome (e_ornament_name) = (match get_prop "ornament" el with | Error e -> Error e | Ok v -> (match dec_e_ornament_name v with | Error e -> Error e | Ok w -> Ok w)) in
      let o1 : outcome (option (num)) = (match get_prop "slashCount" el with | Error _ -> Ok None | Ok v -> (match as_int v with | Error e -> Error e | Ok w -> Ok (Some w))) in
      (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> Ok (C__vkind__Ornament f0 f1)))
    else
    if tag = "RehearsalMark" then
      let o0 : outcome (string) = (match get_prop "label" el with | Error e -> Error e | Ok v -> (match as_string v with | Error e -> Error e | Ok w -> Ok w)) in
      (match o0 with | Error e -> Error e | Ok f0 -> Ok (C__vkind__RehearsalMark f0))
    else
    if tag = "NavigationMark" then
      let o0 : outcome (e_navigation_kind) = (match get_prop "navigation" el with | Error e -> Error e | Ok v -> (match dec_e_navigation_kind v with | Error e -> Error e | Ok w -> Ok w)) in
      (match o0 with | Error e -> Error e | Ok f0 -> Ok (C__vkind__NavigationMark f0))
    else
    if tag = "Form" then
      let o0 : outcome (list (string)) = (match get_prop "arrangement" el with | Error e -> Error e | Ok v -> (match v with | JArr ys -> (match dec_items_l_str [] ys with | Error e -> Error e | Ok w -> Ok w) | other -> Error ("expected array, got " ^ kind_name other))) in
      let o1 : outcome (option (string)) = (match get_prop "name" el with | Error _ -> Ok None | Ok v -> (match as_string v with | Error e -> Error e | Ok w -> Ok (Some w))) in
      let o2 : outcome (list (r_form_section num flt)) = (match get_prop "sections" el with | Error e -> Error e | Ok v -> (match v with | JArr ys -> (match dec_items_l_r_form_section [] ys with | Error e -> Error e | Ok w -> Ok w) | other -> Error ("expected array, got " ^ kind_name other))) in
      (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> (match o2 with | Error e -> Error e | Ok f2 -> Ok (C__vkind__Form f0 f1 f2))))
    else
    Error ("unknown kind: " ^ tag)

and dec_r_staff_definition (#num #flt: eqtype) (el: jval num flt) : Tot (outcome (r_staff_definition num flt)) (decreases %[(jsize el <: nat); 0]) =
  let o0 : outcome (e_clef_kind) = (match get_prop "clef" el with | Error e -> Error e | Ok v -> (match dec_e_clef_kind v with | Error e -> Error e | Ok w -> Ok w)) in
  let o1 : outcome (r_key_signature num flt) = (match get_prop "initialKey" el with | Error e -> Error e | Ok v -> (match dec_r_key_signature v with | Error e -> Error e | Ok w -> Ok w)) in
  let o2 : outcome (r_time_signature num flt) = (match get_prop "initialTime" el with | Error e -> Error e | Ok v -> (match dec_r_time_signature v with | Error e -> Error e | Ok w -> Ok w)) in
  let o3 : outcome (num) = (match get_prop "number" el with | Error e -> Error e | Ok v -> (match as_int v with | Error e -> Error e | Ok w -> Ok w)) in
  (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> (match o2 with | Error e -> Error e | Ok f2 -> (match o3 with | Error e -> Error e | Ok f3 -> Ok (C__r_staff_definition__Mk f0 f1 f2 f3)))))

and dec_r_key_signature (#num #flt: eqtype) (el: jval num flt) : Tot (outcome (r_key_signature num flt)) (decreases %[(jsize el <: nat); 0]) =
  let o0 : outcome (e_mode) = (match get_prop "mode" el with | Error e -> Error e | Ok v -> (match dec_e_mode v with | Error e -> Error e | Ok w -> Ok w)) in
  let o1 : outcome (e_note_letter) = (match get_prop "tonic" el with | Error e -> Error e | Ok v -> (match dec_e_note_letter v with | Error e -> Error e | Ok w -> Ok w)) in
  let o2 : outcome (e_accidental) = (match get_prop "tonicAccidental" el with | Error e -> Error e | Ok v -> (match dec_e_accidental v with | Error e -> Error e | Ok w -> Ok w)) in
  (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> (match o2 with | Error e -> Error e | Ok f2 -> Ok (C__r_key_signature__Mk f0 f1 f2))))

and dec_r_time_signature (#num #flt: eqtype) (el: jval num flt) : Tot (outcome (r_time_signature num flt)) (decreases %[(jsize el <: nat); 0]) =
  let o0 : outcome (num) = (match get_prop "denominator" el with | Error e -> Error e | Ok v -> (match as_int v with | Error e -> Error e | Ok w -> Ok w)) in
  let o1 : outcome (num) = (match get_prop "numerator" el with | Error e -> Error e | Ok v -> (match as_int v with | Error e -> Error e | Ok w -> Ok w)) in
  (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> Ok (C__r_time_signature__Mk f0 f1)))

and dec_r_pitch (#num #flt: eqtype) (el: jval num flt) : Tot (outcome (r_pitch num flt)) (decreases %[(jsize el <: nat); 0]) =
  let o0 : outcome (e_accidental) = (match get_prop "accidental" el with | Error e -> Error e | Ok v -> (match dec_e_accidental v with | Error e -> Error e | Ok w -> Ok w)) in
  let o1 : outcome (e_note_letter) = (match get_prop "letter" el with | Error e -> Error e | Ok v -> (match dec_e_note_letter v with | Error e -> Error e | Ok w -> Ok w)) in
  let o2 : outcome (num) = (match get_prop "midi" el with | Error e -> Error e | Ok v -> (match as_int v with | Error e -> Error e | Ok w -> Ok w)) in
  let o3 : outcome (num) = (match get_prop "octave" el with | Error e -> Error e | Ok v -> (match as_int v with | Error e -> Error e | Ok w -> Ok w)) in
  (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> (match o2 with | Error e -> Error e | Ok f2 -> (match o3 with | Error e -> Error e | Ok f3 -> Ok (C__r_pitch__Mk f0 f1 f2 f3)))))

and dec_r_form_section (#num #flt: eqtype) (el: jval num flt) : Tot (outcome (r_form_section num flt)) (decreases %[(jsize el <: nat); 0]) =
  let o0 : outcome (list (node num flt)) = (match get_prop "children" el with | Error e -> Error e | Ok v -> (match v with | JArr ys -> (match dec_items_l_node [] ys with | Error e -> Error e | Ok w -> Ok w) | other -> Error ("expected array, got " ^ kind_name other))) in
  let o1 : outcome (string) = (match get_prop "label" el with | Error e -> Error e | Ok v -> (match as_string v with | Error e -> Error e | Ok w -> Ok w)) in
  (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> Ok (C__r_form_section__Mk f0 f1)))

and dec_items_l_node (#num #flt: eqtype) (acc: list (node num flt)) (ys: list (jval num flt)) : Tot (outcome (list (node num flt))) (decreases %[(jsizes ys <: nat); 1]) =
  match ys with
  | [] -> Ok (rev acc)
  | y :: rest ->
    (match dec_node y with
     | Ok w -> dec_items_l_node (w :: acc) rest
     | Error e -> Error e)

and dec_items_l_r_staff_definition (#num #flt: eqtype) (acc: list (r_staff_definition num flt)) (ys: list (jval num flt)) : Tot (outcome (list (r_staff_definition num flt))) (decreases %[(jsizes ys <: nat); 1]) =
  match ys with
  | [] -> Ok (rev acc)
  | y :: rest ->
    (match dec_r_staff_definition y with
     | Ok w -> dec_items_l_r_staff_definition (w :: acc) rest
     | Error e -> Error e)

and dec_items_l_int (#num #flt: eqtype) (acc: list (num)) (ys: list (jval num flt)) : Tot (outcome (list (num))) (decreases %[(jsizes ys <: nat); 1]) =
  match ys with
  | [] -> Ok (rev acc)
  | y :: rest ->
    (match as_int y with
     | Ok w -> dec_items_l_int (w :: acc) rest
     | Error e -> Error e)

and dec_items_l_r_form_section (#num #flt: eqtype) (acc: list (r_form_section num flt)) (ys: list (jval num flt)) : Tot (outcome (list (r_form_section num flt))) (decreases %[(jsizes ys <: nat); 1]) =
  match ys with
  | [] -> Ok (rev acc)
  | y :: rest ->
    (match dec_r_form_section y with
     | Ok w -> dec_items_l_r_form_section (w :: acc) rest
     | Error e -> Error e)

and dec_items_l_str (#num #flt: eqtype) (acc: list (string)) (ys: list (jval num flt)) : Tot (outcome (list (string))) (decreases %[(jsizes ys <: nat); 1]) =
  match ys with
  | [] -> Ok (rev acc)
  | y :: rest ->
    (match as_string y with
     | Ok w -> dec_items_l_str (w :: acc) rest
     | Error e -> Error e)

