(*
   Vocabulary — GENERATED by Fuaran.Core.Idl.Codegen's F* target from
   the engine's REFERENCE vocabulary — `tests/Fuaran.Core.Tests/ReferenceIdl.fs`, the
   domain-neutral `Idl` Phase 114 authored to reach the part of the type model no
   vendored sample uses (fuaran-core Phase 173, applying D14 to `proofs/`).
   DO NOT EDIT: `dotnet run --project tests/Fuaran.Core.Tests -- --emit-fstar` regenerates
   it, and the `Proofs.Vocabulary` family holds this file to a fresh generation from that
   source — a vocabulary that moves without a regeneration is VOCABULARY DRIFT, and
   `proofs/check.ps1` names it.

   WHAT THIS IS. The vocabulary's types, its discriminated encoder and its tag-dispatch
   decoder, over Phase 135's `jval` value model and the `Decode` combinators modelled
   beside it (`WireDecode.fst`). The theorems over it are in `VocabularyProofs.fst`, which
   the same generator emits from the same walk — so a kind added to the IDL re-proves
   itself at the next `check.ps1` rather than waiting for a hand-written clause.

   WHAT THIS IS NOT. It is not any host's decoder and no host's build generates it. A
   host keeps its own hand-written, tuned decoder and is certified against its corpus;
   what is proved here is a property of the
   F* BACKEND (`Fuaran.Core.Idl.Codegen`'s `FStarTarget`) over the vocabulary the engine
   is certified on — the same set the F# and TypeScript backends are certified over — and
   not of any domain's vocabulary. A domain proves its own vocabulary in its own
   repository with the same generator; the UI vocabulary's model is `fuaran#1754`'s.

   THE MODEL'S BOUNDARY, stated rather than implied.

     - The numeric carriers are OPAQUE (`num` / `flt`), as they are in `WireDecode`: no
       definition here looks inside a number, it only moves one. A float member therefore
       decodes from `JFloat` alone — the widening `as_float` performs through a supplied
       `to_flt` has nothing to widen when the carriers are parameters, and the encoder
       never emits an integer at a float slot.
     - A HOST-ONLY member has no wire projection and is absent from the model. The model
       is of the wire; a member that is never on the wire is not part of it.
     - A `TMap` is an ASSOCIATION LIST in the authored order. A map has no declared key
       order, and an assoc list is what the wire object is before a renderer sorts it.
     - A `TJson` member, and a host-codec member whose wire is JSON, is carried VERBATIM
       as a `jval`. What such a member holds is the host codec's business, not the
       schema's, and inventing an F* counterpart for a host type would model a fiction.
     - Generic unions are MONOMORPHISED at the arguments this vocabulary reaches, which
       is what keeps every definition and every emitted lemma first-order.

   VOCABULARY. Discriminator "$type", nested-kind envelope, ordinal-sorted key order.
   4 of 5 kinds are modelled; 4 declared types and 2 enums are reached.
   The kinds NOT modelled — named here rather than silently missing, because a reader
   of the theorem needs to know what it does not cover. Two different reasons, and
   they are worth telling apart: a construct with no wire-level meaning in the model
   is a BOUNDARY, while a kind held out of the proof vocabulary is a COST CONTROL
   that a measurement could lift:

     - Measure: the F* proof model cannot express a declared default the opaque numeric model cannot spell: VFloat 0.0 (at kind Measure.value)

   THE COST OPTION IS PART OF THE ARTEFACT. `--ext context_pruning` is set below rather
   than passed by the leg: this module opens the whole decode model and declares dozens
   of types, so every query would otherwise carry the entire context. Measured on the
   pinned prover it is the difference between a module the leg can afford and one it
   cannot — the same finding `TreeOps`, `JsonParse`, `Preservation` and `TreeDiff` each
   record in `modules.json`. If this module's budget is ever bumped, check the option is
   still here before reading the growth as ordinary.

   Apache-2.0, like everything beside it.
*)
module Vocabulary

open WireDecode

#set-options "--ext context_pruning"

(* ======================================================================================
   1. The closed string sets (`TEnum`) — a bare wire string, not an object.
   ====================================================================================== *)

type e_strictness =
  | C__e_strictness__StrictReplay
  | C__e_strictness__AdvisoryWarning

let enc_e_strictness (#num #flt: eqtype) (x: e_strictness) : Tot (jval num flt) =
  match x with
  | C__e_strictness__StrictReplay -> JStr "StrictReplay"
  | C__e_strictness__AdvisoryWarning -> JStr "AdvisoryWarning"

let dec_e_strictness (#num #flt: eqtype) (el: jval num flt) : Tot (outcome e_strictness) =
  match as_string el with
  | Error e -> Error e
  | Ok s ->
    if s = "StrictReplay" then Ok C__e_strictness__StrictReplay else
    if s = "AdvisoryWarning" then Ok C__e_strictness__AdvisoryWarning else
    Error ("unknown Strictness: " ^ s)

type e_layout_kind =
  | C__e_layout_kind__Stack
  | C__e_layout_kind__Row
  | C__e_layout_kind__Grid

let enc_e_layout_kind (#num #flt: eqtype) (x: e_layout_kind) : Tot (jval num flt) =
  match x with
  | C__e_layout_kind__Stack -> JStr "Stack"
  | C__e_layout_kind__Row -> JStr "Row"
  | C__e_layout_kind__Grid -> JStr "Grid"

let dec_e_layout_kind (#num #flt: eqtype) (el: jval num flt) : Tot (outcome e_layout_kind) =
  match as_string el with
  | Error e -> Error e
  | Ok s ->
    if s = "Stack" then Ok C__e_layout_kind__Stack else
    if s = "Row" then Ok C__e_layout_kind__Row else
    if s = "Grid" then Ok C__e_layout_kind__Grid else
    Error ("unknown LayoutKind: " ^ s)

(* ======================================================================================
   2. The vocabulary's types — one mutual group, because a record may hold a union, a
      union a node, and a node a list of nodes. Records are single-constructor types
      rather than F* records so that two objects declaring a `label` cannot collide.
   ====================================================================================== *)

type node (num flt: eqtype) =
  | C__node__Node : id:string -> k:(vkind num flt) -> hidden:(option (bool)) -> label:(option (string)) -> node num flt

and vkind (num flt: eqtype) =
  | C__vkind__Embed : component_id:(string) -> content_hash:(option (r_content_hash num flt)) -> module_id:(string) -> props:(option (list (string & jval num flt))) -> vkind num flt
  | C__vkind__Group : children:(list (node num flt)) -> layout:(e_layout_kind) -> on_select:(unit) -> vkind num flt
  | C__vkind__Link : href:(u_slot__str num flt) -> label:(u_text num flt) -> on_click:(unit) -> vkind num flt
  | C__vkind__Note : body:(u_text num flt) -> vkind num flt

and r_content_hash (num flt: eqtype) =
  | C__r_content_hash__Mk : hash:(string) -> strictness:(e_strictness) -> r_content_hash num flt

and u_slot__str (num flt: eqtype) =
  | C__u_slot__str__Fixed : value:(string) -> u_slot__str num flt
  | C__u_slot__str__Ref : name:(string) -> u_slot__str num flt

and u_text (num flt: eqtype) =
  | C__u_text__Inline : text:(string) -> u_text num flt
  | C__u_text__Lookup : args:(option (list (string & string))) -> key:(string) -> u_text num flt

(* ======================================================================================
   3. The encoder — the discriminated envelope, keys in the vocabulary's canonical
      order. The model has no render step, so the object LITERAL is the canonical form.
      Recursion is on the MODEL value, where F*'s subterm order spans the whole family.
   ====================================================================================== *)

(* The member-list SUFFIXES — one per conditional member of a constructor carrying two or
   more, bound once by the encoder below rather than written into both arms of a test.
   Opaque to the solver: only the per-suffix lemmas of the proof script look inside. *)

[@@"opaque_to_smt"]
let sfx_node__Node__hidden (#num #flt: eqtype) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Tot (list (string & jval num flt)) =
  match e with | None -> rest | Some v -> ("hidden", v) :: rest

[@@"opaque_to_smt"]
let sfx_node__Node__label (#num #flt: eqtype) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Tot (list (string & jval num flt)) =
  match e with | None -> rest | Some v -> ("label", v) :: rest

[@@"opaque_to_smt"]
let sfx_vkind__Embed__content_hash (#num #flt: eqtype) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Tot (list (string & jval num flt)) =
  match e with | None -> rest | Some v -> ("contentHash", v) :: rest

[@@"opaque_to_smt"]
let sfx_vkind__Embed__props (#num #flt: eqtype) (e: option (jval num flt)) (rest: list (string & jval num flt)) : Tot (list (string & jval num flt)) =
  match e with | None -> rest | Some v -> ("props", v) :: rest

(* The member READERS — one per conditional member of a suffixed constructor whose read calls
   nothing in the decoder family, applied by the decoder below rather than inlined into it.
   Opaque to the solver: only the per-reader value lemmas of the proof script look inside. *)

[@@"opaque_to_smt"]
let rd_node__Node__hidden (#num #flt: eqtype) (el: jval num flt) : Tot (outcome (option (bool))) =
  (match get_prop "hidden" el with | Error _ -> Ok None | Ok v -> (match as_bool v with | Error e -> Error e | Ok w -> Ok (Some w)))

[@@"opaque_to_smt"]
let rd_node__Node__label (#num #flt: eqtype) (el: jval num flt) : Tot (outcome (option (string))) =
  (match get_prop "label" el with | Error _ -> Ok None | Ok v -> (match as_string v with | Error e -> Error e | Ok w -> Ok (Some w)))

let rec enc_node (#num #flt: eqtype) (x: node num flt) : Tot (jval num flt) (decreases x) =
  match x with
  | C__node__Node i k e0 e1 ->
    JObj (("id", JStr i) :: ("kind", enc_vkind k) :: (let s1 = sfx_node__Node__label #num #flt (enc_opt_str #num #flt e1) ([]) in let s0 = sfx_node__Node__hidden #num #flt (enc_opt_bool #num #flt e0) (s1) in s0))

and enc_vkind (#num #flt: eqtype) (x: vkind num flt) : Tot (jval num flt) (decreases x) =
  match x with
  | C__vkind__Embed f0 f1 f2 f3 ->
    JObj (("$type", JStr "Embed") :: (let s1 = sfx_vkind__Embed__props #num #flt (enc_opt_m_json #num #flt f3) ([]) in let s0 = sfx_vkind__Embed__content_hash #num #flt (enc_opt_r_content_hash #num #flt f1) (("moduleId", JStr f2) :: s1) in ("componentId", JStr f0) :: s0))
  | C__vkind__Group f0 f1 f2 ->
    JObj (("$type", JStr "Group") :: ("children", JArr (enc_items_l_node f0)) :: (if f1 = C__e_layout_kind__Stack then ("onSelect", JStr "<closure>") :: [] else ("layout", enc_e_layout_kind f1) :: ("onSelect", JStr "<closure>") :: []))
  | C__vkind__Link f0 f1 f2 ->
    JObj (("$type", JStr "Link") :: ("href", enc_u_slot__str f0) :: ("label", enc_u_text f1) :: ("onClick", JStr "<closure>") :: [])
  | C__vkind__Note f0 ->
    JObj (("$type", JStr "Note") :: ("body", enc_u_text f0) :: [])

and enc_r_content_hash (#num #flt: eqtype) (x: r_content_hash num flt) : Tot (jval num flt) (decreases x) =
  match x with
  | C__r_content_hash__Mk f0 f1 -> JObj (("hash", JStr f0) :: ("strictness", enc_e_strictness f1) :: [])

and enc_u_slot__str (#num #flt: eqtype) (x: u_slot__str num flt) : Tot (jval num flt) (decreases x) =
  match x with
  | C__u_slot__str__Fixed f0 ->
    JObj (("$type", JStr "Fixed") :: ("value", JStr f0) :: [])
  | C__u_slot__str__Ref f0 ->
    JObj (("$type", JStr "Ref") :: ("name", JStr f0) :: [])

and enc_u_text (#num #flt: eqtype) (x: u_text num flt) : Tot (jval num flt) (decreases x) =
  match x with
  | C__u_text__Inline f0 ->
    JObj (("$type", JStr "Inline") :: ("text", JStr f0) :: [])
  | C__u_text__Lookup f0 f1 ->
    JObj (("$type", JStr "Lookup") :: (match f0 with | None -> ("key", JStr f1) :: [] | Some w -> ("args", JObj (enc_entries_m_str w)) :: ("key", JStr f1) :: []))

and enc_entries_m_json (#num #flt: eqtype) (es: list (string & jval num flt)) : Tot (list (string & jval num flt)) (decreases es) =
  match es with
  | [] -> []
  | (k, v) :: t -> (k, v) :: enc_entries_m_json t

and enc_items_l_node (#num #flt: eqtype) (xs: list (node num flt)) : Tot (list (jval num flt)) (decreases xs) =
  match xs with
  | [] -> []
  | y :: t -> enc_node y :: enc_items_l_node t

and enc_entries_m_str (#num #flt: eqtype) (es: list (string & string)) : Tot (list (string & jval num flt)) (decreases es) =
  match es with
  | [] -> []
  | (k, v) :: t -> (k, JStr v) :: enc_entries_m_str t

and enc_opt_bool (#num #flt: eqtype) (o: option (bool)) : Tot (option (jval num flt)) (decreases o) =
  match o with | None -> None | Some w -> Some (JBool w)

and enc_opt_str (#num #flt: eqtype) (o: option (string)) : Tot (option (jval num flt)) (decreases o) =
  match o with | None -> None | Some w -> Some (JStr w)

and enc_opt_r_content_hash (#num #flt: eqtype) (o: option (r_content_hash num flt)) : Tot (option (jval num flt)) (decreases o) =
  match o with | None -> None | Some w -> Some (enc_r_content_hash w)

and enc_opt_m_json (#num #flt: eqtype) (o: option (list (string & jval num flt))) : Tot (option (jval num flt)) (decreases o) =
  match o with | None -> None | Some w -> Some (JObj (enc_entries_m_json w))

(* ======================================================================================
   4. The tag-dispatch decoder. Every cross-type call goes through `get_prop`, whose
      RETURN-TYPE refinement (`jsize (Ok?.v r) < jsize el`) is the termination argument:
      a decoder that descends by NAME into a value it looked up has no syntactic one.
      Value decoders sit at tier 0 on `jsize`, walkers at tier 1 on `jsizes` / `fsize`.
   ====================================================================================== *)

let rec dec_node (#num #flt: eqtype) (el: jval num flt) : Tot (outcome (node num flt)) (decreases %[(jsize el <: nat); 0]) =
  let oid : outcome string = str_field "id" el in
  let ok : outcome (vkind num flt) = (match get_prop "kind" el with | Error e -> Error e | Ok v -> dec_vkind v) in
  let o0 : outcome (option (bool)) = rd_node__Node__hidden #num #flt el in
  let o1 : outcome (option (string)) = rd_node__Node__label #num #flt el in
  (match oid with | Error e -> Error e | Ok i -> (match ok with | Error e -> Error e | Ok k -> (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> Ok (C__node__Node i k f0 f1)))))

and dec_vkind (#num #flt: eqtype) (el: jval num flt) : Tot (outcome (vkind num flt)) (decreases %[(jsize el <: nat); 0]) =
  match str_field "$type" el with
  | Error e -> Error e
  | Ok tag ->
    if tag = "Embed" then
      let o0 : outcome (string) = (match get_prop "componentId" el with | Error e -> Error e | Ok v -> (match as_string v with | Error e -> Error e | Ok w -> Ok w)) in
      let o1 : outcome (option (r_content_hash num flt)) = (match get_prop "contentHash" el with | Error _ -> Ok None | Ok v -> (match dec_r_content_hash v with | Error e -> Error e | Ok w -> Ok (Some w))) in
      let o2 : outcome (string) = (match get_prop "moduleId" el with | Error e -> Error e | Ok v -> (match as_string v with | Error e -> Error e | Ok w -> Ok w)) in
      let o3 : outcome (option (list (string & jval num flt))) = (match get_prop "props" el with | Error _ -> Ok None | Ok v -> (match v with | JObj fs -> (match dec_entries_m_json [] fs with | Error e -> Error e | Ok w -> Ok (Some w)) | other -> Error ("expected object, got " ^ kind_name other))) in
      (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> (match o2 with | Error e -> Error e | Ok f2 -> (match o3 with | Error e -> Error e | Ok f3 -> Ok (C__vkind__Embed f0 f1 f2 f3)))))
    else
    if tag = "Group" then
      let o0 : outcome (list (node num flt)) = (match get_prop "children" el with | Error e -> Error e | Ok v -> (match v with | JArr ys -> (match dec_items_l_node [] ys with | Error e -> Error e | Ok w -> Ok w) | other -> Error ("expected array, got " ^ kind_name other))) in
      let o1 : outcome (e_layout_kind) = (match get_prop "layout" el with | Error _ -> Ok C__e_layout_kind__Stack | Ok v -> (match dec_e_layout_kind v with | Error e -> Error e | Ok w -> Ok w)) in
      let o2 : outcome (unit) = (match get_prop "onSelect" el with | Error e -> Error e | Ok v -> (let _ = v in let w = () in Ok w)) in
      (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> (match o2 with | Error e -> Error e | Ok f2 -> Ok (C__vkind__Group f0 f1 f2))))
    else
    if tag = "Link" then
      let o0 : outcome (u_slot__str num flt) = (match get_prop "href" el with | Error e -> Error e | Ok v -> (match dec_u_slot__str v with | Error e -> Error e | Ok w -> Ok w)) in
      let o1 : outcome (u_text num flt) = (match get_prop "label" el with | Error e -> Error e | Ok v -> (match dec_u_text v with | Error e -> Error e | Ok w -> Ok w)) in
      let o2 : outcome (unit) = (match get_prop "onClick" el with | Error e -> Error e | Ok v -> (let _ = v in let w = () in Ok w)) in
      (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> (match o2 with | Error e -> Error e | Ok f2 -> Ok (C__vkind__Link f0 f1 f2))))
    else
    if tag = "Note" then
      let o0 : outcome (u_text num flt) = (match get_prop "body" el with | Error e -> Error e | Ok v -> (match dec_u_text v with | Error e -> Error e | Ok w -> Ok w)) in
      (match o0 with | Error e -> Error e | Ok f0 -> Ok (C__vkind__Note f0))
    else
    Error ("unknown kind: " ^ tag)

and dec_r_content_hash (#num #flt: eqtype) (el: jval num flt) : Tot (outcome (r_content_hash num flt)) (decreases %[(jsize el <: nat); 0]) =
  let o0 : outcome (string) = (match get_prop "hash" el with | Error e -> Error e | Ok v -> (match as_string v with | Error e -> Error e | Ok w -> Ok w)) in
  let o1 : outcome (e_strictness) = (match get_prop "strictness" el with | Error e -> Error e | Ok v -> (match dec_e_strictness v with | Error e -> Error e | Ok w -> Ok w)) in
  (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> Ok (C__r_content_hash__Mk f0 f1)))

and dec_u_slot__str (#num #flt: eqtype) (el: jval num flt) : Tot (outcome (u_slot__str num flt)) (decreases %[(jsize el <: nat); 0]) =
  match str_field "$type" el with
  | Error e -> Error e
  | Ok tag ->
    if tag = "Fixed" then
      let o0 : outcome (string) = (match get_prop "value" el with | Error e -> Error e | Ok v -> (match as_string v with | Error e -> Error e | Ok w -> Ok w)) in
      (match o0 with | Error e -> Error e | Ok f0 -> Ok (C__u_slot__str__Fixed f0))
    else
    if tag = "Ref" then
      let o0 : outcome (string) = (match get_prop "name" el with | Error e -> Error e | Ok v -> (match as_string v with | Error e -> Error e | Ok w -> Ok w)) in
      (match o0 with | Error e -> Error e | Ok f0 -> Ok (C__u_slot__str__Ref f0))
    else
    Error ("unknown u_slot__str case: " ^ tag)

and dec_u_text (#num #flt: eqtype) (el: jval num flt) : Tot (outcome (u_text num flt)) (decreases %[(jsize el <: nat); 0]) =
  match str_field "$type" el with
  | Error e -> Error e
  | Ok tag ->
    if tag = "Inline" then
      let o0 : outcome (string) = (match get_prop "text" el with | Error e -> Error e | Ok v -> (match as_string v with | Error e -> Error e | Ok w -> Ok w)) in
      (match o0 with | Error e -> Error e | Ok f0 -> Ok (C__u_text__Inline f0))
    else
    if tag = "Lookup" then
      let o0 : outcome (option (list (string & string))) = (match get_prop "args" el with | Error _ -> Ok None | Ok v -> (match v with | JObj fs -> (match dec_entries_m_str [] fs with | Error e -> Error e | Ok w -> Ok (Some w)) | other -> Error ("expected object, got " ^ kind_name other))) in
      let o1 : outcome (string) = (match get_prop "key" el with | Error e -> Error e | Ok v -> (match as_string v with | Error e -> Error e | Ok w -> Ok w)) in
      (match o0 with | Error e -> Error e | Ok f0 -> (match o1 with | Error e -> Error e | Ok f1 -> Ok (C__u_text__Lookup f0 f1)))
    else
    Error ("unknown u_text case: " ^ tag)

and dec_entries_m_json (#num #flt: eqtype) (acc: list (string & jval num flt)) (fs: list (string & jval num flt)) : Tot (outcome (list (string & jval num flt))) (decreases %[(fsize fs <: nat); 1]) =
  match fs with
  | [] -> Ok (rev acc)
  | (k, v) :: rest ->
    (match Ok v with
     | Ok w -> dec_entries_m_json ((k, w) :: acc) rest
     | Error e -> Error e)

and dec_items_l_node (#num #flt: eqtype) (acc: list (node num flt)) (ys: list (jval num flt)) : Tot (outcome (list (node num flt))) (decreases %[(jsizes ys <: nat); 1]) =
  match ys with
  | [] -> Ok (rev acc)
  | y :: rest ->
    (match dec_node y with
     | Ok w -> dec_items_l_node (w :: acc) rest
     | Error e -> Error e)

and dec_entries_m_str (#num #flt: eqtype) (acc: list (string & string)) (fs: list (string & jval num flt)) : Tot (outcome (list (string & string))) (decreases %[(fsize fs <: nat); 1]) =
  match fs with
  | [] -> Ok (rev acc)
  | (k, v) :: rest ->
    (match as_string v with
     | Ok w -> dec_entries_m_str ((k, w) :: acc) rest
     | Error e -> Error e)

