(*
   VocabularyProofs — GENERATED by Fuaran.Core.Idl.Codegen's F* target, from the same walk that
   emits `Vocabulary.fst`, over
   the engine's REFERENCE vocabulary — `tests/Fuaran.Core.Tests/ReferenceIdl.fs`, the
   domain-neutral `Idl` Phase 114 authored to reach the part of the type model no
   vendored sample uses (fuaran-core Phase 173, applying D14 to `proofs/`).
   DO NOT EDIT: `dotnet run --project tests/Fuaran.Core.Tests -- --emit-fstar` regenerates
   it, and the `Proofs.Vocabulary` family holds this file to a fresh generation from that
   source — a vocabulary that moves without a regeneration is VOCABULARY DRIFT, and
   `proofs/check.ps1` names it.

   WHAT IS PROVED, and why it is GENERATED rather than written.

   Phase 135 proved `decode (encode n) == Ok n` for a hand-written four-case REFERENCE
   vocabulary, and was explicit about the boundary: a theorem about a reference vocabulary
   is not a theorem about the one a host actually decodes. The real vocabulary has dozens
   of kinds — 4 of this one's 5 are modelled — and it grows. A HAND-WRITTEN proof over
   it would be a theorem about the vocabulary as it stood on the day it was written, which
   is the same defect one release later. So the proof script is emitted by the walk that
   emits the model: a kind added to the IDL re-proves itself at the next `check.ps1`, and a
   kind whose encoder and decoder disagree fails it.

     - `rt_node` and the family beside it — THE ROUND TRIP. For every value of every
       modelled type, decoding its encoding returns that value: `dec_node (enc_node x) ==
       Ok x`, at every depth, through every list, map, optional member and omit-default.
     - `dec_node_total` — TOTALITY, and the exclusivity of the outcome. That the decoders
       type-check at `Tot` is the termination proof; the lemma states that every input
       reaches exactly one of `Ok` / `Error` and never both.

   THE SHAPE — one lemma per constructor, one per presence pattern (fuaran-core Phase 168).
   A constructor with k conditional members (optional, or omitted at its default) encodes
   to 2^k object shapes, and a lemma over the whole constructor puts all of them in ONE
   query. Measured at a twenty-kind vocabulary whose node envelope carried five optional
   members (Phase 150): the node lemma's 65-goal query failed a `--quake` seed at the leg's
   rlimit, the widest kind's arm failed outright, and raising the rlimit turned failing into
   grinding. `--split_queries` is not settable as a pragma on the pinned prover, so the
   isolation is in the emitted shape instead. `rt_<T>` is the round trip over a type — for a
   type with several constructors, a CASE SPLIT whose arms cite `rt_<T>__<Ctor>`, one
   constructor's arm alone under `C__<T>__<Ctor>? x`. A constructor with
   2 or more conditional members is split further: `rt_<T>__<Ctor>__p<bits>` proves ONE
   presence pattern, its `requires` pinning every conditional member present or absent so
   the encoder's nested match collapses to one object literal in the query, and the
   constructor's lemma is a split on exactly those members citing each. The family is still
   one mutual induction — a kind's children reach `rt_node` — on the lexicographic measure
   `%[x; tier]`, because the split lemmas recurse on the SAME value and differ only in how
   much of it they have fixed. Every query therefore carries at most one constructor's
   shapes, and a wide envelope or a wide kind costs 2^k small lemmas rather than one it
   cannot discharge. The rlimit precedent Phase 150 took (`--z3rlimit 200` in this file)
   is retired with the shape that needed it: the leg's own rlimit is what these are
   checked under, and a query that wants more is a query the split has failed to isolate.

   WHAT IS NOT PROVED HERE, and why. The `wf` CHARACTERISATION — `Ok? (dec el) == wf el`,
   which Phase 135 carries for its hand-written reference vocabulary — is not restated over
   the generated vocabulary. The only predicate this emitter could generate from the same
   walk is the decoder's own accept set restated clause for clause, and `Ok? (dec el) ==
   (that predicate) el` is then a theorem about two renderings of one definition — true,
   and empty. A characterisation worth the name needs an INDEPENDENT statement of the
   accept set (a schema-shaped predicate), which is a model-sized artefact of its own;
   `proofs/README.md` (theorem 1) records the halt. The round trip covers one direction
   (everything the encoder can produce is read back exactly); the characterisation of what
   ELSE is accepted is not covered, and is named here rather than left to be assumed.

   ONE COST OPTION IS PART OF THE ARTEFACT: `--ext context_pruning` is set below for the
   reason the model module's header gives at greater length — a mutual induction over the
   whole family would otherwise carry the whole family in every query. If this module is
   ever slow enough to want investigating, check it is still in force first.

   Apache-2.0, like everything beside it.
*)
module VocabularyProofs

open WireDecode
open Vocabulary

#set-options "--ext context_pruning"

(* ======================================================================================
   1. The closed string sets. Each is a finite match on distinct literals, so its round
      trip is definitional — stated anyway, because the family below calls it by name.
   ====================================================================================== *)

let rt_e_strictness (#num #flt: eqtype) (x: e_strictness) : Lemma (ensures dec_e_strictness (enc_e_strictness #num #flt x) == Ok x) = ()
let rt_e_layout_kind (#num #flt: eqtype) (x: e_layout_kind) : Lemma (ensures dec_e_layout_kind (enc_e_layout_kind #num #flt x) == Ok x) = ()

(* ======================================================================================
   2. THE ROUND TRIP. One mutual induction over the whole family, recursing on the MODEL
      value — F*'s subterm order spans a mutual inductive family, so each case needs only
      the sub-lemmas of the members it carries. ONE LEMMA PER CONSTRUCTOR, and one per
      PRESENCE PATTERN where a constructor's conditional members warrant it (the header
      says why): no query carries more than one constructor's object shapes.
   ====================================================================================== *)

let rec rt_node (#num #flt: eqtype) (x: node num flt) : Lemma (ensures dec_node (enc_node #num #flt x) == Ok x) (decreases %[x; 2]) =
  match x with
  | C__node__Node i k f0 f1 ->
    (match f0 with
      | None ->
        (match f1 with
          | None ->
            rt_node__p00 #num #flt x
          | Some _ ->
            rt_node__p01 #num #flt x
        )
      | Some _ ->
        (match f1 with
          | None ->
            rt_node__p10 #num #flt x
          | Some _ ->
            rt_node__p11 #num #flt x
        )
    )

(* rt_node__p00 — hidden absent, label absent *)
and rt_node__p00 (#num #flt: eqtype) (x: node num flt) : Lemma (requires (match x with | C__node__Node i k f0 f1 -> None? f0 && None? f1)) (ensures dec_node (enc_node #num #flt x) == Ok x) (decreases %[x; 0]) =
  match x with
  | C__node__Node i k f0 f1 -> rt_vkind #num #flt k

(* rt_node__p01 — hidden absent, label present *)
and rt_node__p01 (#num #flt: eqtype) (x: node num flt) : Lemma (requires (match x with | C__node__Node i k f0 f1 -> None? f0 && Some? f1)) (ensures dec_node (enc_node #num #flt x) == Ok x) (decreases %[x; 0]) =
  match x with
  | C__node__Node i k f0 f1 -> rt_vkind #num #flt k

(* rt_node__p10 — hidden present, label absent *)
and rt_node__p10 (#num #flt: eqtype) (x: node num flt) : Lemma (requires (match x with | C__node__Node i k f0 f1 -> Some? f0 && None? f1)) (ensures dec_node (enc_node #num #flt x) == Ok x) (decreases %[x; 0]) =
  match x with
  | C__node__Node i k f0 f1 -> rt_vkind #num #flt k

(* rt_node__p11 — hidden present, label present *)
and rt_node__p11 (#num #flt: eqtype) (x: node num flt) : Lemma (requires (match x with | C__node__Node i k f0 f1 -> Some? f0 && Some? f1)) (ensures dec_node (enc_node #num #flt x) == Ok x) (decreases %[x; 0]) =
  match x with
  | C__node__Node i k f0 f1 -> rt_vkind #num #flt k

and rt_vkind (#num #flt: eqtype) (x: vkind num flt) : Lemma (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 2]) =
  match x with
  | C__vkind__Embed _ _ _ _ -> rt_vkind__Embed #num #flt x
  | C__vkind__Group _ _ _ -> rt_vkind__Group #num #flt x
  | C__vkind__Link _ _ _ -> rt_vkind__Link #num #flt x
  | C__vkind__Note _ -> rt_vkind__Note #num #flt x

and rt_vkind__Embed (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__Embed? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__Embed f0 f1 f2 f3 ->
    (match f1 with
      | None ->
        (match f3 with
          | None ->
            rt_vkind__Embed__p00 #num #flt x
          | Some _ ->
            rt_vkind__Embed__p01 #num #flt x
        )
      | Some _ ->
        (match f3 with
          | None ->
            rt_vkind__Embed__p10 #num #flt x
          | Some _ ->
            rt_vkind__Embed__p11 #num #flt x
        )
    )

(* rt_vkind__Embed__p00 — contentHash absent, props absent *)
and rt_vkind__Embed__p00 (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (match x with | C__vkind__Embed f0 f1 f2 f3 -> None? f1 && None? f3 | _ -> false)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 0]) =
  match x with
  | C__vkind__Embed f0 f1 f2 f3 -> (match f1 with | None -> () | Some w -> rt_r_content_hash #num #flt w); (match f3 with | None -> () | Some w -> rt_entries_m_json #num #flt [] w)

(* rt_vkind__Embed__p01 — contentHash absent, props present *)
and rt_vkind__Embed__p01 (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (match x with | C__vkind__Embed f0 f1 f2 f3 -> None? f1 && Some? f3 | _ -> false)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 0]) =
  match x with
  | C__vkind__Embed f0 f1 f2 f3 -> (match f1 with | None -> () | Some w -> rt_r_content_hash #num #flt w); (match f3 with | None -> () | Some w -> rt_entries_m_json #num #flt [] w)

(* rt_vkind__Embed__p10 — contentHash present, props absent *)
and rt_vkind__Embed__p10 (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (match x with | C__vkind__Embed f0 f1 f2 f3 -> Some? f1 && None? f3 | _ -> false)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 0]) =
  match x with
  | C__vkind__Embed f0 f1 f2 f3 -> (match f1 with | None -> () | Some w -> rt_r_content_hash #num #flt w); (match f3 with | None -> () | Some w -> rt_entries_m_json #num #flt [] w)

(* rt_vkind__Embed__p11 — contentHash present, props present *)
and rt_vkind__Embed__p11 (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (match x with | C__vkind__Embed f0 f1 f2 f3 -> Some? f1 && Some? f3 | _ -> false)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 0]) =
  match x with
  | C__vkind__Embed f0 f1 f2 f3 -> (match f1 with | None -> () | Some w -> rt_r_content_hash #num #flt w); (match f3 with | None -> () | Some w -> rt_entries_m_json #num #flt [] w)

and rt_vkind__Group (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__Group? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__Group f0 f1 f2 -> rt_items_l_node #num #flt [] f0; rt_e_layout_kind #num #flt f1

and rt_vkind__Link (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__Link? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__Link f0 f1 f2 -> rt_u_slot__str #num #flt f0; rt_u_text #num #flt f1

and rt_vkind__Note (#num #flt: eqtype) (x: vkind num flt) : Lemma (requires (C__vkind__Note? x)) (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__vkind__Note f0 -> rt_u_text #num #flt f0

and rt_r_content_hash (#num #flt: eqtype) (x: r_content_hash num flt) : Lemma (ensures dec_r_content_hash (enc_r_content_hash #num #flt x) == Ok x) (decreases %[x; 2]) =
  match x with
  | C__r_content_hash__Mk f0 f1 -> rt_e_strictness #num #flt f1

and rt_u_slot__str (#num #flt: eqtype) (x: u_slot__str num flt) : Lemma (ensures dec_u_slot__str (enc_u_slot__str #num #flt x) == Ok x) (decreases %[x; 2]) =
  match x with
  | C__u_slot__str__Fixed _ -> rt_u_slot__str__Fixed #num #flt x
  | C__u_slot__str__Ref _ -> rt_u_slot__str__Ref #num #flt x

and rt_u_slot__str__Fixed (#num #flt: eqtype) (x: u_slot__str num flt) : Lemma (requires (C__u_slot__str__Fixed? x)) (ensures dec_u_slot__str (enc_u_slot__str #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__u_slot__str__Fixed f0 -> ()

and rt_u_slot__str__Ref (#num #flt: eqtype) (x: u_slot__str num flt) : Lemma (requires (C__u_slot__str__Ref? x)) (ensures dec_u_slot__str (enc_u_slot__str #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__u_slot__str__Ref f0 -> ()

and rt_u_text (#num #flt: eqtype) (x: u_text num flt) : Lemma (ensures dec_u_text (enc_u_text #num #flt x) == Ok x) (decreases %[x; 2]) =
  match x with
  | C__u_text__Inline _ -> rt_u_text__Inline #num #flt x
  | C__u_text__Lookup _ _ -> rt_u_text__Lookup #num #flt x

and rt_u_text__Inline (#num #flt: eqtype) (x: u_text num flt) : Lemma (requires (C__u_text__Inline? x)) (ensures dec_u_text (enc_u_text #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__u_text__Inline f0 -> ()

and rt_u_text__Lookup (#num #flt: eqtype) (x: u_text num flt) : Lemma (requires (C__u_text__Lookup? x)) (ensures dec_u_text (enc_u_text #num #flt x) == Ok x) (decreases %[x; 1]) =
  match x with
  | C__u_text__Lookup f0 f1 -> (match f0 with | None -> () | Some w -> rt_entries_m_str #num #flt [] w)

and rt_entries_m_json (#num #flt: eqtype) (acc: list (string & jval num flt)) (es: list (string & jval num flt)) : Lemma (ensures dec_entries_m_json acc (enc_entries_m_json #num #flt es) == Ok (rev_app acc es)) (decreases %[es; 2]) =
  match es with
  | [] -> ()
  | (k, v) :: t -> rt_entries_m_json #num #flt ((k, v) :: acc) t

and rt_items_l_node (#num #flt: eqtype) (acc: list (node num flt)) (xs: list (node num flt)) : Lemma (ensures dec_items_l_node acc (enc_items_l_node #num #flt xs) == Ok (rev_app acc xs)) (decreases %[xs; 2]) =
  match xs with
  | [] -> ()
  | y :: t -> rt_node #num #flt y; rt_items_l_node #num #flt (y :: acc) t

and rt_entries_m_str (#num #flt: eqtype) (acc: list (string & string)) (es: list (string & string)) : Lemma (ensures dec_entries_m_str acc (enc_entries_m_str #num #flt es) == Ok (rev_app acc es)) (decreases %[es; 2]) =
  match es with
  | [] -> ()
  | (k, v) :: t -> rt_entries_m_str #num #flt ((k, v) :: acc) t

(* ======================================================================================
   3. TOTALITY. That the decoders type-check at `Tot` is the termination proof; what the
      lemma adds is that the outcome is exactly one of the two, for EVERY input — the
      failure classification is exhaustive rather than merely non-empty.
   ====================================================================================== *)

let dec_node_total (#num #flt: eqtype) (el: jval num flt)
  : Lemma (ensures (Ok? (dec_node el) \/ Error? (dec_node el)) /\
                   ~(Ok? (dec_node el) /\ Error? (dec_node el)))
  = ()

