(*
   VocabularyVectors — GENERATED by Fuaran.Core.Idl.Codegen's F* target (fuaran-core Phase 303).
   DO NOT EDIT: the test project's `--emit-fstar` regenerates it from the three-way
   differential's vectors, and a generation diff holds it to that.

   For each vector, the reference interpreter's canonical bytes are parsed into the model's
   `jval` (instantiated at `num = int`, `flt = string`, a float carried as its canonical
   layout), and the value the interpreter DECODES those bytes to is written as the generated
   model's own value; `assert_norm` has the normaliser evaluate the model's `enc_node` on
   the value and compare it with the parsed bytes, member for member and key for key. The
   generated model and the interpreter agree on every vector, or this module does not
   check. What the facts cannot see, by construction: the float LAYOUT (`flt` is opaque to
   the model) and the WIRE_FORMAT section-7 sentinels (a non-finite float is spelled as a
   string the model's float slot does not carry) — the three-way differential covers both.
*)
module VocabularyVectors

open WireDecode
module D = DocVocabulary
module S = ScoreVocabulary
module R = Vocabulary

let d_v0 : D.node int string =
  (D.C__node__Document "a\"b" (Some "back\\slash") (D.C__e_locale__EnUS) (D.C__e_numbering__DecimalNumbering) ([(D.C__node__Table "node-1" None ([(D.C__node__Row "a\"b" (true) ([]))]))]))

let d_e0 : jval int string =
  (JObj [("kind", (JStr "Document")); ("id", (JStr "a\"b")); ("title", (JStr "back\\slash")); ("locale", (JStr "EnUS")); ("numbering", (JStr "DecimalNumbering")); ("children", (JArr [(JObj [("kind", (JStr "Table")); ("id", (JStr "node-1")); ("children", (JArr [(JObj [("kind", (JStr "Row")); ("id", (JStr "a\"b")); ("isHeader", (JBool true)); ("children", (JArr []))])]))])]))])

let d_v1 : D.node int string =
  (D.C__node__Section "a\"b" ([(D.C__u_run__Strong ([]))]) (D.C__e_heading_depth__H5) ([(D.C__node__Cell "a\"b" ([(D.C__u_run__Emphasis ([]))])); (D.C__node__Section "node-1" ([]) (D.C__e_heading_depth__H4) ([]))]))

let d_e1 : jval int string =
  (JObj [("kind", (JStr "Section")); ("id", (JStr "a\"b")); ("heading", (JArr [(JObj [("kind", (JStr "Strong")); ("runs", (JArr []))])])); ("depth", (JStr "H5")); ("children", (JArr [(JObj [("kind", (JStr "Cell")); ("id", (JStr "a\"b")); ("runs", (JArr [(JObj [("kind", (JStr "Emphasis")); ("runs", (JArr []))])]))]); (JObj [("kind", (JStr "Section")); ("id", (JStr "node-1")); ("heading", (JArr [])); ("depth", (JStr "H4")); ("children", (JArr []))])]))])

let d_v2 : D.node int string =
  (D.C__node__Paragraph "n" ([(D.C__u_run__InlineRef ("new\nline")); (D.C__u_run__Code (""))]))

let d_e2 : jval int string =
  (JObj [("kind", (JStr "Paragraph")); ("id", (JStr "n")); ("runs", (JArr [(JObj [("kind", (JStr "InlineRef")); ("target", (JStr "new\nline"))]); (JObj [("kind", (JStr "Code")); ("value", (JStr ""))])]))])

let d_v3 : D.node int string =
  (D.C__node__ListBlock "a\"b" (D.C__e_list_style__Numbered) ([(D.C__node__Paragraph "a\"b" ([(D.C__u_run__Link ("quote\" inside") ("quote\" inside"))])); (D.C__node__Caption "" ([(D.C__u_run__Strong ([])); (D.C__u_run__Strong ([]))]))]))

let d_e3 : jval int string =
  (JObj [("kind", (JStr "ListBlock")); ("id", (JStr "a\"b")); ("style", (JStr "Numbered")); ("children", (JArr [(JObj [("kind", (JStr "Paragraph")); ("id", (JStr "a\"b")); ("runs", (JArr [(JObj [("kind", (JStr "Link")); ("text", (JStr "quote\" inside")); ("url", (JStr "quote\" inside"))])]))]); (JObj [("kind", (JStr "Caption")); ("id", (JStr "")); ("runs", (JArr [(JObj [("kind", (JStr "Strong")); ("runs", (JArr []))]); (JObj [("kind", (JStr "Strong")); ("runs", (JArr []))])]))])]))])

let d_v4 : D.node int string =
  (D.C__node__ListItem "n" ([(D.C__node__Cell "node-1" ([(D.C__u_run__Code ("quote\" inside"))]))]))

let d_e4 : jval int string =
  (JObj [("kind", (JStr "ListItem")); ("id", (JStr "n")); ("children", (JArr [(JObj [("kind", (JStr "Cell")); ("id", (JStr "node-1")); ("runs", (JArr [(JObj [("kind", (JStr "Code")); ("value", (JStr "quote\" inside"))])]))])]))])

let d_v5 : D.node int string =
  (D.C__node__Table "n" (Some [(D.C__u_run__Link ("new\nline") ("new\nline"))]) ([(D.C__node__Caption "a\"b" ([(D.C__u_run__Code ("</script>"))])); (D.C__node__Caption "" ([]))]))

let d_e5 : jval int string =
  (JObj [("kind", (JStr "Table")); ("id", (JStr "n")); ("caption", (JArr [(JObj [("kind", (JStr "Link")); ("text", (JStr "new\nline")); ("url", (JStr "new\nline"))])])); ("children", (JArr [(JObj [("kind", (JStr "Caption")); ("id", (JStr "a\"b")); ("runs", (JArr [(JObj [("kind", (JStr "Code")); ("value", (JStr "</script>"))])]))]); (JObj [("kind", (JStr "Caption")); ("id", (JStr "")); ("runs", (JArr []))])]))])

let d_v6 : D.node int string =
  (D.C__node__Row "n" (false) ([(D.C__node__Table "n" (Some [(D.C__u_run__Code ("astral-😀")); (D.C__u_run__InlineVariable ("plain"))]) ([])); (D.C__node__ListItem "" ([]))]))

let d_e6 : jval int string =
  (JObj [("kind", (JStr "Row")); ("id", (JStr "n")); ("isHeader", (JBool false)); ("children", (JArr [(JObj [("kind", (JStr "Table")); ("id", (JStr "n")); ("caption", (JArr [(JObj [("kind", (JStr "Code")); ("value", (JStr "astral-😀"))]); (JObj [("kind", (JStr "InlineVariable")); ("field", (JStr "plain"))])])); ("children", (JArr []))]); (JObj [("kind", (JStr "ListItem")); ("id", (JStr "")); ("children", (JArr []))])]))])

let d_v7 : D.node int string =
  (D.C__node__Cell "a\"b" ([(D.C__u_run__InlineVariable ("quote\" inside"))]))

let d_e7 : jval int string =
  (JObj [("kind", (JStr "Cell")); ("id", (JStr "a\"b")); ("runs", (JArr [(JObj [("kind", (JStr "InlineVariable")); ("field", (JStr "quote\" inside"))])]))])

let d_v8 : D.node int string =
  (D.C__node__Figure "node-1" ("") ([]))

let d_e8 : jval int string =
  (JObj [("kind", (JStr "Figure")); ("id", (JStr "node-1")); ("source", (JStr "")); ("children", (JArr []))])

let d_v9 : D.node int string =
  (D.C__node__Caption "n" ([(D.C__u_run__InlineVariable ("astral-😀"))]))

let d_e9 : jval int string =
  (JObj [("kind", (JStr "Caption")); ("id", (JStr "n")); ("runs", (JArr [(JObj [("kind", (JStr "InlineVariable")); ("field", (JStr "astral-😀"))])]))])

let d_v10 : D.node int string =
  (D.C__node__Footnote "node-1" ([(D.C__node__Footnote "node-1" ([(D.C__node__Document "node-1" None (D.C__e_locale__EnGB) (D.C__e_numbering__LegalNumbering) ([])); (D.C__node__Footnote "n" ([]))])); (D.C__node__Figure "node-1" ("astral-😀") ([]))]))

let d_e10 : jval int string =
  (JObj [("kind", (JStr "Footnote")); ("id", (JStr "node-1")); ("children", (JArr [(JObj [("kind", (JStr "Footnote")); ("id", (JStr "node-1")); ("children", (JArr [(JObj [("kind", (JStr "Document")); ("id", (JStr "node-1")); ("locale", (JStr "EnGB")); ("numbering", (JStr "LegalNumbering")); ("children", (JArr []))]); (JObj [("kind", (JStr "Footnote")); ("id", (JStr "n")); ("children", (JArr []))])]))]); (JObj [("kind", (JStr "Figure")); ("id", (JStr "node-1")); ("source", (JStr "astral-😀")); ("children", (JArr []))])]))])

let d_v11 : D.node int string =
  (D.C__node__Document "n" (Some "new\nline") (D.C__e_locale__EnGB) (D.C__e_numbering__DecimalNumbering) ([(D.C__node__ListItem "a\"b" ([(D.C__node__ListBlock "" (D.C__e_list_style__Roman) ([]))]))]))

let d_e11 : jval int string =
  (JObj [("kind", (JStr "Document")); ("id", (JStr "n")); ("title", (JStr "new\nline")); ("locale", (JStr "EnGB")); ("numbering", (JStr "DecimalNumbering")); ("children", (JArr [(JObj [("kind", (JStr "ListItem")); ("id", (JStr "a\"b")); ("children", (JArr [(JObj [("kind", (JStr "ListBlock")); ("id", (JStr "")); ("style", (JStr "Roman")); ("children", (JArr []))])]))])]))])

let d_vectors_agree : unit =
  assert_norm (D.enc_node d_v0 == d_e0);
  assert_norm (D.enc_node d_v1 == d_e1);
  assert_norm (D.enc_node d_v2 == d_e2);
  assert_norm (D.enc_node d_v3 == d_e3);
  assert_norm (D.enc_node d_v4 == d_e4);
  assert_norm (D.enc_node d_v5 == d_e5);
  assert_norm (D.enc_node d_v6 == d_e6);
  assert_norm (D.enc_node d_v7 == d_e7);
  assert_norm (D.enc_node d_v8 == d_e8);
  assert_norm (D.enc_node d_v9 == d_e9);
  assert_norm (D.enc_node d_v10 == d_e10);
  assert_norm (D.enc_node d_v11 == d_e11)

let s_v0 : S.node int string =
  (S.C__node__Score "" None None ([]))

let s_e0 : jval int string =
  (JObj [("kind", (JStr "Score")); ("id", (JStr "")); ("children", (JArr []))])

let s_v1 : S.node int string =
  (S.C__node__Part "node-1" ("tab\there") ([(S.C__r_staff_definition__Mk (0) (S.C__e_clef_kind__Treble) ((S.C__r_key_signature__Mk (S.C__e_note_letter__G) (S.C__e_accidental__Natural) (S.C__e_mode__LydianAugmented))) ((S.C__r_time_signature__Mk ((-7)) ((-1))))); (S.C__r_staff_definition__Mk (42) (S.C__e_clef_kind__Alto) ((S.C__r_key_signature__Mk (S.C__e_note_letter__A) (S.C__e_accidental__Flat) (S.C__e_mode__IonianAugmented))) ((S.C__r_time_signature__Mk (1) ((-2147483648)))))]) ([]))

let s_e1 : jval int string =
  (JObj [("kind", (JStr "Part")); ("id", (JStr "node-1")); ("name", (JStr "tab\there")); ("staves", (JArr [(JObj [("number", (JInt 0)); ("clef", (JStr "Treble")); ("initialKey", (JObj [("tonic", (JStr "G")); ("tonicAccidental", (JStr "Natural")); ("mode", (JStr "LydianAugmented"))])); ("initialTime", (JObj [("numerator", (JInt (-7))); ("denominator", (JInt (-1)))]))]); (JObj [("number", (JInt 42)); ("clef", (JStr "Alto")); ("initialKey", (JObj [("tonic", (JStr "A")); ("tonicAccidental", (JStr "Flat")); ("mode", (JStr "IonianAugmented"))])); ("initialTime", (JObj [("numerator", (JInt 1)); ("denominator", (JInt (-2147483648)))]))])])); ("children", (JArr []))])

let s_v2 : S.node int string =
  (S.C__node__Measure "" (1) (false) (false) None (false) ([(S.C__node__PartGroup "a\"b" (Some "") (S.C__e_bracket_kind__Brace) ([])); (S.C__node__NavigationMark "n" (S.C__e_navigation_kind__ToCoda))]))

let s_e2 : jval int string =
  (JObj [("kind", (JStr "Measure")); ("id", (JStr "")); ("number", (JInt 1)); ("children", (JArr [(JObj [("kind", (JStr "PartGroup")); ("id", (JStr "a\"b")); ("name", (JStr "")); ("bracket", (JStr "Brace")); ("children", (JArr []))]); (JObj [("kind", (JStr "NavigationMark")); ("id", (JStr "n")); ("navigation", (JStr "ToCoda"))])]))])

let s_v3 : S.node int string =
  (S.C__node__Staff "n" (42) ([(S.C__node__HairpinEnd ""); (S.C__node__Dynamic "node-1" (S.C__e_dynamic_level__Fortississimo))]))

let s_e3 : jval int string =
  (JObj [("kind", (JStr "Staff")); ("id", (JStr "n")); ("staffNumber", (JInt 42)); ("children", (JArr [(JObj [("kind", (JStr "HairpinEnd")); ("id", (JStr ""))]); (JObj [("kind", (JStr "Dynamic")); ("id", (JStr "node-1")); ("level", (JStr "Fortississimo"))])]))])

let s_v4 : S.node int string =
  (S.C__node__GraceNote "a\"b" ((S.C__r_pitch__Mk (S.C__e_note_letter__C) (S.C__e_accidental__Natural) ((-7)) (42))) (S.C__e_grace_kind__Appoggiatura))

let s_e4 : jval int string =
  (JObj [("kind", (JStr "GraceNote")); ("id", (JStr "a\"b")); ("pitch", (JObj [("letter", (JStr "C")); ("accidental", (JStr "Natural")); ("octave", (JInt (-7))); ("midi", (JInt 42))])); ("grace", (JStr "Appoggiatura"))])

let s_v5 : S.node int string =
  (S.C__node__Dynamic "node-1" (S.C__e_dynamic_level__Piano))

let s_e5 : jval int string =
  (JObj [("kind", (JStr "Dynamic")); ("id", (JStr "node-1")); ("level", (JStr "Piano"))])

let s_v6 : S.node int string =
  (S.C__node__Fermata "a\"b")

let s_e6 : jval int string =
  (JObj [("kind", (JStr "Fermata")); ("id", (JStr "a\"b"))])

let s_v7 : S.node int string =
  (S.C__node__HairpinStart "n" (S.C__e_hairpin_kind__Decrescendo))

let s_e7 : jval int string =
  (JObj [("kind", (JStr "HairpinStart")); ("id", (JStr "n")); ("hairpin", (JStr "Decrescendo"))])

let s_v8 : S.node int string =
  (S.C__node__HairpinEnd "node-1")

let s_e8 : jval int string =
  (JObj [("kind", (JStr "HairpinEnd")); ("id", (JStr "node-1"))])

let s_v9 : S.node int string =
  (S.C__node__SlurStart "a\"b")

let s_e9 : jval int string =
  (JObj [("kind", (JStr "SlurStart")); ("id", (JStr "a\"b"))])

let s_v10 : S.node int string =
  (S.C__node__SlurEnd "n")

let s_e10 : jval int string =
  (JObj [("kind", (JStr "SlurEnd")); ("id", (JStr "n"))])

let s_v11 : S.node int string =
  (S.C__node__OctaveShiftStart "a\"b" (S.C__e_octave_shift_kind__Ottava))

let s_e11 : jval int string =
  (JObj [("kind", (JStr "OctaveShiftStart")); ("id", (JStr "a\"b")); ("octaveShift", (JStr "Ottava"))])

let s_vectors_agree : unit =
  assert_norm (S.enc_node s_v0 == s_e0);
  assert_norm (S.enc_node s_v1 == s_e1);
  assert_norm (S.enc_node s_v2 == s_e2);
  assert_norm (S.enc_node s_v3 == s_e3);
  assert_norm (S.enc_node s_v4 == s_e4);
  assert_norm (S.enc_node s_v5 == s_e5);
  assert_norm (S.enc_node s_v6 == s_e6);
  assert_norm (S.enc_node s_v7 == s_e7);
  assert_norm (S.enc_node s_v8 == s_e8);
  assert_norm (S.enc_node s_v9 == s_e9);
  assert_norm (S.enc_node s_v10 == s_e10);
  assert_norm (S.enc_node s_v11 == s_e11)

let r_v0 : R.node int string =
  (R.C__node__Node "a\"b" (R.C__vkind__Embed ("") None ("astral-😀") (Some [("\\", (JFloat "1234.5"))])) (Some true) None)

let r_e0 : jval int string =
  (JObj [("hidden", (JBool true)); ("id", (JStr "a\"b")); ("kind", (JObj [("$type", (JStr "Embed")); ("componentId", (JStr "")); ("moduleId", (JStr "astral-😀")); ("props", (JObj [("\\", (JFloat "1234.5"))]))]))])

let r_v1 : R.node int string =
  (R.C__node__Node "a\"b" (R.C__vkind__Link ((R.C__u_slot__str__Fixed ("new\nline"))) ((R.C__u_text__Lookup (Some [("", "back\\slash")]) ("plain"))) (())) (Some false) (Some "</script>"))

let r_e1 : jval int string =
  (JObj [("hidden", (JBool false)); ("id", (JStr "a\"b")); ("kind", (JObj [("$type", (JStr "Link")); ("href", (JObj [("$type", (JStr "Fixed")); ("value", (JStr "new\nline"))])); ("label", (JObj [("$type", (JStr "Lookup")); ("args", (JObj [("", (JStr "back\\slash"))])); ("key", (JStr "plain"))])); ("onClick", (JStr "<closure>"))])); ("label", (JStr "</script>"))])

let r_v2 : R.node int string =
  (R.C__node__Node "a\"b" (R.C__vkind__Note ((R.C__u_text__Lookup (Some [("", "ctrl\u0001here")]) ("back\\slash")))) (Some false) (Some "astral-😀"))

let r_e2 : jval int string =
  (JObj [("hidden", (JBool false)); ("id", (JStr "a\"b")); ("kind", (JObj [("$type", (JStr "Note")); ("body", (JObj [("$type", (JStr "Lookup")); ("args", (JObj [("", (JStr "ctrl\u0001here"))])); ("key", (JStr "back\\slash"))]))])); ("label", (JStr "astral-😀"))])

let r_v3 : R.node int string =
  (R.C__node__Node "a\"b" (R.C__vkind__Group ([(R.C__node__Node "" (R.C__vkind__Embed ("quote\" inside") (Some (R.C__r_content_hash__Mk ("accent-é") (R.C__e_strictness__AdvisoryWarning))) ("new\nline") (Some [("a", (JStr "back\\slash")); ("a\"b", (JObj [("a", (JStr "astral-😀")); ("z", (JInt (-2147483648)))]))])) None (Some "accent-é")); (R.C__node__Node "" (R.C__vkind__Link ((R.C__u_slot__str__Ref ("tab\there"))) ((R.C__u_text__Inline ("accent-é"))) (())) (Some true) (Some "</script>"))]) (R.C__e_layout_kind__Stack) (())) (Some false) (Some "new\nline"))

let r_e3 : jval int string =
  (JObj [("hidden", (JBool false)); ("id", (JStr "a\"b")); ("kind", (JObj [("$type", (JStr "Group")); ("children", (JArr [(JObj [("id", (JStr "")); ("kind", (JObj [("$type", (JStr "Embed")); ("componentId", (JStr "quote\" inside")); ("contentHash", (JObj [("hash", (JStr "accent-é")); ("strictness", (JStr "AdvisoryWarning"))])); ("moduleId", (JStr "new\nline")); ("props", (JObj [("a", (JStr "back\\slash")); ("a\"b", (JObj [("a", (JStr "astral-😀")); ("z", (JInt (-2147483648)))]))]))])); ("label", (JStr "accent-é"))]); (JObj [("hidden", (JBool true)); ("id", (JStr "")); ("kind", (JObj [("$type", (JStr "Link")); ("href", (JObj [("$type", (JStr "Ref")); ("name", (JStr "tab\there"))])); ("label", (JObj [("$type", (JStr "Inline")); ("text", (JStr "accent-é"))])); ("onClick", (JStr "<closure>"))])); ("label", (JStr "</script>"))])])); ("onSelect", (JStr "<closure>"))])); ("label", (JStr "new\nline"))])

let r_v4 : R.node int string =
  (R.C__node__Node "a\"b" (R.C__vkind__Link ((R.C__u_slot__str__Ref ("astral-😀"))) ((R.C__u_text__Lookup (Some [("9", "plain")]) (""))) (())) (Some true) (Some "accent-é"))

let r_e4 : jval int string =
  (JObj [("hidden", (JBool true)); ("id", (JStr "a\"b")); ("kind", (JObj [("$type", (JStr "Link")); ("href", (JObj [("$type", (JStr "Ref")); ("name", (JStr "astral-😀"))])); ("label", (JObj [("$type", (JStr "Lookup")); ("args", (JObj [("9", (JStr "plain"))])); ("key", (JStr ""))])); ("onClick", (JStr "<closure>"))])); ("label", (JStr "accent-é"))])

let r_v5 : R.node int string =
  (R.C__node__Node "n" (R.C__vkind__Note ((R.C__u_text__Lookup (Some [("0", "quote\" inside"); ("10", "plain")]) ("plain")))) None (Some "back\\slash"))

let r_e5 : jval int string =
  (JObj [("id", (JStr "n")); ("kind", (JObj [("$type", (JStr "Note")); ("body", (JObj [("$type", (JStr "Lookup")); ("args", (JObj [("0", (JStr "quote\" inside")); ("10", (JStr "plain"))])); ("key", (JStr "plain"))]))])); ("label", (JStr "back\\slash"))])

let r_v6 : R.node int string =
  (R.C__node__Node "n" (R.C__vkind__Embed ("ctrl\u0001here") (Some (R.C__r_content_hash__Mk ("tab\there") (R.C__e_strictness__AdvisoryWarning))) ("</script>") (Some [("10", (JStr "ctrl\u0001here")); ("kind", (JInt 3))])) (Some false) None)

let r_e6 : jval int string =
  (JObj [("hidden", (JBool false)); ("id", (JStr "n")); ("kind", (JObj [("$type", (JStr "Embed")); ("componentId", (JStr "ctrl\u0001here")); ("contentHash", (JObj [("hash", (JStr "tab\there")); ("strictness", (JStr "AdvisoryWarning"))])); ("moduleId", (JStr "</script>")); ("props", (JObj [("10", (JStr "ctrl\u0001here")); ("kind", (JInt 3))]))]))])

let r_v7 : R.node int string =
  (R.C__node__Node "" (R.C__vkind__Embed ("back\\slash") (Some (R.C__r_content_hash__Mk ("plain") (R.C__e_strictness__StrictReplay))) ("quote\" inside") (Some [("0", (JStr "back\\slash"))])) None None)

let r_e7 : jval int string =
  (JObj [("id", (JStr "")); ("kind", (JObj [("$type", (JStr "Embed")); ("componentId", (JStr "back\\slash")); ("contentHash", (JObj [("hash", (JStr "plain")); ("strictness", (JStr "StrictReplay"))])); ("moduleId", (JStr "quote\" inside")); ("props", (JObj [("0", (JStr "back\\slash"))]))]))])

let r_v8 : R.node int string =
  (R.C__node__Node "" (R.C__vkind__Embed ("new\nline") (Some (R.C__r_content_hash__Mk ("astral-😀") (R.C__e_strictness__AdvisoryWarning))) ("astral-😀") (Some [("10", (JStr "")); ("_", (JInt 1))])) (Some false) (Some "plain"))

let r_e8 : jval int string =
  (JObj [("hidden", (JBool false)); ("id", (JStr "")); ("kind", (JObj [("$type", (JStr "Embed")); ("componentId", (JStr "new\nline")); ("contentHash", (JObj [("hash", (JStr "astral-😀")); ("strictness", (JStr "AdvisoryWarning"))])); ("moduleId", (JStr "astral-😀")); ("props", (JObj [("10", (JStr "")); ("_", (JInt 1))]))])); ("label", (JStr "plain"))])

let r_v9 : R.node int string =
  (R.C__node__Node "node-1" (R.C__vkind__Note ((R.C__u_text__Lookup (Some [("0", "back\\slash"); ("😀", "new\nline")]) ("tab\there")))) (Some false) (Some ""))

let r_e9 : jval int string =
  (JObj [("hidden", (JBool false)); ("id", (JStr "node-1")); ("kind", (JObj [("$type", (JStr "Note")); ("body", (JObj [("$type", (JStr "Lookup")); ("args", (JObj [("0", (JStr "back\\slash")); ("😀", (JStr "new\nline"))])); ("key", (JStr "tab\there"))]))])); ("label", (JStr ""))])

let r_v10 : R.node int string =
  (R.C__node__Node "a\"b" (R.C__vkind__Embed ("plain") (Some (R.C__r_content_hash__Mk ("ctrl\u0001here") (R.C__e_strictness__AdvisoryWarning))) ("astral-😀") (Some [("10", (JStr "new\nline")); ("kind", (JObj [("a", (JStr "plain")); ("z", (JInt (-7)))]))])) (Some true) (Some "ctrl\u0001here"))

let r_e10 : jval int string =
  (JObj [("hidden", (JBool true)); ("id", (JStr "a\"b")); ("kind", (JObj [("$type", (JStr "Embed")); ("componentId", (JStr "plain")); ("contentHash", (JObj [("hash", (JStr "ctrl\u0001here")); ("strictness", (JStr "AdvisoryWarning"))])); ("moduleId", (JStr "astral-😀")); ("props", (JObj [("10", (JStr "new\nline")); ("kind", (JObj [("a", (JStr "plain")); ("z", (JInt (-7)))]))]))])); ("label", (JStr "ctrl\u0001here"))])

let r_v11 : R.node int string =
  (R.C__node__Node "" (R.C__vkind__Embed ("back\\slash") None ("new\nline") (Some [("10", (JArr [(JInt (-1)); (JStr "quote\" inside")]))])) None None)

let r_e11 : jval int string =
  (JObj [("id", (JStr "")); ("kind", (JObj [("$type", (JStr "Embed")); ("componentId", (JStr "back\\slash")); ("moduleId", (JStr "new\nline")); ("props", (JObj [("10", (JArr [(JInt (-1)); (JStr "quote\" inside")]))]))]))])

let r_vectors_agree : unit =
  assert_norm (R.enc_node r_v0 == r_e0);
  assert_norm (R.enc_node r_v1 == r_e1);
  assert_norm (R.enc_node r_v2 == r_e2);
  assert_norm (R.enc_node r_v3 == r_e3);
  assert_norm (R.enc_node r_v4 == r_e4);
  assert_norm (R.enc_node r_v5 == r_e5);
  assert_norm (R.enc_node r_v6 == r_e6);
  assert_norm (R.enc_node r_v7 == r_e7);
  assert_norm (R.enc_node r_v8 == r_e8);
  assert_norm (R.enc_node r_v9 == r_e9);
  assert_norm (R.enc_node r_v10 == r_e10);
  assert_norm (R.enc_node r_v11 == r_e11)
