(*
   VocabularyProofs — GENERATED by Fuaran.Core.Idl.Codegen's F* target, from the same walk over the
   pinned wire-format IDL that emits `Vocabulary.fst` (fuaran-core Phase 150). DO NOT EDIT:
   `proofs/check.ps1` regenerates it and fails the leg on any difference.

   WHAT IS PROVED, and why it is GENERATED rather than written.

   Phase 135 proved `decode (encode n) == Ok n` for a hand-written four-case REFERENCE
   vocabulary, and was explicit about the boundary: a theorem about a reference vocabulary
   is not a theorem about the one a host actually decodes. The real vocabulary has dozens
   of kinds — 20 of this one's 43 are modelled — and it grows. A HAND-WRITTEN proof over
   it would be a theorem about the vocabulary as it stood on the day it was written, which
   is the same defect one release later. So the proof script is emitted by the walk that
   emits the model: a kind added to the IDL re-proves itself at the next `check.ps1`, and a
   kind whose encoder and decoder disagree fails it.

     - `rt_node` and the family beside it — THE ROUND TRIP. For every value of every
       modelled type, decoding its encoding returns that value: `dec_node (enc_node x) ==
       Ok x`, at every depth, through every list, map, optional member and omit-default.
     - `dec_node_total` — TOTALITY, and the exclusivity of the outcome. That the decoders
       type-check at `Tot` is the termination proof; the lemma states that every input
       reaches exactly one of `Ok` / `Error` and never both.

   WHAT IS NOT PROVED HERE. The `wf` CHARACTERISATION — `Ok? (dec el) == wf el`, which
   Phase 135 carries for the reference vocabulary — is not restated over the generated
   vocabulary: it needs a second generated predicate mirroring the decoder's accept set,
   which is a model-sized artefact of its own. The round trip covers one direction
   (everything the encoder can produce is read back exactly); the characterisation of what
   ELSE is accepted is not covered, and is named here rather than left to be assumed.

   TWO COST OPTIONS ARE PART OF THE ARTEFACT, and the second was MEASURED rather than
   guessed. `--ext context_pruning` is set below for the reason the model module's header
   gives at greater length: a mutual induction over the whole family would otherwise carry
   the whole family in every query.

   The other is a MEASURED finding rather than a default anybody chose. Under the leg's own
   `--quake 3` the node lemma proved 64 of 65 goals in a single query and FAILED the third
   seed at the leg's default rlimit of 40 — green standalone and red under `check.ps1`,
   exactly the shape `Preservation`'s `invert_applicable` records in `modules.json`, and
   exactly the failure an unquaked run hides. `--z3rlimit 200` is the same remedy that
   precedent took. It is a blunt one: the hard goal is hard because the node's five
   OPTIONAL envelope members put thirty-two object shapes in one query, and isolating that
   goal would be the sharper fix — `--split_queries` is not settable as a pragma on the
   pinned prover, so it would mean emitting the node's proof as several smaller lemmas,
   which is a successor phase's work rather than a flag. If this module is ever slow enough
   to want investigating, check both options are still in force first: losing the rlimit
   does not read as slowness, it reads as a flake.

   Apache-2.0, like everything beside it.
*)
module VocabularyProofs

open WireDecode
open Vocabulary

#set-options "--z3rlimit 200 --ext context_pruning"

(* ======================================================================================
   1. The closed string sets. Each is a finite match on distinct literals, so its round
      trip is definitional — stated anyway, because the family below calls it by name.
   ====================================================================================== *)

let rt_e_time_grain (#num #flt: eqtype) (x: e_time_grain) : Lemma (ensures dec_e_time_grain (enc_e_time_grain #num #flt x) == Ok x) = ()
let rt_e_date_style (#num #flt: eqtype) (x: e_date_style) : Lemma (ensures dec_e_date_style (enc_e_date_style #num #flt x) == Ok x) = ()
let rt_e_relative_time_unit (#num #flt: eqtype) (x: e_relative_time_unit) : Lemma (ensures dec_e_relative_time_unit (enc_e_relative_time_unit #num #flt x) == Ok x) = ()
let rt_e_duration_unit (#num #flt: eqtype) (x: e_duration_unit) : Lemma (ensures dec_e_duration_unit (enc_e_duration_unit #num #flt x) == Ok x) = ()
let rt_e_duration_style (#num #flt: eqtype) (x: e_duration_style) : Lemma (ensures dec_e_duration_style (enc_e_duration_style #num #flt x) == Ok x) = ()
let rt_e_live_region_kind (#num #flt: eqtype) (x: e_live_region_kind) : Lemma (ensures dec_e_live_region_kind (enc_e_live_region_kind #num #flt x) == Ok x) = ()
let rt_e_text_direction (#num #flt: eqtype) (x: e_text_direction) : Lemma (ensures dec_e_text_direction (enc_e_text_direction #num #flt x) == Ok x) = ()
let rt_e_emphasis (#num #flt: eqtype) (x: e_emphasis) : Lemma (ensures dec_e_emphasis (enc_e_emphasis #num #flt x) == Ok x) = ()
let rt_e_style_role (#num #flt: eqtype) (x: e_style_role) : Lemma (ensures dec_e_style_role (enc_e_style_role #num #flt x) == Ok x) = ()
let rt_e_tone_variant (#num #flt: eqtype) (x: e_tone_variant) : Lemma (ensures dec_e_tone_variant (enc_e_tone_variant #num #flt x) == Ok x) = ()
let rt_e_font_voice (#num #flt: eqtype) (x: e_font_voice) : Lemma (ensures dec_e_font_voice (enc_e_font_voice #num #flt x) == Ok x) = ()
let rt_e_style_weight (#num #flt: eqtype) (x: e_style_weight) : Lemma (ensures dec_e_style_weight (enc_e_style_weight #num #flt x) == Ok x) = ()
let rt_e_badge_variant (#num #flt: eqtype) (x: e_badge_variant) : Lemma (ensures dec_e_badge_variant (enc_e_badge_variant #num #flt x) == Ok x) = ()
let rt_e_image_aspect (#num #flt: eqtype) (x: e_image_aspect) : Lemma (ensures dec_e_image_aspect (enc_e_image_aspect #num #flt x) == Ok x) = ()
let rt_e_embed_permission (#num #flt: eqtype) (x: e_embed_permission) : Lemma (ensures dec_e_embed_permission (enc_e_embed_permission #num #flt x) == Ok x) = ()
let rt_e_capture_source (#num #flt: eqtype) (x: e_capture_source) : Lemma (ensures dec_e_capture_source (enc_e_capture_source #num #flt x) == Ok x) = ()
let rt_e_heading_variant (#num #flt: eqtype) (x: e_heading_variant) : Lemma (ensures dec_e_heading_variant (enc_e_heading_variant #num #flt x) == Ok x) = ()
let rt_e_icon_size (#num #flt: eqtype) (x: e_icon_size) : Lemma (ensures dec_e_icon_size (enc_e_icon_size #num #flt x) == Ok x) = ()
let rt_e_link_protection (#num #flt: eqtype) (x: e_link_protection) : Lemma (ensures dec_e_link_protection (enc_e_link_protection #num #flt x) == Ok x) = ()
let rt_e_math_display (#num #flt: eqtype) (x: e_math_display) : Lemma (ensures dec_e_math_display (enc_e_math_display #num #flt x) == Ok x) = ()
let rt_e_scroll_orientation (#num #flt: eqtype) (x: e_scroll_orientation) : Lemma (ensures dec_e_scroll_orientation (enc_e_scroll_orientation #num #flt x) == Ok x) = ()

(* ======================================================================================
   2. THE ROUND TRIP. One mutual induction over the whole family, recursing on the MODEL
      value — F*'s subterm order spans a mutual inductive family, so each case needs only
      the sub-lemmas of the members it carries.
   ====================================================================================== *)

let rec rt_node (#num #flt: eqtype) (x: node num flt) : Lemma (ensures dec_node (enc_node #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__node__Node i k f0 f1 f2 f3 f4 ->
    rt_vkind #num #flt k; (match f0 with | None -> () | Some w -> rt_r_accessibility #num #flt w); (match f1 with | None -> () | Some w -> rt_r_state_behaviour #num #flt w); (match f2 with | None -> () | Some w -> rt_r_semantic_style #num #flt w); (match f3 with | None -> () | Some w -> rt_u_text_source #num #flt w); (match f4 with | None -> () | Some w -> rt_u_binding__bool #num #flt w)

and rt_vkind (#num #flt: eqtype) (x: vkind num flt) : Lemma (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__vkind__Badge f0 f1 -> rt_u_text_source #num #flt f0; rt_e_badge_variant #num #flt f1
  | C__vkind__Callout f0 f1 f2 f3 f4 -> rt_u_text_source #num #flt f0; (match f2 with | None -> () | Some w -> rt_u_text_source #num #flt w); rt_e_tone_variant #num #flt f4
  | C__vkind__CodeBlock f0 f1 f2 f3 f4 -> rt_items_l_int #num #flt [] f2
  | C__vkind__Disclosure f0 f1 f2 f3 f4 -> rt_items_l_node #num #flt [] f0; rt_u_text_source #num #flt f2; rt_u_binding__bool #num #flt f4
  | C__vkind__Embed f0 f1 f2 f3 -> rt_e_image_aspect #num #flt f0; rt_items_l_e_embed_permission #num #flt [] f1; rt_u_binding__str #num #flt f2; rt_u_text_source #num #flt f3
  | C__vkind__ErrorBoundary f0 f1 -> rt_node #num #flt f0; rt_node #num #flt f1
  | C__vkind__Fact f0 f1 f2 f3 f4 f5 -> (match f1 with | None -> () | Some w -> rt_u_text_source #num #flt w); rt_u_text_source #num #flt f3; rt_e_tone_variant #num #flt f4; rt_u_text_source #num #flt f5
  | C__vkind__FileUpload f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 -> rt_items_l_str #num #flt [] f0; (match f2 with | None -> () | Some w -> rt_e_capture_source #num #flt w); (match f4 with | None -> () | Some w -> rt_u_binding__bool #num #flt w); rt_u_text_source #num #flt f6
  | C__vkind__Heading f0 f1 f2 -> rt_u_text_source #num #flt f1; rt_e_heading_variant #num #flt f2
  | C__vkind__Icon f0 f1 f2 f3 -> rt_e_icon_size #num #flt f2; rt_e_tone_variant #num #flt f3
  | C__vkind__Link f0 f1 f2 f3 f4 f5 -> rt_u_binding__str #num #flt f1; rt_u_text_source #num #flt f2; (match f3 with | None -> () | Some w -> rt_e_link_protection #num #flt w)
  | C__vkind__List f0 f1 -> rt_items_l_u_text_source #num #flt [] f0
  | C__vkind__Markdown f0 -> rt_u_text_source #num #flt f0
  | C__vkind__Math f0 f1 -> rt_e_math_display #num #flt f0
  | C__vkind__Progress f0 f1 f2 f3 f4 -> (match f0 with | None -> () | Some w -> rt_u_text_source #num #flt w); rt_u_binding__flt #num #flt f1; (match f3 with | None -> () | Some w -> rt_u_text_source #num #flt w); rt_e_tone_variant #num #flt f4
  | C__vkind__ScrollArea f0 f1 f2 f3 -> rt_items_l_node #num #flt [] f0; rt_e_scroll_orientation #num #flt f3
  | C__vkind__Skeleton f0 -> ()
  | C__vkind__SplitPanel f0 f1 -> rt_items_l_node #num #flt [] f0
  | C__vkind__SummaryList f0 f1 -> rt_items_l_node #num #flt [] f0; (match f1 with | None -> () | Some w -> rt_u_text_source #num #flt w)
  | C__vkind__Toast f0 f1 f2 f3 -> rt_u_text_source #num #flt f1; rt_u_binding__bool #num #flt f2; rt_e_tone_variant #num #flt f3

and rt_r_accessibility (#num #flt: eqtype) (x: r_accessibility num flt) : Lemma (ensures dec_r_accessibility (enc_r_accessibility #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__r_accessibility__Mk f0 f1 f2 f3 f4 f5 -> (match f1 with | None -> () | Some w -> rt_u_binding__bool #num #flt w); (match f2 with | None -> () | Some w -> rt_u_binding__str #num #flt w); (match f4 with | None -> () | Some w -> rt_e_live_region_kind #num #flt w)

and rt_u_binding__bool (#num #flt: eqtype) (x: u_binding__bool num flt) : Lemma (ensures dec_u_binding__bool (enc_u_binding__bool #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__u_binding__bool__Static f0 -> ()
  | C__u_binding__bool__Query f0 f1 -> (match f0 with | None -> () | Some w -> rt_items_l_str #num #flt [] w)
  | C__u_binding__bool__Filter f0 f1 -> ()
  | C__u_binding__bool__Selection f0 f1 f2 -> ()
  | C__u_binding__bool__State f0 f1 -> ()
  | C__u_binding__bool__Now f0 -> (match f0 with | None -> () | Some w -> rt_e_time_grain #num #flt w)
  | C__u_binding__bool__Computed f0 -> ()
  | C__u_binding__bool__Local f0 f1 f2 f3 f4 f5 f6 -> (match f0 with | None -> () | Some w -> rt_u_format #num #flt w); rt_u_local_flush_trigger #num #flt f2; rt_u_binding__bool #num #flt f4
  | C__u_binding__bool__Format f0 f1 f2 -> rt_u_format #num #flt f0; rt_u_locale_source #num #flt f1; rt_u_binding__flt #num #flt f2
  | C__u_binding__bool__I18n f0 f1 -> (match f0 with | None -> () | Some w -> rt_entries_m_u_binding__json #num #flt [] w)
  | C__u_binding__bool__Transform f0 f1 f2 -> (match f0 with | None -> () | Some w -> rt_items_l_r_transform_param #num #flt [] w); rt_items_l_json #num #flt [] f1
  | C__u_binding__bool__Expr f0 f1 -> (match f1 with | None -> () | Some w -> rt_items_l_r_transform_param #num #flt [] w)
  | C__u_binding__bool__Invoke f0 f1 -> rt_items_l_r_invoke_arg #num #flt [] f0

and rt_u_local_flush_trigger (#num #flt: eqtype) (x: u_local_flush_trigger num flt) : Lemma (ensures dec_u_local_flush_trigger (enc_u_local_flush_trigger #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__u_local_flush_trigger__OnBlur  -> ()
  | C__u_local_flush_trigger__OnSubmit  -> ()
  | C__u_local_flush_trigger__OnDebounce f0 -> ()
  | C__u_local_flush_trigger__OnCommitAction  -> ()

and rt_u_format (#num #flt: eqtype) (x: u_format num flt) : Lemma (ensures dec_u_format (enc_u_format #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__u_format__Number f0 -> ()
  | C__u_format__Currency f0 -> ()
  | C__u_format__Percent f0 -> ()
  | C__u_format__Date f0 -> rt_e_date_style #num #flt f0
  | C__u_format__RelativeTime f0 -> rt_e_relative_time_unit #num #flt f0
  | C__u_format__Duration f0 f1 -> rt_e_duration_style #num #flt f0; rt_e_duration_unit #num #flt f1
  | C__u_format__Since f0 -> (match f0 with | None -> () | Some w -> rt_e_relative_time_unit #num #flt w)

and rt_u_binding__flt (#num #flt: eqtype) (x: u_binding__flt num flt) : Lemma (ensures dec_u_binding__flt (enc_u_binding__flt #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__u_binding__flt__Static f0 -> ()
  | C__u_binding__flt__Query f0 f1 -> (match f0 with | None -> () | Some w -> rt_items_l_str #num #flt [] w)
  | C__u_binding__flt__Filter f0 f1 -> ()
  | C__u_binding__flt__Selection f0 f1 f2 -> ()
  | C__u_binding__flt__State f0 f1 -> ()
  | C__u_binding__flt__Now f0 -> (match f0 with | None -> () | Some w -> rt_e_time_grain #num #flt w)
  | C__u_binding__flt__Computed f0 -> ()
  | C__u_binding__flt__Local f0 f1 f2 f3 f4 f5 f6 -> (match f0 with | None -> () | Some w -> rt_u_format #num #flt w); rt_u_local_flush_trigger #num #flt f2; rt_u_binding__flt #num #flt f4
  | C__u_binding__flt__Format f0 f1 f2 -> rt_u_format #num #flt f0; rt_u_locale_source #num #flt f1; rt_u_binding__flt #num #flt f2
  | C__u_binding__flt__I18n f0 f1 -> (match f0 with | None -> () | Some w -> rt_entries_m_u_binding__json #num #flt [] w)
  | C__u_binding__flt__Transform f0 f1 f2 -> (match f0 with | None -> () | Some w -> rt_items_l_r_transform_param #num #flt [] w); rt_items_l_json #num #flt [] f1
  | C__u_binding__flt__Expr f0 f1 -> (match f1 with | None -> () | Some w -> rt_items_l_r_transform_param #num #flt [] w)
  | C__u_binding__flt__Invoke f0 f1 -> rt_items_l_r_invoke_arg #num #flt [] f0

and rt_u_locale_source (#num #flt: eqtype) (x: u_locale_source num flt) : Lemma (ensures dec_u_locale_source (enc_u_locale_source #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__u_locale_source__Ambient  -> ()
  | C__u_locale_source__Explicit f0 -> ()

and rt_u_binding__json (#num #flt: eqtype) (x: u_binding__json num flt) : Lemma (ensures dec_u_binding__json (enc_u_binding__json #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__u_binding__json__Static f0 -> ()
  | C__u_binding__json__Query f0 f1 -> (match f0 with | None -> () | Some w -> rt_items_l_str #num #flt [] w)
  | C__u_binding__json__Filter f0 f1 -> ()
  | C__u_binding__json__Selection f0 f1 f2 -> ()
  | C__u_binding__json__State f0 f1 -> ()
  | C__u_binding__json__Now f0 -> (match f0 with | None -> () | Some w -> rt_e_time_grain #num #flt w)
  | C__u_binding__json__Computed f0 -> ()
  | C__u_binding__json__Local f0 f1 f2 f3 f4 f5 f6 -> (match f0 with | None -> () | Some w -> rt_u_format #num #flt w); rt_u_local_flush_trigger #num #flt f2; rt_u_binding__json #num #flt f4
  | C__u_binding__json__Format f0 f1 f2 -> rt_u_format #num #flt f0; rt_u_locale_source #num #flt f1; rt_u_binding__flt #num #flt f2
  | C__u_binding__json__I18n f0 f1 -> (match f0 with | None -> () | Some w -> rt_entries_m_u_binding__json #num #flt [] w)
  | C__u_binding__json__Transform f0 f1 f2 -> (match f0 with | None -> () | Some w -> rt_items_l_r_transform_param #num #flt [] w); rt_items_l_json #num #flt [] f1
  | C__u_binding__json__Expr f0 f1 -> (match f1 with | None -> () | Some w -> rt_items_l_r_transform_param #num #flt [] w)
  | C__u_binding__json__Invoke f0 f1 -> rt_items_l_r_invoke_arg #num #flt [] f0

and rt_r_transform_param (#num #flt: eqtype) (x: r_transform_param num flt) : Lemma (ensures dec_r_transform_param (enc_r_transform_param #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__r_transform_param__Mk f0 f1 -> rt_u_binding__json #num #flt f0

and rt_r_invoke_arg (#num #flt: eqtype) (x: r_invoke_arg num flt) : Lemma (ensures dec_r_invoke_arg (enc_r_invoke_arg #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__r_invoke_arg__Mk f0 f1 -> ()

and rt_u_binding__str (#num #flt: eqtype) (x: u_binding__str num flt) : Lemma (ensures dec_u_binding__str (enc_u_binding__str #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__u_binding__str__Static f0 -> ()
  | C__u_binding__str__Query f0 f1 -> (match f0 with | None -> () | Some w -> rt_items_l_str #num #flt [] w)
  | C__u_binding__str__Filter f0 f1 -> ()
  | C__u_binding__str__Selection f0 f1 f2 -> ()
  | C__u_binding__str__State f0 f1 -> ()
  | C__u_binding__str__Now f0 -> (match f0 with | None -> () | Some w -> rt_e_time_grain #num #flt w)
  | C__u_binding__str__Computed f0 -> ()
  | C__u_binding__str__Local f0 f1 f2 f3 f4 f5 f6 -> (match f0 with | None -> () | Some w -> rt_u_format #num #flt w); rt_u_local_flush_trigger #num #flt f2; rt_u_binding__str #num #flt f4
  | C__u_binding__str__Format f0 f1 f2 -> rt_u_format #num #flt f0; rt_u_locale_source #num #flt f1; rt_u_binding__flt #num #flt f2
  | C__u_binding__str__I18n f0 f1 -> (match f0 with | None -> () | Some w -> rt_entries_m_u_binding__json #num #flt [] w)
  | C__u_binding__str__Transform f0 f1 f2 -> (match f0 with | None -> () | Some w -> rt_items_l_r_transform_param #num #flt [] w); rt_items_l_json #num #flt [] f1
  | C__u_binding__str__Expr f0 f1 -> (match f1 with | None -> () | Some w -> rt_items_l_r_transform_param #num #flt [] w)
  | C__u_binding__str__Invoke f0 f1 -> rt_items_l_r_invoke_arg #num #flt [] f0

and rt_r_state_behaviour (#num #flt: eqtype) (x: r_state_behaviour num flt) : Lemma (ensures dec_r_state_behaviour (enc_r_state_behaviour #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__r_state_behaviour__Mk f0 f1 f2 -> (match f0 with | None -> () | Some w -> rt_node #num #flt w); (match f2 with | None -> () | Some w -> rt_node #num #flt w)

and rt_r_semantic_style (#num #flt: eqtype) (x: r_semantic_style num flt) : Lemma (ensures dec_r_semantic_style (enc_r_semantic_style #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__r_semantic_style__Mk f0 f1 f2 f3 f4 f5 -> rt_e_text_direction #num #flt f0; rt_e_emphasis #num #flt f1; rt_e_style_role #num #flt f2; rt_e_tone_variant #num #flt f3; rt_e_font_voice #num #flt f4; rt_e_style_weight #num #flt f5

and rt_u_text_source (#num #flt: eqtype) (x: u_text_source num flt) : Lemma (ensures dec_u_text_source (enc_u_text_source #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__u_text_source__Literal f0 -> ()
  | C__u_text_source__Bound f0 -> rt_u_binding__str #num #flt f0
  | C__u_text_source__I18n f0 f1 -> rt_entries_m_json #num #flt [] f0

and rt_items_l_str (#num #flt: eqtype) (acc: list (string)) (xs: list (string)) : Lemma (ensures dec_items_l_str acc (enc_items_l_str #num #flt xs) == Ok (rev_app acc xs)) (decreases xs) =
  match xs with
  | [] -> ()
  | y :: t -> rt_items_l_str #num #flt (y :: acc) t

and rt_items_l_json (#num #flt: eqtype) (acc: list (jval num flt)) (xs: list (jval num flt)) : Lemma (ensures dec_items_l_json acc (enc_items_l_json #num #flt xs) == Ok (rev_app acc xs)) (decreases xs) =
  match xs with
  | [] -> ()
  | y :: t -> rt_items_l_json #num #flt (y :: acc) t

and rt_items_l_r_transform_param (#num #flt: eqtype) (acc: list (r_transform_param num flt)) (xs: list (r_transform_param num flt)) : Lemma (ensures dec_items_l_r_transform_param acc (enc_items_l_r_transform_param #num #flt xs) == Ok (rev_app acc xs)) (decreases xs) =
  match xs with
  | [] -> ()
  | y :: t -> rt_r_transform_param #num #flt y; rt_items_l_r_transform_param #num #flt (y :: acc) t

and rt_items_l_r_invoke_arg (#num #flt: eqtype) (acc: list (r_invoke_arg num flt)) (xs: list (r_invoke_arg num flt)) : Lemma (ensures dec_items_l_r_invoke_arg acc (enc_items_l_r_invoke_arg #num #flt xs) == Ok (rev_app acc xs)) (decreases xs) =
  match xs with
  | [] -> ()
  | y :: t -> rt_r_invoke_arg #num #flt y; rt_items_l_r_invoke_arg #num #flt (y :: acc) t

and rt_entries_m_u_binding__json (#num #flt: eqtype) (acc: list (string & u_binding__json num flt)) (es: list (string & u_binding__json num flt)) : Lemma (ensures dec_entries_m_u_binding__json acc (enc_entries_m_u_binding__json #num #flt es) == Ok (rev_app acc es)) (decreases es) =
  match es with
  | [] -> ()
  | (k, v) :: t -> rt_u_binding__json #num #flt v; rt_entries_m_u_binding__json #num #flt ((k, v) :: acc) t

and rt_entries_m_json (#num #flt: eqtype) (acc: list (string & jval num flt)) (es: list (string & jval num flt)) : Lemma (ensures dec_entries_m_json acc (enc_entries_m_json #num #flt es) == Ok (rev_app acc es)) (decreases es) =
  match es with
  | [] -> ()
  | (k, v) :: t -> rt_entries_m_json #num #flt ((k, v) :: acc) t

and rt_items_l_int (#num #flt: eqtype) (acc: list (num)) (xs: list (num)) : Lemma (ensures dec_items_l_int acc (enc_items_l_int #num #flt xs) == Ok (rev_app acc xs)) (decreases xs) =
  match xs with
  | [] -> ()
  | y :: t -> rt_items_l_int #num #flt (y :: acc) t

and rt_items_l_node (#num #flt: eqtype) (acc: list (node num flt)) (xs: list (node num flt)) : Lemma (ensures dec_items_l_node acc (enc_items_l_node #num #flt xs) == Ok (rev_app acc xs)) (decreases xs) =
  match xs with
  | [] -> ()
  | y :: t -> rt_node #num #flt y; rt_items_l_node #num #flt (y :: acc) t

and rt_items_l_e_embed_permission (#num #flt: eqtype) (acc: list (e_embed_permission)) (xs: list (e_embed_permission)) : Lemma (ensures dec_items_l_e_embed_permission acc (enc_items_l_e_embed_permission #num #flt xs) == Ok (rev_app acc xs)) (decreases xs) =
  match xs with
  | [] -> ()
  | y :: t -> rt_e_embed_permission #num #flt y; rt_items_l_e_embed_permission #num #flt (y :: acc) t

and rt_items_l_u_text_source (#num #flt: eqtype) (acc: list (u_text_source num flt)) (xs: list (u_text_source num flt)) : Lemma (ensures dec_items_l_u_text_source acc (enc_items_l_u_text_source #num #flt xs) == Ok (rev_app acc xs)) (decreases xs) =
  match xs with
  | [] -> ()
  | y :: t -> rt_u_text_source #num #flt y; rt_items_l_u_text_source #num #flt (y :: acc) t

(* ======================================================================================
   3. TOTALITY. That the decoders type-check at `Tot` is the termination proof; what the
      lemma adds is that the outcome is exactly one of the two, for EVERY input — the
      failure classification is exhaustive rather than merely non-empty.
   ====================================================================================== *)

let dec_node_total (#num #flt: eqtype) (el: jval num flt)
  : Lemma (ensures (Ok? (dec_node el) \/ Error? (dec_node el)) /\
                   ~(Ok? (dec_node el) /\ Error? (dec_node el)))
  = ()

