(*
   VocabularyProofs — GENERATED by Fuaran.Core.Idl.Codegen's F* target, from the same walk that
   emits `Vocabulary.fst`, over
   the engine's REFERENCE vocabulary — `tests/Fuaran.Core.Tests/ReferenceIdl.fs`, the
   domain-neutral `Idl` Phase 114 authored to reach the part of the type model no
   vendored sample uses (fuaran-core Phase 173, applying D14 to `proofs/`).
   DO NOT EDIT: `dotnet run --project tests/Fuaran.Core.Tests -- --emit-fstar` regenerates
   it, and the `Proofs.Vocabulary` family holds this file to a fresh generation from that
   source — a vocabulary that moves without a regeneration is VOCABULARY DRIFT, and
   `proofs/check.ps1` names it.

   WHAT IS PROVED, and why it is GENERATED rather than written.

   Phase 135 proved `decode (encode n) == Ok n` for a hand-written four-case REFERENCE
   vocabulary, and was explicit about the boundary: a theorem about a reference vocabulary
   is not a theorem about the one a host actually decodes. The real vocabulary has dozens
   of kinds — 4 of this one's 5 are modelled — and it grows. A HAND-WRITTEN proof over
   it would be a theorem about the vocabulary as it stood on the day it was written, which
   is the same defect one release later. So the proof script is emitted by the walk that
   emits the model: a kind added to the IDL re-proves itself at the next `check.ps1`, and a
   kind whose encoder and decoder disagree fails it.

     - `rt_node` and the family beside it — THE ROUND TRIP. For every value of every
       modelled type, decoding its encoding returns that value: `dec_node (enc_node x) ==
       Ok x`, at every depth, through every list, map, optional member and omit-default.
     - `dec_node_total` — TOTALITY, and the exclusivity of the outcome. That the decoders
       type-check at `Tot` is the termination proof; the lemma states that every input
       reaches exactly one of `Ok` / `Error` and never both.

   WHAT IS NOT PROVED HERE. The `wf` CHARACTERISATION — `Ok? (dec el) == wf el`, which
   Phase 135 carries for the reference vocabulary — is not restated over the generated
   vocabulary: it needs a second generated predicate mirroring the decoder's accept set,
   which is a model-sized artefact of its own. The round trip covers one direction
   (everything the encoder can produce is read back exactly); the characterisation of what
   ELSE is accepted is not covered, and is named here rather than left to be assumed.

   TWO COST OPTIONS ARE PART OF THE ARTEFACT, and the second was MEASURED rather than
   guessed. `--ext context_pruning` is set below for the reason the model module's header
   gives at greater length: a mutual induction over the whole family would otherwise carry
   the whole family in every query.

   The other is a MEASURED finding rather than a default anybody chose, and it was measured
   at the scale this emitter was first run at — a twenty-kind vocabulary whose node envelope
   carries five OPTIONAL members (fuaran-core Phase 150). Under the leg's own `--quake 3`
   that node lemma proved 64 of 65 goals in a single query and FAILED the third seed at the
   leg's default rlimit of 40 — green standalone and red under `check.ps1`, exactly the
   shape `Preservation`'s `invert_applicable` records in `modules.json`, and exactly the
   failure an unquaked run hides. `--z3rlimit 200` is the same remedy that precedent took.
   It is a blunt one: the hard goal is hard because k conditional envelope members put 2^k
   object shapes in one query, and isolating that goal would be the sharper fix —
   `--split_queries` is not settable as a pragma on the pinned prover, so it would mean
   emitting the node's proof as several smaller lemmas, which is a successor's work rather
   than a flag. A vocabulary with a small envelope never meets the goal and pays nothing for
   the option. If this module is ever slow enough to want investigating, check both options
   are still in force first: losing the rlimit does not read as slowness, it reads as a flake.

   Apache-2.0, like everything beside it.
*)
module VocabularyProofs

open WireDecode
open Vocabulary

#set-options "--z3rlimit 200 --ext context_pruning"

(* ======================================================================================
   1. The closed string sets. Each is a finite match on distinct literals, so its round
      trip is definitional — stated anyway, because the family below calls it by name.
   ====================================================================================== *)

let rt_e_strictness (#num #flt: eqtype) (x: e_strictness) : Lemma (ensures dec_e_strictness (enc_e_strictness #num #flt x) == Ok x) = ()
let rt_e_layout_kind (#num #flt: eqtype) (x: e_layout_kind) : Lemma (ensures dec_e_layout_kind (enc_e_layout_kind #num #flt x) == Ok x) = ()

(* ======================================================================================
   2. THE ROUND TRIP. One mutual induction over the whole family, recursing on the MODEL
      value — F*'s subterm order spans a mutual inductive family, so each case needs only
      the sub-lemmas of the members it carries.
   ====================================================================================== *)

let rec rt_node (#num #flt: eqtype) (x: node num flt) : Lemma (ensures dec_node (enc_node #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__node__Node i k f0 f1 ->
    rt_vkind #num #flt k

and rt_vkind (#num #flt: eqtype) (x: vkind num flt) : Lemma (ensures dec_vkind (enc_vkind #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__vkind__Embed f0 f1 f2 f3 -> (match f1 with | None -> () | Some w -> rt_r_content_hash #num #flt w); (match f3 with | None -> () | Some w -> rt_entries_m_json #num #flt [] w)
  | C__vkind__Group f0 f1 f2 -> rt_items_l_node #num #flt [] f0; rt_e_layout_kind #num #flt f1
  | C__vkind__Link f0 f1 f2 -> rt_u_slot__str #num #flt f0; rt_u_text #num #flt f1
  | C__vkind__Note f0 -> rt_u_text #num #flt f0

and rt_r_content_hash (#num #flt: eqtype) (x: r_content_hash num flt) : Lemma (ensures dec_r_content_hash (enc_r_content_hash #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__r_content_hash__Mk f0 f1 -> rt_e_strictness #num #flt f1

and rt_u_slot__str (#num #flt: eqtype) (x: u_slot__str num flt) : Lemma (ensures dec_u_slot__str (enc_u_slot__str #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__u_slot__str__Fixed f0 -> ()
  | C__u_slot__str__Ref f0 -> ()

and rt_u_text (#num #flt: eqtype) (x: u_text num flt) : Lemma (ensures dec_u_text (enc_u_text #num #flt x) == Ok x) (decreases x) =
  match x with
  | C__u_text__Inline f0 -> ()
  | C__u_text__Lookup f0 f1 -> (match f0 with | None -> () | Some w -> rt_entries_m_str #num #flt [] w)

and rt_entries_m_json (#num #flt: eqtype) (acc: list (string & jval num flt)) (es: list (string & jval num flt)) : Lemma (ensures dec_entries_m_json acc (enc_entries_m_json #num #flt es) == Ok (rev_app acc es)) (decreases es) =
  match es with
  | [] -> ()
  | (k, v) :: t -> rt_entries_m_json #num #flt ((k, v) :: acc) t

and rt_items_l_node (#num #flt: eqtype) (acc: list (node num flt)) (xs: list (node num flt)) : Lemma (ensures dec_items_l_node acc (enc_items_l_node #num #flt xs) == Ok (rev_app acc xs)) (decreases xs) =
  match xs with
  | [] -> ()
  | y :: t -> rt_node #num #flt y; rt_items_l_node #num #flt (y :: acc) t

and rt_entries_m_str (#num #flt: eqtype) (acc: list (string & string)) (es: list (string & string)) : Lemma (ensures dec_entries_m_str acc (enc_entries_m_str #num #flt es) == Ok (rev_app acc es)) (decreases es) =
  match es with
  | [] -> ()
  | (k, v) :: t -> rt_entries_m_str #num #flt ((k, v) :: acc) t

(* ======================================================================================
   3. TOTALITY. That the decoders type-check at `Tot` is the termination proof; what the
      lemma adds is that the outcome is exactly one of the two, for EVERY input — the
      failure classification is exhaustive rather than merely non-empty.
   ====================================================================================== *)

let dec_node_total (#num #flt: eqtype) (el: jval num flt)
  : Lemma (ensures (Ok? (dec_node el) \/ Error? (dec_node el)) /\
                   ~(Ok? (dec_node el) /\ Error? (dec_node el)))
  = ()

